In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import time
import glob
from datetime import datetime

In [107]:
def genIce(data, level, level_name):
    data_len, _ = data.shape
    print("data len = ", data_len)
    block_len = int(np.ceil(data_len/level))
    print("block_len", block_len)
    scores = []
    total_durations = []
    for i in range(level):
        start = i*block_len
        end = min(data_len, (i+1)*block_len)
        print("start = ", start, "  end = ", end)
        #print(df['duration'][start:end])
        #print(df['truth_int'][start:end])
        #print(df['weighted_truth'][start:end])
        total_duration = df['duration'][start:end].sum()
        total_durations.append(total_duration)
        #print(weighted_sum)
        #durations = df['duration'][start:end]
        #truth_ints = df['truth_int'][start:end]
        #print("truth_ints: ")
        #print(truth_ints)
        df_tmp = df[start:end]
        print(df_tmp['truth_int'])
        print(df_tmp['duration'])
        duration_3 = df_tmp.loc[df_tmp['truth_int'] == 3, 'duration'].sum()
        duration_2 = df_tmp.loc[df_tmp['truth_int'] == 2, 'duration'].sum()
        duration_1 = df_tmp.loc[df_tmp['truth_int'] == 1, 'duration'].sum()
        duration_0 = df_tmp.loc[df_tmp['truth_int'] == 0, 'duration'].sum()
        duration_unk = df_tmp.loc[df_tmp['truth_int'] == -1, 'duration'].sum()
        print("3: ", duration_3, "2: ", duration_2, "1: ", duration_1, "0: ", duration_0, "-1: ", duration_unk)
        
        print("total_duration = ",total_duration)
        assert(total_duration == duration_2 + duration_3+ duration_1+ duration_0+ duration_unk)
        dur_scores = []
        dur_scores.append(duration_unk)
        dur_scores.append(duration_0)
        dur_scores.append(duration_1)
        dur_scores.append(duration_2)
        dur_scores.append(duration_3)
        
        maxId = np.argmax(dur_scores)
        print("max Id: ", maxId-1)
        scores.append(maxId-1)
        #print(weighted_sum/duration)
        #print(round(weighted_sum/duration))
        #scores.append(round(weighted_sum/duration))
    return scores, total_durations

In [111]:
allFiles = glob.glob("*.csv")
movies = {}
for filename in allFiles:
    print(filename)
    name = (filename.split('.'))[0]
    print(name)
    df = pd.read_csv(filename)
    #print(df)
    #df['truth_int'] = df['truth_int'].astype('int64')
    try:
        df["weighted_truth"] = df['truth_int']*df['duration']
        division = [27, 9, 3, 1]
        for div in division:
            scores, total_durations = genIce(df, div, "ice"+ str(div))
            scores_df = pd.DataFrame()
            scores_df['truth_int'] = scores
            scores_df['duration'] = total_durations
            scores_df.to_csv(name+"_ice"+str(div)+".csv")
    except:
        print("failed for ", name)

12YearsaSlave.csv
12YearsaSlave
data len =  108
block_len 4
start =  0   end =  4
0    3
1    2
2    3
3    2
Name: truth_int, dtype: int64
0    41
1    42
2    13
3    32
Name: duration, dtype: int64
3:  54 2:  74 1:  0 0:  0 -1:  0
total_duration =  128
max Id:  2
start =  4   end =  8
4    2
5    0
6    3
7    3
Name: truth_int, dtype: int64
4     41
5    115
6     18
7     41
Name: duration, dtype: int64
3:  59 2:  41 1:  0 0:  115 -1:  0
total_duration =  215
max Id:  0
start =  8   end =  12
8     3
9     2
10    3
11    3
Name: truth_int, dtype: int64
8     28
9     40
10    29
11    24
Name: duration, dtype: int64
3:  81 2:  40 1:  0 0:  0 -1:  0
total_duration =  121
max Id:  3
start =  12   end =  16
12    2
13    3
14    3
15    2
Name: truth_int, dtype: int64
12    40
13    53
14    13
15    41
Name: duration, dtype: int64
3:  66 2:  81 1:  0 0:  0 -1:  0
total_duration =  147
max Id:  2
start =  16   end =  20
16    3
17    3
18    2
19    3
Name: truth_int, dtype: int64
16     34
17    284
18     69
19     35
Name: duration, dtype: int64
3:  353 2:  69 1:  0 0:  0 -1:  0
total_duration =  422
max Id:  3
start =  20   end =  24
20    3
21    3
22    3
23    3
Name: truth_int, dtype: int64
20    55
21    15
22    31
23    45
Name: duration, dtype: int64
3:  146 2:  0 1:  0 0:  0 -1:  0
total_duration =  146
max Id:  3
start =  24   end =  28
24    3
25   -1
26    2
27    0
Name: truth_int, dtype: int64
24    75
25    25
26    57
27    75
Name: duration, dtype: int64
3:  75 2:  57 1:  0 0:  75 -1:  25
total_duration =  232
max Id:  0
start =  28   end =  32
28    2
29    1
30    3
31    2
Name: truth_int, dtype: int64
28    34
29    40
30    23
31    80
Name: duration, dtype: int64
3:  23 2:  114 1:  40 0:  0 -1:  0
total_duration =  177
max Id:  2
start =  32   end =  36
32   -1
33    2
34    3
35    3
Name: truth_int, dtype: int64
32    24
33    49
34    29
35    39
Name: duration, dtype: int64
3:  68 2:  49 1:  0 0:  0 -1:  24
total_duration =  141
max Id:  3
start =  36   end =  40
36    2
37    3
38    3
39    3
Name: truth_int, dtype: int64
36    34
37    31
38    78
39    48
Name: duration, dtype: int64
3:  157 2:  34 1:  0 0:  0 -1:  0
total_duration =  191
max Id:  3
start =  40   end =  44
40    2
41    3
42    3
43    3
Name: truth_int, dtype: int64
40    68
41    63
42    18
43    52
Name: duration, dtype: int64
3:  133 2:  68 1:  0 0:  0 -1:  0
total_duration =  201
max Id:  3
start =  44   end =  48
44    2
45    2
46    0
47    2
Name: truth_int, dtype: int64
44     75
45     65
46     62
47    135
Name: duration, dtype: int64
3:  0 2:  275 1:  0 0:  62 -1:  0
total_duration =  337
max Id:  2
start =  48   end =  52
48    3
49    3
50    2
51    3
Name: truth_int, dtype: int64
48    27
49    80
50    26
51    70
Name: duration, dtype: int64
3:  177 2:  26 1:  0 0:  0 -1:  0
total_duration =  203
max Id:  3
start =  52   end =  56
52    3
53    3
54    3
55    2
Name: truth_int, dtype: int64
52    66
53    73
54    28
55    79
Name: duration, dtype: int64
3:  167 2:  79 1:  0 0:  0 -1:  0
total_duration =  246
max Id:  3
start =  56   end =  60
56    2
57    3
58    2
59    0
Name: truth_int, dtype: int64
56    174
57     10
58     67
59     60
Name: duration, dtype: int64
3:  10 2:  241 1:  0 0:  60 -1:  0
total_duration =  311
max Id:  2
start =  60   end =  64
60    2
61    3
62    3
63    3
Name: truth_int, dtype: int64
60     68
61     29
62    119
63     16
Name: duration, dtype: int64
3:  164 2:  68 1:  0 0:  0 -1:  0
total_duration =  232
max Id:  3
start =  64   end =  68
64   -1
65    3
66    3
67    3
Name: truth_int, dtype: int64
64    68
65    28
66    25
67    80
Name: duration, dtype: int64
3:  133 2:  0 1:  0 0:  0 -1:  68
total_duration =  201
max Id:  3
start =  68   end =  72
68    2
69   -1
70    3
71    1
Name: truth_int, dtype: int64
68    100
69    114
70     28
71     15
Name: duration, dtype: int64
3:  28 2:  100 1:  15 0:  0 -1:  114
total_duration =  257
max Id:  -1
start =  72   end =  76
72    0
73    2
74    3
75    3
Name: truth_int, dtype: int64
72    232
73    172
74     38
75    121
Name: duration, dtype: int64
3:  159 2:  172 1:  0 0:  232 -1:  0
total_duration =  563
max Id:  0
start =  76   end =  80
76    3
77    3
78    2
79    0
Name: truth_int, dtype: int64
76     23
77     35
78    127
79    154
Name: duration, dtype: int64
3:  58 2:  127 1:  0 0:  154 -1:  0
total_duration =  339
max Id:  0
start =  80   end =  84
80    2
81    2
82    2
83    3
Name: truth_int, dtype: int64
80    57
81    59
82    45
83    59
Name: duration, dtype: int64
3:  59 2:  161 1:  0 0:  0 -1:  0
total_duration =  220
max Id:  2
start =  84   end =  88
84    1
85    3
86   -1
87    3
Name: truth_int, dtype: int64
84     39
85     61
86    113
87     29
Name: duration, dtype: int64
3:  90 2:  0 1:  39 0:  0 -1:  113
total_duration =  242
max Id:  -1
start =  88   end =  92
88   -1
89    2
90    3
91    2
Name: truth_int, dtype: int64
88     47
89    107
90    123
91     45
Name: duration, dtype: int64
3:  123 2:  152 1:  0 0:  0 -1:  47
total_duration =  322
max Id:  2
start =  92   end =  96
92    3
93    3
94    0
95    0
Name: truth_int, dtype: int64
92    187
93     57
94     48
95     38
Name: duration, dtype: int64
3:  244 2:  0 1:  0 0:  86 -1:  0
total_duration =  330
max Id:  3
start =  96   end =  100
96    0
97    3
98    3
99    2
Name: truth_int, dtype: int64
96    130
97    211
98     79
99    390
Name: duration, dtype: int64
3:  290 2:  390 1:  0 0:  130 -1:  0
total_duration =  810
max Id:  2
start =  100   end =  104
100    3
101   -1
102    3
103    3
Name: truth_int, dtype: int64
100     52
101     44
102    231
103    105
Name: duration, dtype: int64
3:  388 2:  0 1:  0 0:  0 -1:  44
total_duration =  432
max Id:  3
start =  104   end =  108
104    2
105    3
106    2
107    3
Name: truth_int, dtype: int64
104    167
105     59
106    200
107     62
Name: duration, dtype: int64
3:  121 2:  367 1:  0 0:  0 -1:  0
total_duration =  488
max Id:  2
data len =  108
block_len 12
start =  0   end =  12
0     3
1     2
2     3
3     2
4     2
5     0
6     3
7     3
8     3
9     2
10    3
11    3
Name: truth_int, dtype: int64
0      41
1      42
2      13
3      32
4      41
5     115
6      18
7      41
8      28
9      40
10     29
11     24
Name: duration, dtype: int64
3:  194 2:  155 1:  0 0:  115 -1:  0
total_duration =  464
max Id:  3
start =  12   end =  24
12    2
13    3
14    3
15    2
16    3
17    3
18    2
19    3
20    3
21    3
22    3
23    3
Name: truth_int, dtype: int64
12     40
13     53
14     13
15     41
16     34
17    284
18     69
19     35
20     55
21     15
22     31
23     45
Name: duration, dtype: int64
3:  565 2:  150 1:  0 0:  0 -1:  0
total_duration =  715
max Id:  3
start =  24   end =  36
24    3
25   -1
26    2
27    0
28    2
29    1
30    3
31    2
32   -1
33    2
34    3
35    3
Name: truth_int, dtype: int64
24    75
25    25
26    57
27    75
28    34
29    40
30    23
31    80
32    24
33    49
34    29
35    39
Name: duration, dtype: int64
3:  166 2:  220 1:  40 0:  75 -1:  49
total_duration =  550
max Id:  2
start =  36   end =  48
36    2
37    3
38    3
39    3
40    2
41    3
42    3
43    3
44    2
45    2
46    0
47    2
Name: truth_int, dtype: int64
36     34
37     31
38     78
39     48
40     68
41     63
42     18
43     52
44     75
45     65
46     62
47    135
Name: duration, dtype: int64
3:  290 2:  377 1:  0 0:  62 -1:  0
total_duration =  729
max Id:  2
start =  48   end =  60
48    3
49    3
50    2
51    3
52    3
53    3
54    3
55    2
56    2
57    3
58    2
59    0
Name: truth_int, dtype: int64
48     27
49     80
50     26
51     70
52     66
53     73
54     28
55     79
56    174
57     10
58     67
59     60
Name: duration, dtype: int64
3:  354 2:  346 1:  0 0:  60 -1:  0
total_duration =  760
max Id:  3
start =  60   end =  72
60    2
61    3
62    3
63    3
64   -1
65    3
66    3
67    3
68    2
69   -1
70    3
71    1
Name: truth_int, dtype: int64
60     68
61     29
62    119
63     16
64     68
65     28
66     25
67     80
68    100
69    114
70     28
71     15
Name: duration, dtype: int64
3:  325 2:  168 1:  15 0:  0 -1:  182
total_duration =  690
max Id:  3
start =  72   end =  84
72    0
73    2
74    3
75    3
76    3
77    3
78    2
79    0
80    2
81    2
82    2
83    3
Name: truth_int, dtype: int64
72    232
73    172
74     38
75    121
76     23
77     35
78    127
79    154
80     57
81     59
82     45
83     59
Name: duration, dtype: int64
3:  276 2:  460 1:  0 0:  386 -1:  0
total_duration =  1122
max Id:  2
start =  84   end =  96
84    1
85    3
86   -1
87    3
88   -1
89    2
90    3
91    2
92    3
93    3
94    0
95    0
Name: truth_int, dtype: int64
84     39
85     61
86    113
87     29
88     47
89    107
90    123
91     45
92    187
93     57
94     48
95     38
Name: duration, dtype: int64
3:  457 2:  152 1:  39 0:  86 -1:  160
total_duration =  894
max Id:  3
start =  96   end =  108
96     0
97     3
98     3
99     2
100    3
101   -1
102    3
103    3
104    2
105    3
106    2
107    3
Name: truth_int, dtype: int64
96     130
97     211
98      79
99     390
100     52
101     44
102    231
103    105
104    167
105     59
106    200
107     62
Name: duration, dtype: int64

3:  799 2:  757 1:  0 0:  130 -1:  44
total_duration =  1730
max Id:  3
data len =  108
block_len 36
start =  0   end =  36
0     3
1     2
2     3
3     2
4     2
5     0
6     3
7     3
8     3
9     2
10    3
11    3
12    2
13    3
14    3
15    2
16    3
17    3
18    2
19    3
20    3
21    3
22    3
23    3
24    3
25   -1
26    2
27    0
28    2
29    1
30    3
31    2
32   -1
33    2
34    3
35    3
Name: truth_int, dtype: int64
0      41
1      42
2      13
3      32
4      41
5     115
6      18
7      41
8      28
9      40
10     29
11     24
12     40
13     53
14     13
15     41
16     34
17    284
18     69
19     35
20     55
21     15
22     31
23     45
24     75
25     25
26     57
27     75
28     34
29     40
30     23
31     80
32     24
33     49
34     29
35     39
Name: duration, dtype: int64
3:  925 2:  525 1:  40 0:  190 -1:  49
total_duration =  1729
max Id:  3
start =  36   end =  72
36    2
37    3
38    3
39    3
40    2
41    3
42    3
43    3
44    2
45    2
46    0
47    2
48    3
49    3
50    2
51    3
52    3
53    3
54    3
55    2
56    2
57    3
58    2
59    0
60    2
61    3
62    3
63    3
64   -1
65    3
66    3
67    3
68    2
69   -1
70    3
71    1
Name: truth_int, dtype: int64
36     34
37     31
38     78
39     48
40     68
41     63
42     18
43     52
44     75
45     65
46     62
47    135
48     27
49     80
50     26
51     70
52     66
53     73
54     28
55     79
56    174
57     10
58     67
59     60
60     68
61     29
62    119
63     16
64     68
65     28
66     25
67     80
68    100
69    114
70     28
71     15
Name: duration, dtype: int64
3:  969 2:  891 1:  15 0:  122 -1:  182
total_duration =  2179
max Id:  3
start =  72   end =  108
72     0
73     2
74     3
75     3
76     3
77     3
78     2
79     0
80     2
81     2
82     2
83     3
84     1
85     3
86    -1
87     3
88    -1
89     2
90     3
91     2
92     3
93     3
94     0
95     0
96     0
97     3
98     3
99     2
100    3
101   -1
102    3
103    3
104    2
105    3
106    2
107    3
Name: truth_int, dtype: int64
72     232
73     172
74      38
75     121
76      23
77      35
78     127
79     154
80      57
81      59
82      45
83      59
84      39
85      61
86     113
87      29
88      47
89     107
90     123
91      45
92     187
93      57
94      48
95      38
96     130
97     211
98      79
99     390
100     52
101     44
102    231
103    105
104    167
105     59
106    200
107     62
Name: duration, dtype: int64
3:  1532 2:  1369 1:  39 0:  602 -1:  204
total_duration =  3746
max Id:  3
data len =  108
block_len 108
start =  0   end =  108
0      3
1      2
2      3
3      2
4      2
5      0
6      3
7      3
8      3
9      2
10     3
11     3
12     2
13     3
14     3
15     2
16     3
17     3
18     2
19     3
20     3
21     3
22     3
23     3
24     3
25    -1
26     2
27     0
28     2
29     1
      ..
78     2
79     0
80     2
81     2
82     2
83     3
84     1
85     3
86    -1
87     3
88    -1
89     2
90     3
91     2
92     3
93     3
94     0
95     0
96     0
97     3
98     3
99     2
100    3
101   -1
102    3
103    3
104    2
105    3
106    2
107    3
Name: truth_int, Length: 108, dtype: int64
0       41
1       42
2       13
3       32
4       41
5      115
6       18
7       41
8       28
9       40
10      29
11      24
12      40
13      53
14      13
15      41
16      34
17     284
18      69
19      35
20      55
21      15
22      31
23      45
24      75
25      25
26      57
27      75
28      34
29      40
      ...
78     127
79     154
80      57
81      59
82      45
83      59
84      39
85      61
86     113
87      29
88      47
89     107
90     123
91      45
92     187
93      57
94      48
95      38
96     130
97     211
98      79
99     390
100     52
101     44
102    231
103    105
104    167
105     59
106    200
107     62
Name: duration, Length: 108, dtype: int64
3:  3426 2:  2785 1:  94 0:  914 -1:  435
total_duration =  7654
max Id:  3
12YearsaSlave_ice1.csv
12YearsaSlave_ice1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7654
Name: duration, dtype: int64
3:  7654 2:  0 1:  0 0:  0 -1:  0
total_duration =  7654
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  9   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  10   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  11   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  12   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  13   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  14   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  15   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  16   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  17   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  18   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  19   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  20   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  21   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  22   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  23   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  24   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  25   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1

data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7654
Name: duration, dtype: int64
3:  7654 2:  0 1:  0 0:  0 -1:  0
total_duration =  7654
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7654
Name: duration, dtype: int64
3:  7654 2:  0 1:  0 0:  0 -1:  0
total_duration =  7654
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7654
Name: duration, dtype: int64
3:  7654 2:  0 1:  0 0:  0 -1:  0
total_duration =  7654
max Id:  3
12YearsaSlave_ice2.csv
12YearsaSlave_ice2
failed for  12YearsaSlave_ice2
12YearsaSlave_ice4.csv
12YearsaSlave_ice4
failed for  12YearsaSlave_ice4
12YearsaSlave_ice8.csv
12YearsaSlave_ice8
failed for  12YearsaSlave_ice8
AmericanSniper.csv
AmericanSniper
data len =  112
block_len 5
start =  0   end =  5
0    3
1    1
2    1
3    3
4    1
Name: truth_int, dtype: int64
0    42
1    85
2    57
3    44
4    34
Name: duration, dtype: int64
3:  86 2:  0 1:  176 0:  0 -1:  0
total_duration =  262
max Id:  1
start =  5   end =  10
5    3
6    3
7    0
8    0
9    0
Name: truth_int, dtype: int64
5    80
6    62
7    20
8    54
9    48
Name: duration, dtype: int64
3:  142 2:  0 1:  0 0:  122 -1:  0
total_duration =  264
max Id:  3
start =  10   end =  15
10    0
11    3
12    2
13    3
14    3
Name: truth_int, dtype: int64
10     59
11     32
12    176
13    213
14     25
Name: duration, dtype: int64
3:  270 2:  176 1:  0 0:  59 -1:  0
total_duration =  505
max Id:  3
start =  15   end =  20
15    2
16    3
17    2
18   -1
19    2
Name: truth_int, dtype: int64
15    36
16    40
17    25
18    73
19    17
Name: duration, dtype: int64
3:  40 2:  78 1:  0 0:  0 -1:  73
total_duration =  191
max Id:  2
start =  20   end =  25
20   -1
21    2
22    3
23    3
24    2
Name: truth_int, dtype: int64
20    41
21    30
22    40
23     6
24    49
Name: duration, dtype: int64
3:  46 2:  79 1:  0 0:  0 -1:  41
total_duration =  166
max Id:  2
start =  25   end =  30
25    1
26    2
27    2
28    1
29    0
Name: truth_int, dtype: int64
25     85
26     47
27     40
28    118
29     68
Name: duration, dtype: int64
3:  0 2:  87 1:  203 0:  68 -1:  0
total_duration =  358
max Id:  1
start =  30   end =  35
30    2
31    3
32    3
33    1
34    1
Name: truth_int, dtype: int64
30    31
31    45
32    76
33    53
34    43
Name: duration, dtype: int64
3:  121 2:  31 1:  96 0:  0 -1:  0
total_duration =  248
max Id:  3
start =  35   end =  40
35    3
36    3
37   -1
38   -1
39    2
Name: truth_int, dtype: int64
35     19
36     42
37    147
38     70
39     43
Name: duration, dtype: int64
3:  61 2:  43 1:  0 0:  0 -1:  217
total_duration =  321
max Id:  -1
start =  40   end =  45
40    2
41    1
42    0
43    0
44    2
Name: truth_int, dtype: int64
40     84
41    104
42    106
43     55
44     34
Name: duration, dtype: int64
3:  0 2:  118 1:  104 0:  161 -1:  0
total_duration =  383
max Id:  0
start =  45   end =  50
45    0
46   -1
47    0
48    2
49    1
Name: truth_int, dtype: int64
45    13
46    23
47     6
48    28
49    80
Name: duration, dtype: int64
3:  0 2:  28 1:  80 0:  19 -1:  23
total_duration =  150
max Id:  1
start =  50   end =  55
50    1
51    1
52    2
53    3
54    3
Name: truth_int, dtype: int64
50    110
51     47
52     19
53     52
54     77
Name: duration, dtype: int64
3:  129 2:  19 1:  157 0:  0 -1:  0
total_duration =  305
max Id:  1
start =  55   end =  60
55    3
56    2
57    1
58    2
59    1
Name: truth_int, dtype: int64
55    57
56    55
57    50
58    27
59    64
Name: duration, dtype: int64
3:  57 2:  82 1:  114 0:  0 -1:  0
total_duration =  253
max Id:  1
start =  60   end =  65
60    1
61    1
62   -1
63    3
64    0
Name: truth_int, dtype: int64
60    101
61     55
62     81
63     65
64     37
Name: duration, dtype: int64
3:  65 2:  0 1:  156 0:  37 -1:  81
total_duration =  339
max Id:  1
start =  65   end =  70
65    0
66    0
67    1
68    0
69    0
Name: truth_int, dtype: int64
65    77
66    70
67    69
68    42
69    94
Name: duration, dtype: int64
3:  0 2:  0 1:  69 0:  283 -1:  0
total_duration =  352
max Id:  0
start =  70   end =  75
70    2
71    0
72    0
73    0
74    2
Name: truth_int, dtype: int64
70     39
71     78
72     39
73     59
74    156
Name: duration, dtype: int64
3:  0 2:  195 1:  0 0:  176 -1:  0
total_duration =  371
max Id:  2
start =  75   end =  80
75    2
76    3
77   -1
78    0
79    2
Name: truth_int, dtype: int64
75     60
76    110
77     77
78     95
79     87
Name: duration, dtype: int64
3:  110 2:  147 1:  0 0:  95 -1:  77
total_duration =  429
max Id:  2
start =  80   end =  85
80    3
81    2
82    2
83    1
84    1
Name: truth_int, dtype: int64
80     72
81     60
82    148
83     19
84     94
Name: duration, dtype: int64
3:  72 2:  208 1:  113 0:  0 -1:  0
total_duration =  393
max Id:  2
start =  85   end =  90
85    0
86    1
87    3
88    2
89    2
Name: truth_int, dtype: int64
85     52
86    118
87     97
88     56
89     54
Name: duration, dtype: int64
3:  97 2:  110 1:  118 0:  52 -1:  0
total_duration =  377
max Id:  1
start =  90   end =  95
90    1
91    0
92    0
93    0
94    2
Name: truth_int, dtype: int64
90     90
91     40
92    209
93     52
94    159
Name: duration, dtype: int64
3:  0 2:  159 1:  90 0:  301 -1:  0
total_duration =  550
max Id:  0
start =  95   end =  100
95    2
96    2
97    2
98   -1
99   -1
Name: truth_int, dtype: int64
95    229
96     62
97    178
98    129
99     40
Name: duration, dtype: int64
3:  0 2:  469 1:  0 0:  0 -1:  169
total_duration =  638
max Id:  2
start =  100   end =  105
100    1
101   -1
102    3
103    3
104    3
Name: truth_int, dtype: int64
100     74
101    106
102     36
103     73
104     38
Name: duration, dtype: int64
3:  147 2:  0 1:  74 0:  0 -1:  106
total_duration =  327
max Id:  3
start =  105   end =  110
105    3
106    3
107    3
108    3
109    0
Name: truth_int, dtype: int64
105     21
106     25
107     25
108    144
109     24
Name: duration, dtype: int64
3:  215 2:  0 1:  0 0:  24 -1:  0
total_duration =  239
max Id:  3
start =  110   end =  112
110    3
111    3
Name: truth_int, dtype: int64
110     11
111    172
Name: duration, dtype: int64
3:  183 2:  0 1:  0 0:  0 -1:  0
total_duration =  183
max Id:  3
start =  115   end =  112
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  120   end =  112
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)

3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  125   end =  112
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  130   end =  112
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  112
block_len 13
start =  0   end =  13
0     3
1     1
2     1
3     3
4     1
5     3
6     3
7     0
8     0
9     0
10    0
11    3
12    2
Name: truth_int, dtype: int64
0      42
1      85
2      57
3      44
4      34
5      80
6      62
7      20
8      54
9      48
10     59
11     32
12    176
Name: duration, dtype: int64
3:  260 2:  176 1:  176 0:  181 -1:  0
total_duration =  793
max Id:  3
start =  13   end =  26
13    3
14    3
15    2
16    3
17    2
18   -1
19    2
20   -1
21    2
22    3
23    3
24    2
25    1
Name: truth_int, dtype: int64
13    213
14     25
15     36
16     40
17     25
18     73
19     17
20     41
21     30
22     40
23      6
24     49
25     85
Name: duration, dtype: int64
3:  324 2:  157 1:  85 0:  0 -1:  114
total_duration =  680
max Id:  3
start =  26   end =  39
26    2
27    2
28    1
29    0
30    2
31    3
32    3
33    1
34    1
35    3
36    3
37   -1
38   -1
Name: truth_int, dtype: int64
26     47
27     40
28    118
29     68
30     31
31     45
32     76
33     53
34     43
35     19
36     42
37    147
38     70
Name: duration, dtype: int64
3:  182 2:  118 1:  214 0:  68 -1:  217
total_duration =  799
max Id:  -1
start =  39   end =  52
39    2
40    2
41    1
42    0
43    0
44    2
45    0
46   -1
47    0
48    2
49    1
50    1
51    1
Name: truth_int, dtype: int64
39     43
40     84
41    104
42    106
43     55
44     34
45     13
46     23
47      6
48     28
49     80
50    110
51     47
Name: duration, dtype: int64
3:  0 2:  189 1:  341 0:  180 -1:  23
total_duration =  733
max Id:  1
start =  52   end =  65
52    2
53    3
54    3
55    3
56    2
57    1
58    2
59    1
60    1
61    1
62   -1
63    3
64    0
Name: truth_int, dtype: int64
52     19
53     52
54     77
55     57
56     55
57     50
58     27
59     64
60    101
61     55
62     81
63     65
64     37
Name: duration, dtype: int64
3:  251 2:  101 1:  270 0:  37 -1:  81
total_duration =  740
max Id:  1
start =  65   end =  78
65    0
66    0
67    1
68    0
69    0
70    2
71    0
72    0
73    0
74    2
75    2
76    3
77   -1
Name: truth_int, dtype: int64
65     77
66     70
67     69
68     42
69     94
70     39
71     78
72     39
73     59
74    156
75     60
76    110
77     77
Name: duration, dtype: int64
3:  110 2:  255 1:  69 0:  459 -1:  77
total_duration =  970
max Id:  0
start =  78   end =  91
78    0
79    2
80    3
81    2
82    2
83    1
84    1
85    0
86    1
87    3
88    2
89    2
90    1
Name: truth_int, dtype: int64
78     95
79     87
80     72
81     60
82    148
83     19
84     94
85     52
86    118
87     97
88     56
89     54
90     90
Name: duration, dtype: int64
3:  169 2:  405 1:  321 0:  147 -1:  0
total_duration =  1042
max Id:  2
start =  91   end =  104
91     0
92     0
93     0
94     2
95     2
96     2
97     2
98    -1
99    -1
100    1
101   -1
102    3
103    3
Name: truth_int, dtype: int64
91      40
92     209
93      52
94     159
95     229
96      62
97     178
98     129
99      40
100     74
101    106
102     36
103     73
Name: duration, dtype: int64
3:  109 2:  628 1:  74 0:  301 -1:  275
total_duration =  1387
max Id:  2
start =  104   end =  112
104    3
105    3
106    3
107    3
108    3
109    0
110    3
111    3
Name: truth_int, dtype: int64
104     38
105     21
106     25
107     25
108    144
109     24
110     11
111    172
Name: duration, dtype: int64
3:  436 2:  0 1:  0 0:  24 -1:  0
total_duration =  460
max Id:  3
data len =  112
block_len 38
start =  0   end =  38
0     3
1     1
2     1
3     3
4     1
5     3
6     3
7     0
8     0
9     0
10    0
11    3
12    2
13    3
14    3
15    2
16    3
17    2
18   -1
19    2
20   -1
21    2
22    3
23    3
24    2
25    1
26    2
27    2
28    1
29    0
30    2
31    3
32    3
33    1
34    1
35    3
36    3
37   -1
Name: truth_int, dtype: int64
0      42
1      85
2      57
3      44
4      34
5      80
6      62
7      20
8      54
9      48
10     59
11     32
12    176
13    213
14     25
15     36
16     40
17     25
18     73
19     17
20     41
21     30
22     40
23      6
24     49
25     85
26     47
27     40
28    118
29     68
30     31
31     45
32     76
33     53
34     43
35     19
36     42
37    147
Name: duration, dtype: int64
3:  766 2:  451 1:  475 0:  249 -1:  261
total_duration =  2202
max Id:  3
start =  38   end =  76
38   -1
39    2
40    2
41    1
42    0
43    0
44    2
45    0
46   -1
47    0
48    2
49    1
50    1
51    1
52    2
53    3
54    3
55    3
56    2
57    1
58    2
59    1
60    1
61    1
62   -1
63    3
64    0
65    0
66    0
67    1
68    0
69    0
70    2
71    0
72    0
73    0
74    2
75    2
Name: truth_int, dtype: int64
38     70
39     43
40     84
41    104
42    106
43     55
44     34
45     13
46     23
47      6
48     28
49     80
50    110
51     47
52     19
53     52
54     77
55     57
56     55
57     50
58     27
59     64
60    101
61     55
62     81
63     65
64     37
65     77
66     70
67     69
68     42
69     94
70     39
71     78
72     39
73     59
74    156
75     60
Name: duration, dtype: int64
3:  251 2:  545 1:  680 0:  676 -1:  174
total_duration =  2326
max Id:  1
start =  76   end =  112
76     3
77    -1
78     0
79     2
80     3
81     2
82     2
83     1
84     1
85     0
86     1
87     3
88     2
89     2
90     1
91     0
92     0
93     0
94     2
95     2
96     2
97     2
98    -1
99    -1
100    1
101   -1
102    3
103    3
104    3
105    3
106    3
107    3
108    3
109    0
110    3
111    3
Name: truth_int, dtype: int64
76     110
77      77
78      95
79      87
80      72
81      60
82     148
83      19
84      94
85      52
86     118
87      97
88      56
89      54
90      90
91      40
92     209
93      52
94     159
95     229
96      62
97     178
98     129
99      40
100     74
101    106
102     36
103     73
104     38
105     21
106     25
107     25
108    144
109     24
110     11
111    172
Name: duration, dtype: int64
3:  824 2:  1033 1:  395 0:  472 -1:  352
total_duration =  3076
max Id:  2
data len =  112
block_len 112
start =  0   end =  112
0      3
1      1
2      1
3      3
4      1
5      3
6      3
7      0
8      0
9      0
10     0
11     3
12     2
13     3
14     3
15     2
16     3
17     2
18    -1
19     2
20    -1
21     2
22     3
23     3
24     2
25     1
26     2
27     2
28     1
29     0
      ..
82     2
83     1
84     1
85     0
86     1
87     3
88     2
89     2
90     1
91     0
92     0
93     0
94     2
95     2
96     2
97     2
98    -1
99    -1
100    1
101   -1
102    3
103    3
104    3
105    3
106    3
107    3
108    3
109    0
110    3
111    3
Name: truth_int, Length: 112, dtype: int64
0       42
1       85
2       57
3       44
4       34
5       80
6       62
7       20
8       54
9       48
10      59
11      32
12     176
13     213
14      25
15      36
16      40
17      25
18      73
19      17
20      41
21      30
22      40
23       6
24      49
25      85
26      47
27      40
28     118
29      68
      ...
82     148
83      19
84      94
85      52
86     118
87      97
88      56
89      54
90      90
91      40
92     209
93      52
94     159
95     229
96      62
97     178
98     129
99      40
100     74
101    106
102     36
103     73
104     38
105     21
106     25
107     25
108    144
109     24
110     11
111    172
Name: duration, Length: 112, dtype: int64
3:  1841 2:  2029 1:  1550 0:  1397 -1:  787
total_duration =  7604
max Id:  2
AmericanSniper_ice1.csv
AmericanSniper_ice1
data len =  1
block_len 1
start =  0   end =  1
0    2
Name: truth_int, dtype: int64
0    7604
Name: duration, dtype: int64
3:  0 2:  7604 1:  0 0:  0 -1:  0
total_duration =  7604
max Id:  2
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  9   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  10   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  11   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  12   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  13   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  14   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)

3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  15   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  16   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  17   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  18   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  19   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  20   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  21   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  22   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  23   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  24   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  25   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    2
Name: truth_int, dtype: int64
0    7604
Name: duration, dtype: int64
3:  0 2:  7604 1:  0 0:  0 -1:  0
total_duration =  7604
max Id:  2
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    2
Name: truth_int, dtype: int64
0    7604
Name: duration, dtype: int64
3:  0 2:  7604 1:  0 0:  0 -1:  0
total_duration =  7604
max Id:  2
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    2
Name: truth_int, dtype: int64
0    7604
Name: duration, dtype: int64
3:  0 2:  7604 1:  0 0:  0 -1:  0
total_duration =  7604
max Id:  2
AmericanSniper_ice2.csv
AmericanSniper_ice2
failed for  AmericanSniper_ice2
AmericanSniper_ice4.csv
AmericanSniper_ice4
failed for  AmericanSniper_ice4
AmericanSniper_ice8.csv
AmericanSniper_ice8
failed for  AmericanSniper_ice8
BohemianRhapsody.csv
BohemianRhapsody
data len =  179
block_len 7
start =  0   end =  7
0   -1
1    3
2    3
3    3
4    3
5    3
6   -1
Name: truth_int, dtype: int64
0    29
1    19
2    21
3    57
4    57
5    13
6    13
Name: duration, dtype: int64
3:  167 2:  0 1:  0 0:  0 -1:  42
total_duration =  209
max Id:  3
start =  7   end =  14
7     3
8     3
9     3
10    3
11    3
12    3
13    1
Name: truth_int, dtype: int64
7     13
8     24
9      7
10    17
11    78
12    25
13    49
Name: duration, dtype: int64
3:  164 2:  0 1:  49 0:  0 -1:  0
total_duration =  213
max Id:  3
start =  14   end =  21
14    3
15    0
16    1
17    3
18    3
19    3
20    3
Name: truth_int, dtype: int64
14    12
15    27
16    55
17     7
18    12
19    39
20    60
Name: duration, dtype: int64
3:  130 2:  0 1:  55 0:  27 -1:  0
total_duration =  212
max Id:  3
start =  21   end =  28
21    2
22   -1
23    3
24    2
25    3
26    3
27    2
Name: truth_int, dtype: int64
21    29
22     6
23    42
24    21
25    33
26    17
27    24
Name: duration, dtype: int64
3:  92 2:  74 1:  0 0:  0 -1:  6
total_duration =  172
max Id:  3
start =  28   end =  35
28   -1
29    1
30    3
31    2
32    3
33    3
34    3
Name: truth_int, dtype: int64
28    17
29    10
30    79
31    12
32     8
33    15
34    39
Name: duration, dtype: int64
3:  141 2:  12 1:  10 0:  0 -1:  17
total_duration =  180
max Id:  3
start =  35   end =  42
35    3
36    2
37   -1
38   -1
39    1
40    3
41    3
Name: truth_int, dtype: int64
35    32
36    15
37    17
38    19
39    22
40    17
41    17
Name: duration, dtype: int64
3:  66 2:  15 1:  22 0:  0 -1:  36
total_duration =  139
max Id:  3
start =  42   end =  49
42    2
43    3
44    2
45    2
46    2
47    0
48    2
Name: truth_int, dtype: int64
42    18
43    34
44    43
45    22
46    46
47    10
48     6
Name: duration, dtype: int64
3:  34 2:  135 1:  0 0:  10 -1:  0
total_duration =  179
max Id:  2
start =  49   end =  56
49    1
50    3
51    2
52    2
53    3
54    2
55    0
Name: truth_int, dtype: int64
49    24
50    41
51    30
52    13
53    43
54    93
55    18
Name: duration, dtype: int64
3:  84 2:  136 1:  24 0:  18 -1:  0
total_duration =  262
max Id:  2
start =  56   end =  63
56    3
57    3
58    1
59    3
60    3
61    2
62    3
Name: truth_int, dtype: int64
56     35
57    149
58     27
59     26
60    103
61    109
62     41
Name: duration, dtype: int64
3:  354 2:  109 1:  27 0:  0 -1:  0
total_duration =  490
max Id:  3
start =  63   end =  70
63    0
64    2
65    1
66    3
67    3
68    3
69    3
Name: truth_int, dtype: int64
63     55
64     19
65     70
66     70
67     77
68     90
69    105
Name: duration, dtype: int64
3:  342 2:  19 1:  70 0:  55 -1:  0
total_duration =  486
max Id:  3
start =  70   end =  77
70    2
71    1
72    2
73    3
74    2
75    3
76    3
Name: truth_int, dtype: int64
70    137
71     85
72     47
73     55
74      9
75     15
76     86
Name: duration, dtype: int64
3:  156 2:  193 1:  85 0:  0 -1:  0
total_duration =  434
max Id:  2
start =  77   end =  84
77    3
78    3
79    3
80    2
81    3
82    3
83    3
Name: truth_int, dtype: int64
77     41
78     31
79     14
80     29
81     83
82     67
83    134
Name: duration, dtype: int64
3:  370 2:  29 1:  0 0:  0 -1:  0
total_duration =  399
max Id:  3
start =  84   end =  91
84    3
85    3
86    2
87    3
88    2
89    2
90    2
Name: truth_int, dtype: int64
84     64
85    114
86     28
87     22
88     65
89     38
90      8
Name: duration, dtype: int64
3:  200 2:  139 1:  0 0:  0 -1:  0
total_duration =  339
max Id:  3
start =  91   end =  98
91    3
92    0
93    0
94    1
95    3
96    2
97    3
Name: truth_int, dtype: int64
91    31
92    34
93    35
94    90
95    71
96     7
97    49
Name: duration, dtype: int64
3:  151 2:  7 1:  90 0:  69 -1:  0
total_duration =  317
max Id:  3
start =  98   end =  105
98     3
99     3
100    2
101    3
102    0
103   -1
104    0
Name: truth_int, dtype: int64
98     111
99      19
100     13
101     18
102     11
103     88
104     40
Name: duration, dtype: int64
3:  148 2:  13 1:  0 0:  51 -1:  88
total_duration =  300
max Id:  3
start =  105   end =  112
105    0
106    0
107    2
108    2
109    1
110    3
111    2
Name: truth_int, dtype: int64
105    75
106    60
107    17
108    12
109     3
110    14
111    34
Name: duration, dtype: int64
3:  14 2:  63 1:  3 0:  135 -1:  0
total_duration =  215
max Id:  0
start =  112   end =  119
112    3
113    2
114    3
115    2
116    3
117    2
118    2
Name: truth_int, dtype: int64
112     6
113     9
114     4
115    50
116    12
117    70
118     4
Name: duration, dtype: int64
3:  22 2:  133 1:  0 0:  0 -1:  0
total_duration =  155
max Id:  2
start =  119   end =  126
119    2
120    2
121    3
122    3
123    0
124    0
125    3
Name: truth_int, dtype: int64
119    98
120    61
121    25
122    42
123     8
124    22
125    50
Name: duration, dtype: int64
3:  117 2:  159 1:  0 0:  30 -1:  0
total_duration =  306
max Id:  2
start =  126   end =  133
126    1
127   -1
128    3
129    2
130    2
131    2
132    0
Name: truth_int, dtype: int64
126    167
127     32
128     25
129     35
130     11
131     75
132     46
Name: duration, dtype: int64
3:  25 2:  121 1:  167 0:  46 -1:  32
total_duration =  391
max Id:  1
start =  133   end =  140
133   -1
134   -1
135   -1
136    2
137    0
138    3
139    0
Name: truth_int, dtype: int64
133     33
134     60
135     90
136    143
137      9
138     26
139     66
Name: duration, dtype: int64
3:  26 2:  143 1:  0 0:  75 -1:  183
total_duration =  427
max Id:  -1
start =  140   end =  147
140    1
141    0
142    0
143    0
144    2
145    2
146    2
Name: truth_int, dtype: int64
140     22
141     25
142    118
143     25
144     22
145     30
146      6
Name: duration, dtype: int64
3:  0 2:  58 1:  22 0:  168 -1:  0
total_duration =  248
max Id:  0

start =  147   end =  154
147    3
148    0
149    3
150    3
151    2
152    2
153   -1
Name: truth_int, dtype: int64
147    62
148    26
149    40
150    30
151     3
152    44
153    43
Name: duration, dtype: int64
3:  132 2:  47 1:  0 0:  26 -1:  43
total_duration =  248
max Id:  3
start =  154   end =  161
154    2
155    3
156    0
157    3
158    2
159    3
160    0
Name: truth_int, dtype: int64
154     36
155     14
156      8
157    127
158     24
159     28
160     45
Name: duration, dtype: int64
3:  169 2:  60 1:  0 0:  53 -1:  0
total_duration =  282
max Id:  3
start =  161   end =  168
161   -1
162   -1
163   -1
164    2
165    3
166    3
167    3
Name: truth_int, dtype: int64
161    116
162     50
163     20
164     29
165     27
166      9
167    107
Name: duration, dtype: int64
3:  143 2:  29 1:  0 0:  0 -1:  186
total_duration =  358
max Id:  -1
start =  168   end =  175
168    2
169    2
170    3
171    3
172    2
173    3
174    3
Name: truth_int, dtype: int64
168      4
169     28
170    200
171     48
172    166
173    259
174      7
Name: duration, dtype: int64
3:  514 2:  198 1:  0 0:  0 -1:  0
total_duration =  712
max Id:  3
start =  175   end =  179
175    3
176    3
177    3
178    3
Name: truth_int, dtype: int64
175     8
176     7
177     7
178    12
Name: duration, dtype: int64
3:  34 2:  0 1:  0 0:  0 -1:  0
total_duration =  34
max Id:  3
start =  182   end =  179
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  179
block_len 20
start =  0   end =  20
0    -1
1     3
2     3
3     3
4     3
5     3
6    -1
7     3
8     3
9     3
10    3
11    3
12    3
13    1
14    3
15    0
16    1
17    3
18    3
19    3
Name: truth_int, dtype: int64
0     29
1     19
2     21
3     57
4     57
5     13
6     13
7     13
8     24
9      7
10    17
11    78
12    25
13    49
14    12
15    27
16    55
17     7
18    12
19    39
Name: duration, dtype: int64
3:  401 2:  0 1:  104 0:  27 -1:  42
total_duration =  574
max Id:  3
start =  20   end =  40
20    3
21    2
22   -1
23    3
24    2
25    3
26    3
27    2
28   -1
29    1
30    3
31    2
32    3
33    3
34    3
35    3
36    2
37   -1
38   -1
39    1
Name: truth_int, dtype: int64
20    60
21    29
22     6
23    42
24    21
25    33
26    17
27    24
28    17
29    10
30    79
31    12
32     8
33    15
34    39
35    32
36    15
37    17
38    19
39    22
Name: duration, dtype: int64
3:  325 2:  101 1:  32 0:  0 -1:  59
total_duration =  517
max Id:  3
start =  40   end =  60
40    3
41    3
42    2
43    3
44    2
45    2
46    2
47    0
48    2
49    1
50    3
51    2
52    2
53    3
54    2
55    0
56    3
57    3
58    1
59    3
Name: truth_int, dtype: int64
40     17
41     17
42     18
43     34
44     43
45     22
46     46
47     10
48      6
49     24
50     41
51     30
52     13
53     43
54     93
55     18
56     35
57    149
58     27
59     26
Name: duration, dtype: int64
3:  362 2:  271 1:  51 0:  28 -1:  0
total_duration =  712
max Id:  3
start =  60   end =  80
60    3
61    2
62    3
63    0
64    2
65    1
66    3
67    3
68    3
69    3
70    2
71    1
72    2
73    3
74    2
75    3
76    3
77    3
78    3
79    3
Name: truth_int, dtype: int64
60    103
61    109
62     41
63     55
64     19
65     70
66     70
67     77
68     90
69    105
70    137
71     85
72     47
73     55
74      9
75     15
76     86
77     41
78     31
79     14
Name: duration, dtype: int64
3:  728 2:  321 1:  155 0:  55 -1:  0
total_duration =  1259
max Id:  3
start =  80   end =  100
80    2
81    3
82    3
83    3
84    3
85    3
86    2
87    3
88    2
89    2
90    2
91    3
92    0
93    0
94    1
95    3
96    2
97    3
98    3
99    3
Name: truth_int, dtype: int64
80     29
81     83
82     67
83    134
84     64
85    114
86     28
87     22
88     65
89     38
90      8
91     31
92     34
93     35
94     90
95     71
96      7
97     49
98    111
99     19
Name: duration, dtype: int64
3:  765 2:  175 1:  90 0:  69 -1:  0
total_duration =  1099
max Id:  3
start =  100   end =  120
100    2
101    3
102    0
103   -1
104    0
105    0
106    0
107    2
108    2
109    1
110    3
111    2
112    3
113    2
114    3
115    2
116    3
117    2
118    2
119    2
Name: truth_int, dtype: int64
100    13
101    18
102    11
103    88
104    40
105    75
106    60
107    17
108    12
109     3
110    14
111    34
112     6
113     9
114     4
115    50
116    12
117    70
118     4
119    98
Name: duration, dtype: int64
3:  54 2:  307 1:  3 0:  186 -1:  88
total_duration =  638
max Id:  2
start =  120   end =  140
120    2
121    3
122    3
123    0
124    0
125    3
126    1
127   -1
128    3
129    2
130    2
131    2
132    0
133   -1
134   -1
135   -1
136    2
137    0
138    3
139    0
Name: truth_int, dtype: int64
120     61
121     25
122     42
123      8
124     22
125     50
126    167
127     32
128     25
129     35
130     11
131     75
132     46
133     33
134     60
135     90
136    143
137      9
138     26
139     66
Name: duration, dtype: int64
3:  168 2:  325 1:  167 0:  151 -1:  215
total_duration =  1026
max Id:  2
start =  140   end =  160
140    1
141    0
142    0
143    0
144    2
145    2
146    2
147    3
148    0
149    3
150    3
151    2
152    2
153   -1
154    2
155    3
156    0
157    3
158    2
159    3
Name: truth_int, dtype: int64
140     22
141     25
142    118
143     25
144     22
145     30
146      6
147     62
148     26
149     40
150     30
151      3
152     44
153     43
154     36
155     14
156      8
157    127
158     24
159     28
Name: duration, dtype: int64
3:  301 2:  165 1:  22 0:  202 -1:  43
total_duration =  733
max Id:  3
start =  160   end =  179
160    0
161   -1
162   -1
163   -1
164    2
165    3
166    3
167    3
168    2
169    2
170    3
171    3
172    2
173    3
174    3
175    3
176    3
177    3
178    3
Name: truth_int, dtype: int64
160     45
161    116
162     50
163     20
164     29
165     27
166      9
167    107
168      4
169     28
170    200
171     48
172    166
173    259
174      7
175      8
176      7
177      7
178     12
Name: duration, dtype: int64
3:  691 2:  227 1:  0 0:  45 -1:  186
total_duration =  1149
max Id:  3
data len =  179
block_len 60
start =  0   end =  60
0    -1
1     3
2     3
3     3
4     3
5     3
6    -1
7     3
8     3
9     3
10    3
11    3
12    3
13    1
14    3
15    0
16    1
17    3
18    3
19    3
20    3
21    2
22   -1
23    3
24    2
25    3
26    3
27    2
28   -1
29    1
30    3
31    2
32    3
33    3
34    3
35    3
36    2
37   -1
38   -1
39    1
40    3
41    3
42    2
43    3
44    2
45    2
46    2
47    0
48    2
49    1
50    3
51    2
52    2
53    3
54    2
55    0
56    3
57    3
58    1
59    3
Name: truth_int, dtype: int64
0      29
1      19
2      21
3      57
4      57
5      13
6      13
7      13
8      24
9       7
10     17
11     78
12     25
13     49
14     12
15     27
16     55
17      7
18     12
19     39
20     60
21     29
22      6
23     42
24     21
25     33
26     17
27     24
28     17
29     10
30     79
31     12
32      8
33     15
34     39
35     32
36     15
37     17
38     19
39     22
40     17
41     17
42     18
43     34
44     43
45     22
46     46
47     10
48      6
49     24
50     41
51     30
52     13
53     43
54     93
55     18
56     35
57    149
58     27
59     26
Name: duration, dtype: int64
3:  1088 2:  372 1:  187 0:  55 -1:  101
total_duration =  1803
max Id:  3
start =  60   end =  120
60     3
61     2
62     3
63     0
64     2
65     1
66     3
67     3
68     3
69     3
70     2
71     1
72     2
73     3
74     2
75     3
76     3
77     3
78     3
79     3
80     2
81     3
82     3
83     3
84     3
85     3
86     2
87     3
88     2
89     2
90     2
91     3
92     0
93     0
94     1
95     3
96     2
97     3
98     3
99     3
100    2
101    3
102    0
103   -1
104    0
105    0
106    0
107    2
108    2
109    1
110    3
111    2
112    3
113    2
114    3
115    2
116    3
117    2
118    2
119    2
Name: truth_int, dtype: int64
60     103
61     109
62      41
63      55
64      19
65      70
66      70
67      77
68      90
69     105
70     137
71      85
72      47
73      55
74       9
75      15
76      86
77      41
78      31
79      14
80      29
81      83
82      67
83     134
84      64
85     114
86      28
87      22
88      65
89      38
90       8
91      31
92      34
93      35
94      90
95      71
96       7
97      49
98     111
99      19
100     13
101     18
102     11
103     88
104     40
105     75
106     60
107     17
108     12
109      3
110     14
111     34
112      6
113      9
114      4
115     50
116     12
117     70
118      4
119     98
Name: duration, dtype: int64
3:  1547 2:  803 1:  248 0:  310 -1:  88
total_duration =  2996
max Id:  3
start =  120   end =  179
120    2
121    3
122    3
123    0
124    0
125    3
126    1
127   -1
128    3
129    2
130    2
131    2
132    0
133   -1
134   -1
135   -1
136    2
137    0
138    3
139    0
140    1
141    0
142    0
143    0
144    2
145    2
146    2
147    3
148    0
149    3
150    3
151    2
152    2
153   -1
154    2
155    3
156    0
157    3
158    2
159    3
160    0
161   -1
162   -1
163   -1
164    2
165    3
166    3
167    3
168    2
169    2
170    3
171    3
172    2
173    3
174    3
175    3
176    3
177    3
178    3
Name: truth_int, dtype: int64
120     61
121     25
122     42
123      8
124     22
125     50
126    167
127     32
128     25
129     35
130     11
131     75
132     46
133     33
134     60
135     90
136    143
137      9
138     26
139     66
140     22
141     25
142    118
143     25
144     22
145     30
146      6
147     62
148     26
149     40
150     30
151      3
152     44
153     43
154     36
155     14
156      8
157    127
158     24
159     28
160     45
161    116
162     50
163     20
164     29
165     27
166      9
167    107
168      4
169     28
170    200
171     48
172    166
173    259
174      7
175      8
176      7
177      7
178     12
Name: duration, dtype: int64
3:  1160 2:  717 1:  189 0:  398 -1:  444
total_duration =  2908
max Id:  3
data len =  179
block_len 179
start =  0   end =  179
0     -1
1      3
2      3
3      3
4      3
5      3
6     -1
7      3
8      3
9      3
10     3
11     3
12     3
13     1
14     3
15     0
16     1
17     3
18     3
19     3
20     3
21     2
22    -1
23     3
24     2
25     3
26     3
27     2
28    -1
29     1
      ..
149    3
150    3
151    2
152    2
153   -1
154    2
155    3
156    0
157    3
158    2
159    3
160    0
161   -1
162   -1
163   -1
164    2
165    3
166    3
167    3
168    2
169    2
170    3
171    3
172    2
173    3
174    3
175    3
176    3
177    3
178    3
Name: truth_int, Length: 179, dtype: int64
0       29
1       19
2       21
3       57
4       57
5       13
6       13
7       13
8       24
9        7
10      17
11      78
12      25
13      49
14      12
15      27
16      55
17       7
18      12
19      39
20      60
21      29
22       6
23      42
24      21
25      33
26      17
27      24
28      17
29      10
      ...
149     40
150     30
151      3
152     44
153     43
154     36
155     14
156      8
157    127
158     24
159     28
160     45
161    116
162     50
163     20
164     29
165     27
166      9
167    107
168      4
169     28
170    200
171     48
172    166
173    259
174      7
175      8
176      7
177      7
178     12
Name: duration, Length: 179, dtype: int64
3:  3795 2:  1892 1:  624 0:  763 -1:  633
total_duration =  7707
max Id:  3
BohemianRhapsody_ice1.csv
BohemianRhapsody_ice1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7707
Name: duration, dtype: int64
3:  7707 2:  0 1:  0 0:  0 -1:  0
total_duration =  7707
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)

3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  9   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  10   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  11   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  12   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  13   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  14   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  15   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  16   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  17   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  18   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  19   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  20   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  21   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  22   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  23   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  24   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  25   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7707
Name: duration, dtype: int64
3:  7707 2:  0 1:  0 0:  0 -1:  0
total_duration =  7707
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7707
Name: duration, dtype: int64
3:  7707 2:  0 1:  0 0:  0 -1:  0
total_duration =  7707
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7707
Name: duration, dtype: int64
3:  7707 2:  0 1:  0 0:  0 -1:  0
total_duration =  7707
max Id:  3
BohemianRhapsody_ice2.csv
BohemianRhapsody_ice2
failed for  BohemianRhapsody_ice2
BohemianRhapsody_ice4.csv
BohemianRhapsody_ice4
failed for  BohemianRhapsody_ice4
BohemianRhapsody_ice8.csv
BohemianRhapsody_ice8
failed for  BohemianRhapsody_ice8
BridgeofSpies.csv
BridgeofSpies
data len =  92
block_len 4
start =  0   end =  4
0    3
1    3
2    2
3    2
Name: truth_int, dtype: int64
0     21
1     75
2    152
3     14
Name: duration, dtype: int64
3:  96 2:  166 1:  0 0:  0 -1:  0
total_duration =  262
max Id:  2
start =  4   end =  8
4    2
5    2
6    2
7    3
Name: truth_int, dtype: int64
4     36
5    127
6    131
7    132
Name: duration, dtype: int64
3:  132 2:  294 1:  0 0:  0 -1:  0
total_duration =  426
max Id:  2
start =  8   end =  12
8     3
9     3
10    2
11    3
Name: truth_int, dtype: int64
8      30
9     115
10     34
11    125
Name: duration, dtype: int64
3:  270 2:  34 1:  0 0:  0 -1:  0
total_duration =  304
max Id:  3
start =  12   end =  16
12    3
13    2
14    2
15    3
Name: truth_int, dtype: int64
12    265
13     44
14    151
15     84
Name: duration, dtype: int64
3:  349 2:  195 1:  0 0:  0 -1:  0
total_duration =  544
max Id:  3
start =  16   end =  20
16   -1
17   -1
18    3
19    2
Name: truth_int, dtype: int64
16    113
17    154
18     86
19     56
Name: duration, dtype: int64
3:  86 2:  56 1:  0 0:  0 -1:  267
total_duration =  409
max Id:  -1
start =  20   end =  24
20    3
21    3
22    3
23    1
Name: truth_int, dtype: int64
20    68
21    43
22    51
23    84
Name: duration, dtype: int64
3:  162 2:  0 1:  84 0:  0 -1:  0
total_duration =  246
max Id:  3
start =  24   end =  28
24   -1
25    3
26    3
27    2
Name: truth_int, dtype: int64
24     32
25     39
26    223
27    170
Name: duration, dtype: int64
3:  262 2:  170 1:  0 0:  0 -1:  32
total_duration =  464
max Id:  3
start =  28   end =  32
28    3
29    3
30   -1
31    3
Name: truth_int, dtype: int64
28     98
29     45
30     45
31    100
Name: duration, dtype: int64
3:  243 2:  0 1:  0 0:  0 -1:  45
total_duration =  288
max Id:  3
start =  32   end =  36
32    0
33   -1
34    3
35    3
Name: truth_int, dtype: int64
32    54
33    85
34    97
35    12
Name: duration, dtype: int64
3:  109 2:  0 1:  0 0:  54 -1:  85
total_duration =  248
max Id:  3
start =  36   end =  40
36    3
37    3
38    3
39    3
Name: truth_int, dtype: int64
36    27
37    29
38    12
39    20
Name: duration, dtype: int64
3:  88 2:  0 1:  0 0:  0 -1:  0
total_duration =  88
max Id:  3
start =  40   end =  44
40    3
41    3
42    3
43    3
Name: truth_int, dtype: int64
40     21
41     49
42    165
43     36
Name: duration, dtype: int64
3:  271 2:  0 1:  0 0:  0 -1:  0
total_duration =  271
max Id:  3
start =  44   end =  48
44    3
45    3
46    3
47    3
Name: truth_int, dtype: int64
44    15
45    61
46    49
47    52
Name: duration, dtype: int64
3:  177 2:  0 1:  0 0:  0 -1:  0
total_duration =  177
max Id:  3
start =  48   end =  52
48    3
49    1
50    0
51    2
Name: truth_int, dtype: int64
48    237
49    107
50     31
51    105
Name: duration, dtype: int64
3:  237 2:  105 1:  107 0:  31 -1:  0
total_duration =  480
max Id:  3
start =  52   end =  56
52    2
53    3
54    3
55    0
Name: truth_int, dtype: int64
52     43
53    144
54    118
55     26
Name: duration, dtype: int64
3:  262 2:  43 1:  0 0:  26 -1:  0
total_duration =  331
max Id:  3
start =  56   end =  60
56    3
57    1
58    3
59    3
Name: truth_int, dtype: int64
56    126
57    127
58    130
59    355
Name: duration, dtype: int64
3:  611 2:  0 1:  127 0:  0 -1:  0
total_duration =  738
max Id:  3
start =  60   end =  64
60    3
61    3
62    3
63    3
Name: truth_int, dtype: int64
60    173
61    112
62    153
63     39
Name: duration, dtype: int64
3:  477 2:  0 1:  0 0:  0 -1:  0
total_duration =  477
max Id:  3
start =  64   end =  68
64    3
65    3
66    3
67    2
Name: truth_int, dtype: int64
64    121
65     42
66    155
67     74
Name: duration, dtype: int64
3:  318 2:  74 1:  0 0:  0 -1:  0
total_duration =  392
max Id:  3
start =  68   end =  72
68    0
69    1
70    0
71   -1
Name: truth_int, dtype: int64
68     55
69     67
70    160
71    107
Name: duration, dtype: int64
3:  0 2:  0 1:  67 0:  215 -1:  107
total_duration =  389
max Id:  0
start =  72   end =  76
72   -1
73    3
74   -1
75    2
Name: truth_int, dtype: int64
72    203
73     57
74     32
75     90
Name: duration, dtype: int64
3:  57 2:  90 1:  0 0:  0 -1:  235
total_duration =  382
max Id:  -1
start =  76   end =  80
76    3
77    3
78    3
79    3
Name: truth_int, dtype: int64
76     99
77     30
78    159
79    151
Name: duration, dtype: int64
3:  439 2:  0 1:  0 0:  0 -1:  0
total_duration =  439
max Id:  3
start =  80   end =  84
80    3
81    2
82    2
83    2
Name: truth_int, dtype: int64
80     77
81    134
82     63
83     33
Name: duration, dtype: int64

3:  77 2:  230 1:  0 0:  0 -1:  0
total_duration =  307
max Id:  2
start =  84   end =  88
84   -1
85   -1
86   -1
87   -1
Name: truth_int, dtype: int64
84    70
85    28
86    93
87    80
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  0 -1:  271
total_duration =  271
max Id:  -1
start =  88   end =  92
88    3
89    3
90    3
91    3
Name: truth_int, dtype: int64
88     8
89    11
90     8
91    25
Name: duration, dtype: int64
3:  52 2:  0 1:  0 0:  0 -1:  0
total_duration =  52
max Id:  3
start =  92   end =  92
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  96   end =  92
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  100   end =  92
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  104   end =  92
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  92
block_len 11
start =  0   end =  11
0     3
1     3
2     2
3     2
4     2
5     2
6     2
7     3
8     3
9     3
10    2
Name: truth_int, dtype: int64
0      21
1      75
2     152
3      14
4      36
5     127
6     131
7     132
8      30
9     115
10     34
Name: duration, dtype: int64
3:  373 2:  494 1:  0 0:  0 -1:  0
total_duration =  867
max Id:  2
start =  11   end =  22
11    3
12    3
13    2
14    2
15    3
16   -1
17   -1
18    3
19    2
20    3
21    3
Name: truth_int, dtype: int64
11    125
12    265
13     44
14    151
15     84
16    113
17    154
18     86
19     56
20     68
21     43
Name: duration, dtype: int64
3:  671 2:  251 1:  0 0:  0 -1:  267
total_duration =  1189
max Id:  3
start =  22   end =  33
22    3
23    1
24   -1
25    3
26    3
27    2
28    3
29    3
30   -1
31    3
32    0
Name: truth_int, dtype: int64
22     51
23     84
24     32
25     39
26    223
27    170
28     98
29     45
30     45
31    100
32     54
Name: duration, dtype: int64
3:  556 2:  170 1:  84 0:  54 -1:  77
total_duration =  941
max Id:  3
start =  33   end =  44
33   -1
34    3
35    3
36    3
37    3
38    3
39    3
40    3
41    3
42    3
43    3
Name: truth_int, dtype: int64
33     85
34     97
35     12
36     27
37     29
38     12
39     20
40     21
41     49
42    165
43     36
Name: duration, dtype: int64
3:  468 2:  0 1:  0 0:  0 -1:  85
total_duration =  553
max Id:  3
start =  44   end =  55
44    3
45    3
46    3
47    3
48    3
49    1
50    0
51    2
52    2
53    3
54    3
Name: truth_int, dtype: int64
44     15
45     61
46     49
47     52
48    237
49    107
50     31
51    105
52     43
53    144
54    118
Name: duration, dtype: int64
3:  676 2:  148 1:  107 0:  31 -1:  0
total_duration =  962
max Id:  3
start =  55   end =  66
55    0
56    3
57    1
58    3
59    3
60    3
61    3
62    3
63    3
64    3
65    3
Name: truth_int, dtype: int64
55     26
56    126
57    127
58    130
59    355
60    173
61    112
62    153
63     39
64    121
65     42
Name: duration, dtype: int64
3:  1251 2:  0 1:  127 0:  26 -1:  0
total_duration =  1404
max Id:  3
start =  66   end =  77
66    3
67    2
68    0
69    1
70    0
71   -1
72   -1
73    3
74   -1
75    2
76    3
Name: truth_int, dtype: int64
66    155
67     74
68     55
69     67
70    160
71    107
72    203
73     57
74     32
75     90
76     99
Name: duration, dtype: int64
3:  311 2:  164 1:  67 0:  215 -1:  342
total_duration =  1099
max Id:  -1
start =  77   end =  88
77    3
78    3
79    3
80    3
81    2
82    2
83    2
84   -1
85   -1
86   -1
87   -1
Name: truth_int, dtype: int64
77     30
78    159
79    151
80     77
81    134
82     63
83     33
84     70
85     28
86     93
87     80
Name: duration, dtype: int64
3:  417 2:  230 1:  0 0:  0 -1:  271
total_duration =  918
max Id:  3
start =  88   end =  92
88    3
89    3
90    3
91    3
Name: truth_int, dtype: int64
88     8
89    11
90     8
91    25
Name: duration, dtype: int64
3:  52 2:  0 1:  0 0:  0 -1:  0
total_duration =  52
max Id:  3
data len =  92
block_len 31
start =  0   end =  31
0     3
1     3
2     2
3     2
4     2
5     2
6     2
7     3
8     3
9     3
10    2
11    3
12    3
13    2
14    2
15    3
16   -1
17   -1
18    3
19    2
20    3
21    3
22    3
23    1
24   -1
25    3
26    3
27    2
28    3
29    3
30   -1
Name: truth_int, dtype: int64
0      21
1      75
2     152
3      14
4      36
5     127
6     131
7     132
8      30
9     115
10     34
11    125
12    265
13     44
14    151
15     84
16    113
17    154
18     86
19     56
20     68
21     43
22     51
23     84
24     32
25     39
26    223
27    170
28     98
29     45
30     45
Name: duration, dtype: int64
3:  1500 2:  915 1:  84 0:  0 -1:  344
total_duration =  2843
max Id:  3
start =  31   end =  62
31    3
32    0
33   -1
34    3
35    3
36    3
37    3
38    3
39    3
40    3
41    3
42    3
43    3
44    3
45    3
46    3
47    3
48    3
49    1
50    0
51    2
52    2
53    3
54    3
55    0
56    3
57    1
58    3
59    3
60    3
61    3
Name: truth_int, dtype: int64
31    100
32     54
33     85
34     97
35     12
36     27
37     29
38     12
39     20
40     21
41     49
42    165
43     36
44     15
45     61
46     49
47     52
48    237
49    107
50     31
51    105
52     43
53    144
54    118
55     26
56    126
57    127
58    130
59    355
60    173
61    112
Name: duration, dtype: int64
3:  2140 2:  148 1:  234 0:  111 -1:  85
total_duration =  2718
max Id:  3
start =  62   end =  92
62    3
63    3
64    3
65    3
66    3
67    2
68    0
69    1
70    0
71   -1
72   -1
73    3
74   -1
75    2
76    3
77    3
78    3
79    3
80    3
81    2
82    2
83    2
84   -1
85   -1
86   -1
87   -1
88    3
89    3
90    3
91    3
Name: truth_int, dtype: int64
62    153
63     39
64    121
65     42
66    155
67     74
68     55
69     67
70    160
71    107
72    203
73     57
74     32
75     90
76     99
77     30
78    159
79    151
80     77
81    134
82     63
83     33
84     70
85     28
86     93
87     80
88      8
89     11
90      8
91     25
Name: duration, dtype: int64
3:  1135 2:  394 1:  67 0:  215 -1:  613
total_duration =  2424
max Id:  3
data len =  92
block_len 92
start =  0   end =  92
0     3
1     3
2     2
3     2
4     2
5     2
6     2
7     3
8     3
9     3
10    2
11    3
12    3
13    2
14    2
15    3
16   -1
17   -1
18    3
19    2
20    3
21    3
22    3
23    1
24   -1
25    3
26    3
27    2
28    3
29    3
     ..
62    3
63    3
64    3
65    3
66    3
67    2
68    0
69    1
70    0
71   -1
72   -1
73    3
74   -1
75    2
76    3
77    3
78    3
79    3
80    3
81    2
82    2
83    2
84   -1
85   -1
86   -1
87   -1
88    3
89    3
90    3
91    3
Name: truth_int, Length: 92, dtype: int64
0      21
1      75
2     152
3      14
4      36
5     127
6     131
7     132
8      30
9     115
10     34
11    125
12    265
13     44
14    151
15     84
16    113
17    154
18     86
19     56
20     68
21     43
22     51
23     84
24     32
25     39
26    223
27    170
28     98
29     45
     ...
62    153
63     39
64    121
65     42
66    155
67     74
68     55
69     67
70    160
71    107
72    203
73     57
74     32
75     90
76     99
77     30
78    159
79    151
80     77
81    134
82     63
83     33
84     70
85     28
86     93
87     80
88      8
89     11
90      8
91     25
Name: duration, Length: 92, dtype: int64
3:  4775 2:  1457 1:  385 0:  326 -1:  1042
total_duration =  7985
max Id:  3
BridgeofSpies_ice1.csv
BridgeofSpies_ice1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7985
Name: duration, dtype: int64
3:  7985 2:  0 1:  0 0:  0 -1:  0
total_duration =  7985
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  9   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  10   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  11   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  12   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  13   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  14   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  15   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  16   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  17   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  18   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  19   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  20   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  21   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  22   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  23   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  24   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0

total_duration =  0
max Id:  -1
start =  25   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7985
Name: duration, dtype: int64
3:  7985 2:  0 1:  0 0:  0 -1:  0
total_duration =  7985
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7985
Name: duration, dtype: int64
3:  7985 2:  0 1:  0 0:  0 -1:  0
total_duration =  7985
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7985
Name: duration, dtype: int64
3:  7985 2:  0 1:  0 0:  0 -1:  0
total_duration =  7985
max Id:  3
BridgeofSpies_ice2.csv
BridgeofSpies_ice2
failed for  BridgeofSpies_ice2
BridgeofSpies_ice4.csv
BridgeofSpies_ice4
failed for  BridgeofSpies_ice4
BridgeofSpies_ice8.csv
BridgeofSpies_ice8
failed for  BridgeofSpies_ice8
CaptainPhillips.csv
CaptainPhillips
data len =  172
block_len 7
start =  0   end =  7
0     3
1     3
2     3
3     3
4    -1
5    -1
6    -1
Name: truth_int, dtype: object
0     46
1     18
2    104
3     41
4     10
5     12
6     19
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  250
failed for  CaptainPhillips
DallasBuyersClub.csv
DallasBuyersClub
data len =  159
block_len 6
start =  0   end =  6
0    2
1    3
2    1
3    1
4    0
5    0
Name: truth_int, dtype: int64
0    63
1    51
2    73
3    18
4    43
5    47
Name: duration, dtype: int64
3:  51 2:  63 1:  91 0:  90 -1:  0
total_duration =  295
max Id:  1
start =  6   end =  12
6     0
7    -1
8     3
9    -1
10    3
11   -1
Name: truth_int, dtype: int64
6     16
7     21
8     23
9     48
10     3
11    42
Name: duration, dtype: int64
3:  26 2:  0 1:  0 0:  16 -1:  111
total_duration =  153
max Id:  -1
start =  12   end =  18
12   -1
13    3
14    1
15   -1
16   -1
17   -1
Name: truth_int, dtype: int64
12     26
13     58
14    133
15     98
16     84
17     34
Name: duration, dtype: int64
3:  58 2:  0 1:  133 0:  0 -1:  242
total_duration =  433
max Id:  -1
start =  18   end =  24
18   -1
19    3
20    3
21    2
22    3
23    3
Name: truth_int, dtype: int64
18    12
19    10
20    88
21    21
22    33
23    18
Name: duration, dtype: int64
3:  149 2:  21 1:  0 0:  0 -1:  12
total_duration =  182
max Id:  3
start =  24   end =  30
24   -1
25    3
26    1
27   -1
28    2
29    2
Name: truth_int, dtype: int64
24     11
25     28
26     35
27      8
28    147
29     85
Name: duration, dtype: int64
3:  28 2:  232 1:  35 0:  0 -1:  19
total_duration =  314
max Id:  2
start =  30   end =  36
30    2
31    2
32    3
33    1
34    0
35    2
Name: truth_int, dtype: int64
30     7
31    64
32    46
33    47
34    23
35    41
Name: duration, dtype: int64
3:  46 2:  112 1:  47 0:  23 -1:  0
total_duration =  228
max Id:  2
start =  36   end =  42
36    3
37    2
38    2
39    0
40    0
41    0
Name: truth_int, dtype: int64
36    37
37    50
38    44
39    73
40    74
41    26
Name: duration, dtype: int64
3:  37 2:  94 1:  0 0:  173 -1:  0
total_duration =  304
max Id:  0
start =  42   end =  48
42    0
43    0
44    2
45    3
46    2
47   -1
Name: truth_int, dtype: int64
42    42
43    23
44    65
45    29
46    47
47    36
Name: duration, dtype: int64
3:  29 2:  112 1:  0 0:  65 -1:  36
total_duration =  242
max Id:  2
start =  48   end =  54
48   -1
49   -1
50    2
51    3
52    3
53    0
Name: truth_int, dtype: int64
48    18
49    78
50    20
51    33
52    69
53    76
Name: duration, dtype: int64
3:  102 2:  20 1:  0 0:  76 -1:  96
total_duration =  294
max Id:  3
start =  54   end =  60
54    3
55    3
56    3
57    3
58   -1
59    3
Name: truth_int, dtype: int64
54     87
55     58
56     41
57    114
58     48
59     23
Name: duration, dtype: int64
3:  323 2:  0 1:  0 0:  0 -1:  48
total_duration =  371
max Id:  3
start =  60   end =  66
60    3
61    0
62    0
63    0
64    1
65    3
Name: truth_int, dtype: int64
60    31
61    69
62    65
63    13
64    67
65    16
Name: duration, dtype: int64
3:  47 2:  0 1:  67 0:  147 -1:  0
total_duration =  261
max Id:  0
start =  66   end =  72
66    2
67    2
68    3
69    3
70    2
71    0
Name: truth_int, dtype: int64
66     18
67     17
68     61
69      0
70    119
71     16
Name: duration, dtype: int64
3:  61 2:  154 1:  0 0:  16 -1:  0
total_duration =  231
max Id:  2
start =  72   end =  78
72    3
73    2
74    2
75    0
76    3
77   -1
Name: truth_int, dtype: int64
72     21
73     50
74     41
75    104
76     12
77     27
Name: duration, dtype: int64
3:  33 2:  91 1:  0 0:  104 -1:  27
total_duration =  255
max Id:  0
start =  78   end =  84
78    2
79    3
80    3
81    3
82    3
83    3
Name: truth_int, dtype: int64
78    77
79    11
80    67
81    33
82    19
83    28
Name: duration, dtype: int64
3:  158 2:  77 1:  0 0:  0 -1:  0
total_duration =  235
max Id:  3
start =  84   end =  90
84    2
85    2
86    2
87    2
88    3
89    2
Name: truth_int, dtype: int64
84     47
85    107
86      6
87     31
88     30
89     29
Name: duration, dtype: int64
3:  30 2:  220 1:  0 0:  0 -1:  0
total_duration =  250
max Id:  2
start =  90   end =  96
90    2
91    2
92    3
93   -1
94   -1
95   -1
Name: truth_int, dtype: int64
90    97
91    20
92    12
93    16
94    11
95    15
Name: duration, dtype: int64
3:  12 2:  117 1:  0 0:  0 -1:  42
total_duration =  171
max Id:  2
start =  96   end =  102
96    -1
97     0
98     3
99     3
100    3
101    0
Name: truth_int, dtype: int64
96     15
97     50
98     26
99     19
100    30
101    37
Name: duration, dtype: int64
3:  75 2:  0 1:  0 0:  87 -1:  15
total_duration =  177
max Id:  0
start =  102   end =  108
102    0
103    0
104   -1
105   -1
106    0
107    3
Name: truth_int, dtype: int64
102     27
103     40
104    149
105     21
106      9
107     89
Name: duration, dtype: int64
3:  89 2:  0 1:  0 0:  76 -1:  170
total_duration =  335
max Id:  -1
start =  108   end =  114
108    3
109    3
110    3
111    1
112    0
113   -1
Name: truth_int, dtype: int64
108    15
109    39
110    20
111    76
112    44
113    24
Name: duration, dtype: int64
3:  74 2:  0 1:  76 0:  44 -1:  24
total_duration =  218
max Id:  1
start =  114   end =  120
114    1
115    0
116    3
117    0
118    3
119    0
Name: truth_int, dtype: int64
114     38
115    124
116      9
117     34
118     12
119     39
Name: duration, dtype: int64
3:  21 2:  0 1:  38 0:  197 -1:  0
total_duration =  256
max Id:  0
start =  120   end =  126
120    1
121    0
122    0
123    3
124    0
125   -1
Name: truth_int, dtype: int64
120    53
121    81
122    58
123    54
124    39
125    56
Name: duration, dtype: int64
3:  54 2:  0 1:  53 0:  178 -1:  56
total_duration =  341
max Id:  0
start =  126   end =  132
126    0
127    1
128    2
129    0
130    0
131    1
Name: truth_int, dtype: int64
126    14
127    10
128    42
129    23
130    19
131    11
Name: duration, dtype: int64
3:  0 2:  42 1:  21 0:  56 -1:  0
total_duration =  119
max Id:  0
start =  132   end =  138
132    1
133   -1
134   -1
135    3
136   -1
137    2
Name: truth_int, dtype: int64
132    40
133    17
134    47
135    23
136    44
137    72
Name: duration, dtype: int64
3:  23 2:  72 1:  40 0:  0 -1:  108
total_duration =  243
max Id:  -1
start =  138   end =  144
138    0
139    3
140    3
141    0
142    3
143    0
Name: truth_int, dtype: int64
138    59
139    16
140    34
141    10
142    80
143    32
Name: duration, dtype: int64
3:  130 2:  0 1:  0 0:  101 -1:  0
total_duration =  231
max Id:  3
start =  144   end =  150
144    1
145    0
146    3
147   -1
148    0
149    0
Name: truth_int, dtype: int64
144    138
145     32
146     18
147     54
148     18
149     32
Name: duration, dtype: int64
3:  18 2:  0 1:  138 0:  82 -1:  54
total_duration =  292
max Id:  1
start =  150   end =  156
150    3
151    3
152    0
153    3
154    3
155    3
Name: truth_int, dtype: int64
150    16
151    79
152     5
153     5
154    39
155     7
Name: duration, dtype: int64
3:  146 2:  0 1:  0 0:  5 -1:  0
total_duration =  151
max Id:  3
start =  156   end =  159
156    0
157    3
158    3
Name: truth_int, dtype: int64
156    79
157    16
158     9
Name: duration, dtype: int64
3:  25 2:  0 1:  0 0:  79 -1:  0
total_duration =  104
max Id:  0

data len =  159
block_len 18
start =  0   end =  18
0     2
1     3
2     1
3     1
4     0
5     0
6     0
7    -1
8     3
9    -1
10    3
11   -1
12   -1
13    3
14    1
15   -1
16   -1
17   -1
Name: truth_int, dtype: int64
0      63
1      51
2      73
3      18
4      43
5      47
6      16
7      21
8      23
9      48
10      3
11     42
12     26
13     58
14    133
15     98
16     84
17     34
Name: duration, dtype: int64
3:  135 2:  63 1:  224 0:  106 -1:  353
total_duration =  881
max Id:  -1
start =  18   end =  36
18   -1
19    3
20    3
21    2
22    3
23    3
24   -1
25    3
26    1
27   -1
28    2
29    2
30    2
31    2
32    3
33    1
34    0
35    2
Name: truth_int, dtype: int64
18     12
19     10
20     88
21     21
22     33
23     18
24     11
25     28
26     35
27      8
28    147
29     85
30      7
31     64
32     46
33     47
34     23
35     41
Name: duration, dtype: int64
3:  223 2:  365 1:  82 0:  23 -1:  31
total_duration =  724
max Id:  2
start =  36   end =  54
36    3
37    2
38    2
39    0
40    0
41    0
42    0
43    0
44    2
45    3
46    2
47   -1
48   -1
49   -1
50    2
51    3
52    3
53    0
Name: truth_int, dtype: int64
36    37
37    50
38    44
39    73
40    74
41    26
42    42
43    23
44    65
45    29
46    47
47    36
48    18
49    78
50    20
51    33
52    69
53    76
Name: duration, dtype: int64
3:  168 2:  226 1:  0 0:  314 -1:  132
total_duration =  840
max Id:  0
start =  54   end =  72
54    3
55    3
56    3
57    3
58   -1
59    3
60    3
61    0
62    0
63    0
64    1
65    3
66    2
67    2
68    3
69    3
70    2
71    0
Name: truth_int, dtype: int64
54     87
55     58
56     41
57    114
58     48
59     23
60     31
61     69
62     65
63     13
64     67
65     16
66     18
67     17
68     61
69      0
70    119
71     16
Name: duration, dtype: int64
3:  431 2:  154 1:  67 0:  163 -1:  48
total_duration =  863
max Id:  3
start =  72   end =  90
72    3
73    2
74    2
75    0
76    3
77   -1
78    2
79    3
80    3
81    3
82    3
83    3
84    2
85    2
86    2
87    2
88    3
89    2
Name: truth_int, dtype: int64
72     21
73     50
74     41
75    104
76     12
77     27
78     77
79     11
80     67
81     33
82     19
83     28
84     47
85    107
86      6
87     31
88     30
89     29
Name: duration, dtype: int64
3:  221 2:  388 1:  0 0:  104 -1:  27
total_duration =  740
max Id:  2
start =  90   end =  108
90     2
91     2
92     3
93    -1
94    -1
95    -1
96    -1
97     0
98     3
99     3
100    3
101    0
102    0
103    0
104   -1
105   -1
106    0
107    3
Name: truth_int, dtype: int64
90      97
91      20
92      12
93      16
94      11
95      15
96      15
97      50
98      26
99      19
100     30
101     37
102     27
103     40
104    149
105     21
106      9
107     89
Name: duration, dtype: int64
3:  176 2:  117 1:  0 0:  163 -1:  227
total_duration =  683
max Id:  -1
start =  108   end =  126
108    3
109    3
110    3
111    1
112    0
113   -1
114    1
115    0
116    3
117    0
118    3
119    0
120    1
121    0
122    0
123    3
124    0
125   -1
Name: truth_int, dtype: int64
108     15
109     39
110     20
111     76
112     44
113     24
114     38
115    124
116      9
117     34
118     12
119     39
120     53
121     81
122     58
123     54
124     39
125     56
Name: duration, dtype: int64
3:  149 2:  0 1:  167 0:  419 -1:  80
total_duration =  815
max Id:  0
start =  126   end =  144
126    0
127    1
128    2
129    0
130    0
131    1
132    1
133   -1
134   -1
135    3
136   -1
137    2
138    0
139    3
140    3
141    0
142    3
143    0
Name: truth_int, dtype: int64
126    14
127    10
128    42
129    23
130    19
131    11
132    40
133    17
134    47
135    23
136    44
137    72
138    59
139    16
140    34
141    10
142    80
143    32
Name: duration, dtype: int64
3:  153 2:  114 1:  61 0:  157 -1:  108
total_duration =  593
max Id:  0
start =  144   end =  159
144    1
145    0
146    3
147   -1
148    0
149    0
150    3
151    3
152    0
153    3
154    3
155    3
156    0
157    3
158    3
Name: truth_int, dtype: int64
144    138
145     32
146     18
147     54
148     18
149     32
150     16
151     79
152      5
153      5
154     39
155      7
156     79
157     16
158      9
Name: duration, dtype: int64
3:  189 2:  0 1:  138 0:  166 -1:  54
total_duration =  547
max Id:  3
data len =  159
block_len 53
start =  0   end =  53
0     2
1     3
2     1
3     1
4     0
5     0
6     0
7    -1
8     3
9    -1
10    3
11   -1
12   -1
13    3
14    1
15   -1
16   -1
17   -1
18   -1
19    3
20    3
21    2
22    3
23    3
24   -1
25    3
26    1
27   -1
28    2
29    2
30    2
31    2
32    3
33    1
34    0
35    2
36    3
37    2
38    2
39    0
40    0
41    0
42    0
43    0
44    2
45    3
46    2
47   -1
48   -1
49   -1
50    2
51    3
52    3
Name: truth_int, dtype: int64
0      63
1      51
2      73
3      18
4      43
5      47
6      16
7      21
8      23
9      48
10      3
11     42
12     26
13     58
14    133
15     98
16     84
17     34
18     12
19     10
20     88
21     21
22     33
23     18
24     11
25     28
26     35
27      8
28    147
29     85
30      7
31     64
32     46
33     47
34     23
35     41
36     37
37     50
38     44
39     73
40     74
41     26
42     42
43     23
44     65
45     29
46     47
47     36
48     18
49     78
50     20
51     33
52     69
Name: duration, dtype: int64
3:  526 2:  654 1:  306 0:  367 -1:  516
total_duration =  2369
max Id:  2
start =  53   end =  106
53     0
54     3
55     3
56     3
57     3
58    -1
59     3
60     3
61     0
62     0
63     0
64     1
65     3
66     2
67     2
68     3
69     3
70     2
71     0
72     3
73     2
74     2
75     0
76     3
77    -1
78     2
79     3
80     3
81     3
82     3
83     3
84     2
85     2
86     2
87     2
88     3
89     2
90     2
91     2
92     3
93    -1
94    -1
95    -1
96    -1
97     0
98     3
99     3
100    3
101    0
102    0
103    0
104   -1
105   -1
Name: truth_int, dtype: int64
53      76
54      87
55      58
56      41
57     114
58      48
59      23
60      31
61      69
62      65
63      13
64      67
65      16
66      18
67      17
68      61
69       0
70     119
71      16
72      21
73      50
74      41
75     104
76      12
77      27
78      77
79      11
80      67
81      33
82      19
83      28
84      47
85     107
86       6
87      31
88      30
89      29
90      97
91      20
92      12
93      16
94      11
95      15
96      15
97      50
98      26
99      19
100     30
101     37
102     27
103     40
104    149
105     21
Name: duration, dtype: int64
3:  739 2:  659 1:  67 0:  497 -1:  302
total_duration =  2264
max Id:  3
start =  106   end =  159
106    0
107    3
108    3
109    3
110    3
111    1
112    0
113   -1
114    1
115    0
116    3
117    0
118    3
119    0
120    1
121    0
122    0
123    3
124    0
125   -1
126    0
127    1
128    2
129    0
130    0
131    1
132    1
133   -1
134   -1
135    3
136   -1
137    2
138    0
139    3
140    3
141    0
142    3
143    0
144    1
145    0
146    3
147   -1
148    0
149    0
150    3
151    3
152    0
153    3
154    3
155    3
156    0
157    3
158    3
Name: truth_int, dtype: int64
106      9
107     89
108     15
109     39
110     20
111     76
112     44
113     24
114     38
115    124
116      9
117     34
118     12
119     39
120     53
121     81
122     58
123     54
124     39
125     56
126     14
127     10
128     42
129     23
130     19
131     11
132     40
133     17
134     47
135     23
136     44
137     72
138     59
139     16
140     34
141     10
142     80
143     32
144    138
145     32
146     18
147     54
148     18
149     32
150     16
151     79
152      5
153      5
154     39
155      7
156     79
157     16
158      9
Name: duration, dtype: int64
3:  580 2:  114 1:  366 0:  751 -1:  242
total_duration =  2053
max Id:  0
data len =  159
block_len 159
start =  0   end =  159
0      2
1      3
2      1
3      1
4      0
5      0
6      0
7     -1
8      3
9     -1
10     3
11    -1
12    -1
13     3
14     1
15    -1
16    -1
17    -1
18    -1
19     3
20     3
21     2
22     3
23     3
24    -1
25     3
26     1
27    -1
28     2
29     2
      ..
129    0
130    0
131    1
132    1
133   -1
134   -1
135    3
136   -1
137    2
138    0
139    3
140    3
141    0
142    3
143    0
144    1
145    0
146    3
147   -1
148    0
149    0
150    3
151    3
152    0
153    3
154    3
155    3
156    0
157    3
158    3
Name: truth_int, Length: 159, dtype: int64
0       63
1       51
2       73
3       18
4       43
5       47
6       16
7       21
8       23
9       48
10       3
11      42
12      26
13      58
14     133
15      98
16      84
17      34
18      12
19      10
20      88
21      21
22      33
23      18
24      11
25      28
26      35
27       8
28     147
29      85
      ...
129     23
130     19
131     11
132     40
133     17
134     47
135     23
136     44
137     72
138     59
139     16
140     34
141     10
142     80
143     32
144    138
145     32
146     18
147     54
148     18
149     32
150     16
151     79
152      5
153      5
154     39
155      7
156     79
157     16
158      9
Name: duration, Length: 159, dtype: int64
3:  1845 2:  1427 1:  739 0:  1615 -1:  1060
total_duration =  6686
max Id:  3
DallasBuyersClub_ice1.csv
DallasBuyersClub_ice1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    6686
Name: duration, dtype: int64
3:  6686 2:  0 1:  0 0:  0 -1:  0
total_duration =  6686
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  9   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  10   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  11   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  12   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  13   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  14   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  15   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1

start =  16   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  17   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  18   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  19   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  20   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  21   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  22   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  23   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  24   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  25   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    6686
Name: duration, dtype: int64
3:  6686 2:  0 1:  0 0:  0 -1:  0
total_duration =  6686
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    6686
Name: duration, dtype: int64
3:  6686 2:  0 1:  0 0:  0 -1:  0
total_duration =  6686
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    6686
Name: duration, dtype: int64
3:  6686 2:  0 1:  0 0:  0 -1:  0
total_duration =  6686
max Id:  3
DallasBuyersClub_ice2.csv
DallasBuyersClub_ice2
failed for  DallasBuyersClub_ice2
DallasBuyersClub_ice4.csv
DallasBuyersClub_ice4
failed for  DallasBuyersClub_ice4
DallasBuyersClub_ice8.csv
DallasBuyersClub_ice8
failed for  DallasBuyersClub_ice8
HiddenFigures.csv
HiddenFigures
data len =  111
block_len 5
start =  0   end =  5
0    3
1    3
2    3
3    3
4    0
Name: truth_int, dtype: int64
0    20
1    29
2    63
3    23
4    64
Name: duration, dtype: int64
3:  135 2:  0 1:  0 0:  64 -1:  0
total_duration =  199
max Id:  3
start =  5   end =  10
5    0
6    0
7    3
8    3
9    3
Name: truth_int, dtype: int64
5    143
6     47
7     52
8     13
9     69
Name: duration, dtype: int64
3:  134 2:  0 1:  0 0:  190 -1:  0
total_duration =  324
max Id:  0
start =  10   end =  15
10    3
11    3
12    3
13    3
14    1
Name: truth_int, dtype: int64
10     54
11    104
12     52
13     24
14     28
Name: duration, dtype: int64
3:  234 2:  0 1:  28 0:  0 -1:  0
total_duration =  262
max Id:  3
start =  15   end =  20
15    2
16    3
17    2
18    1
19    3
Name: truth_int, dtype: int64
15    122
16     50
17     65
18     90
19     65
Name: duration, dtype: int64
3:  115 2:  187 1:  90 0:  0 -1:  0
total_duration =  392
max Id:  2
start =  20   end =  25
20   -1
21    2
22    2
23    0
24    1
Name: truth_int, dtype: int64
20     45
21     38
22    111
23     17
24     57
Name: duration, dtype: int64
3:  0 2:  149 1:  57 0:  17 -1:  45
total_duration =  268
max Id:  2
start =  25   end =  30
25    1
26    1
27    3
28    3
29    3
Name: truth_int, dtype: int64
25    116
26    113
27     68
28    156
29     71
Name: duration, dtype: int64
3:  295 2:  0 1:  229 0:  0 -1:  0
total_duration =  524
max Id:  3
start =  30   end =  35
30   -1
31    2
32   -1
33   -1
34    1
Name: truth_int, dtype: int64
30     80
31     84
32     84
33    104
34     27
Name: duration, dtype: int64
3:  0 2:  84 1:  27 0:  0 -1:  268
total_duration =  379
max Id:  -1
start =  35   end =  40
35    0
36    0
37    3
38    3
39    0
Name: truth_int, dtype: int64
35     58
36     32
37     88
38     70
39    132
Name: duration, dtype: int64
3:  158 2:  0 1:  0 0:  222 -1:  0
total_duration =  380
max Id:  0
start =  40   end =  45
40    2
41    3
42    2
43    1
44    2
Name: truth_int, dtype: int64
40    30
41    49
42    36
43    59
44    28
Name: duration, dtype: int64
3:  49 2:  94 1:  59 0:  0 -1:  0
total_duration =  202
max Id:  2
start =  45   end =  50
45    1
46    1
47    1
48   -1
49    3
Name: truth_int, dtype: int64
45     44
46     50
47     34
48    114
49     23
Name: duration, dtype: int64
3:  23 2:  0 1:  128 0:  0 -1:  114
total_duration =  265
max Id:  1
start =  50   end =  55
50    3
51    3
52    3
53    3
54    3
Name: truth_int, dtype: int64
50     30
51    114
52     28
53      9
54     81
Name: duration, dtype: int64
3:  262 2:  0 1:  0 0:  0 -1:  0
total_duration =  262
max Id:  3
start =  55   end =  60
55    2
56    2
57    3
58    1
59    2
Name: truth_int, dtype: int64
55    47
56    22
57    13
58    23
59    69
Name: duration, dtype: int64
3:  13 2:  138 1:  23 0:  0 -1:  0
total_duration =  174
max Id:  2
start =  60   end =  65
60    1
61    1
62    0
63   -1
64    3
Name: truth_int, dtype: int64
60    116
61     20
62     66
63     58
64     25
Name: duration, dtype: int64
3:  25 2:  0 1:  136 0:  66 -1:  58
total_duration =  285
max Id:  1
start =  65   end =  70
65    3
66    3
67    2
68    3
69    3
Name: truth_int, dtype: int64
65    134
66     33
67     77
68     39
69    165
Name: duration, dtype: int64
3:  371 2:  77 1:  0 0:  0 -1:  0
total_duration =  448
max Id:  3
start =  70   end =  75
70    3
71    3
72    2
73    3
74    3
Name: truth_int, dtype: int64
70    24
71    65
72    10
73    43
74    48
Name: duration, dtype: int64
3:  180 2:  10 1:  0 0:  0 -1:  0
total_duration =  190
max Id:  3
start =  75   end =  80
75    3
76    3
77    0
78    3
79    3
Name: truth_int, dtype: int64
75    123
76     29
77     52
78     34
79     15
Name: duration, dtype: int64
3:  201 2:  0 1:  0 0:  52 -1:  0
total_duration =  253
max Id:  3
start =  80   end =  85
80    2
81    3
82    0
83    3
84    2
Name: truth_int, dtype: int64
80     23
81     67
82    242
83     31
84     60
Name: duration, dtype: int64
3:  98 2:  83 1:  0 0:  242 -1:  0
total_duration =  423
max Id:  0
start =  85   end =  90
85    0
86    2
87   -1
88    2
89    3
Name: truth_int, dtype: int64
85     59
86     51
87     74
88     51
89    103
Name: duration, dtype: int64
3:  103 2:  102 1:  0 0:  59 -1:  74
total_duration =  338
max Id:  3
start =  90   end =  95
90    3
91    2
92    2
93    3
94    1
Name: truth_int, dtype: int64
90     11
91    150
92     93
93     23
94     92
Name: duration, dtype: int64
3:  34 2:  243 1:  92 0:  0 -1:  0
total_duration =  369
max Id:  2
start =  95   end =  100
95    1
96    2
97    2
98    2
99    2
Name: truth_int, dtype: int64
95     64
96     28
97     25
98     66
99    126
Name: duration, dtype: int64
3:  0 2:  245 1:  64 0:  0 -1:  0
total_duration =  309
max Id:  2
start =  100   end =  105
100    2
101    0
102    3
103    3
104    2
Name: truth_int, dtype: int64
100     74
101     34
102     60
103    103
104     85
Name: duration, dtype: int64
3:  163 2:  159 1:  0 0:  34 -1:  0
total_duration =  356
max Id:  3
start =  105   end =  110
105    3
106    3
107    3
108    2
109    3
Name: truth_int, dtype: int64
105     48
106    187
107    119
108     37
109     50
Name: duration, dtype: int64
3:  404 2:  37 1:  0 0:  0 -1:  0
total_duration =  441
max Id:  3
start =  110   end =  111
110    3
Name: truth_int, dtype: int64
110    68
Name: duration, dtype: int64
3:  68 2:  0 1:  0 0:  0 -1:  0
total_duration =  68
max Id:  3
start =  115   end =  111
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  120   end =  111
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  125   end =  111
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  130   end =  111
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1

data len =  111
block_len 13
start =  0   end =  13
0     3
1     3
2     3
3     3
4     0
5     0
6     0
7     3
8     3
9     3
10    3
11    3
12    3
Name: truth_int, dtype: int64
0      20
1      29
2      63
3      23
4      64
5     143
6      47
7      52
8      13
9      69
10     54
11    104
12     52
Name: duration, dtype: int64
3:  479 2:  0 1:  0 0:  254 -1:  0
total_duration =  733
max Id:  3
start =  13   end =  26
13    3
14    1
15    2
16    3
17    2
18    1
19    3
20   -1
21    2
22    2
23    0
24    1
25    1
Name: truth_int, dtype: int64
13     24
14     28
15    122
16     50
17     65
18     90
19     65
20     45
21     38
22    111
23     17
24     57
25    116
Name: duration, dtype: int64
3:  139 2:  336 1:  291 0:  17 -1:  45
total_duration =  828
max Id:  2
start =  26   end =  39
26    1
27    3
28    3
29    3
30   -1
31    2
32   -1
33   -1
34    1
35    0
36    0
37    3
38    3
Name: truth_int, dtype: int64
26    113
27     68
28    156
29     71
30     80
31     84
32     84
33    104
34     27
35     58
36     32
37     88
38     70
Name: duration, dtype: int64
3:  453 2:  84 1:  140 0:  90 -1:  268
total_duration =  1035
max Id:  3
start =  39   end =  52
39    0
40    2
41    3
42    2
43    1
44    2
45    1
46    1
47    1
48   -1
49    3
50    3
51    3
Name: truth_int, dtype: int64
39    132
40     30
41     49
42     36
43     59
44     28
45     44
46     50
47     34
48    114
49     23
50     30
51    114
Name: duration, dtype: int64
3:  216 2:  94 1:  187 0:  132 -1:  114
total_duration =  743
max Id:  3
start =  52   end =  65
52    3
53    3
54    3
55    2
56    2
57    3
58    1
59    2
60    1
61    1
62    0
63   -1
64    3
Name: truth_int, dtype: int64
52     28
53      9
54     81
55     47
56     22
57     13
58     23
59     69
60    116
61     20
62     66
63     58
64     25
Name: duration, dtype: int64
3:  156 2:  138 1:  159 0:  66 -1:  58
total_duration =  577
max Id:  1
start =  65   end =  78
65    3
66    3
67    2
68    3
69    3
70    3
71    3
72    2
73    3
74    3
75    3
76    3
77    0
Name: truth_int, dtype: int64
65    134
66     33
67     77
68     39
69    165
70     24
71     65
72     10
73     43
74     48
75    123
76     29
77     52
Name: duration, dtype: int64
3:  703 2:  87 1:  0 0:  52 -1:  0
total_duration =  842
max Id:  3
start =  78   end =  91
78    3
79    3
80    2
81    3
82    0
83    3
84    2
85    0
86    2
87   -1
88    2
89    3
90    3
Name: truth_int, dtype: int64
78     34
79     15
80     23
81     67
82    242
83     31
84     60
85     59
86     51
87     74
88     51
89    103
90     11
Name: duration, dtype: int64
3:  261 2:  185 1:  0 0:  301 -1:  74
total_duration =  821
max Id:  0
start =  91   end =  104
91     2
92     2
93     3
94     1
95     1
96     2
97     2
98     2
99     2
100    2
101    0
102    3
103    3
Name: truth_int, dtype: int64
91     150
92      93
93      23
94      92
95      64
96      28
97      25
98      66
99     126
100     74
101     34
102     60
103    103
Name: duration, dtype: int64
3:  186 2:  562 1:  156 0:  34 -1:  0
total_duration =  938
max Id:  2
start =  104   end =  111
104    2
105    3
106    3
107    3
108    2
109    3
110    3
Name: truth_int, dtype: int64
104     85
105     48
106    187
107    119
108     37
109     50
110     68
Name: duration, dtype: int64
3:  472 2:  122 1:  0 0:  0 -1:  0
total_duration =  594
max Id:  3
data len =  111
block_len 37
start =  0   end =  37
0     3
1     3
2     3
3     3
4     0
5     0
6     0
7     3
8     3
9     3
10    3
11    3
12    3
13    3
14    1
15    2
16    3
17    2
18    1
19    3
20   -1
21    2
22    2
23    0
24    1
25    1
26    1
27    3
28    3
29    3
30   -1
31    2
32   -1
33   -1
34    1
35    0
36    0
Name: truth_int, dtype: int64
0      20
1      29
2      63
3      23
4      64
5     143
6      47
7      52
8      13
9      69
10     54
11    104
12     52
13     24
14     28
15    122
16     50
17     65
18     90
19     65
20     45
21     38
22    111
23     17
24     57
25    116
26    113
27     68
28    156
29     71
30     80
31     84
32     84
33    104
34     27
35     58
36     32
Name: duration, dtype: int64
3:  913 2:  420 1:  431 0:  361 -1:  313
total_duration =  2438
max Id:  3
start =  37   end =  74
37    3
38    3
39    0
40    2
41    3
42    2
43    1
44    2
45    1
46    1
47    1
48   -1
49    3
50    3
51    3
52    3
53    3
54    3
55    2
56    2
57    3
58    1
59    2
60    1
61    1
62    0
63   -1
64    3
65    3
66    3
67    2
68    3
69    3
70    3
71    3
72    2
73    3
Name: truth_int, dtype: int64
37     88
38     70
39    132
40     30
41     49
42     36
43     59
44     28
45     44
46     50
47     34
48    114
49     23
50     30
51    114
52     28
53      9
54     81
55     47
56     22
57     13
58     23
59     69
60    116
61     20
62     66
63     58
64     25
65    134
66     33
67     77
68     39
69    165
70     24
71     65
72     10
73     43
Name: duration, dtype: int64
3:  1033 2:  319 1:  346 0:  198 -1:  172
total_duration =  2068
max Id:  3
start =  74   end =  111
74     3
75     3
76     3
77     0
78     3
79     3
80     2
81     3
82     0
83     3
84     2
85     0
86     2
87    -1
88     2
89     3
90     3
91     2
92     2
93     3
94     1
95     1
96     2
97     2
98     2
99     2
100    2
101    0
102    3
103    3
104    2
105    3
106    3
107    3
108    2
109    3
110    3
Name: truth_int, dtype: int64
74      48
75     123
76      29
77      52
78      34
79      15
80      23
81      67
82     242
83      31
84      60
85      59
86      51
87      74
88      51
89     103
90      11
91     150
92      93
93      23
94      92
95      64
96      28
97      25
98      66
99     126
100     74
101     34
102     60
103    103
104     85
105     48
106    187
107    119
108     37
109     50
110     68
Name: duration, dtype: int64
3:  1119 2:  869 1:  156 0:  387 -1:  74
total_duration =  2605
max Id:  3
data len =  111
block_len 111
start =  0   end =  111
0      3
1      3
2      3
3      3
4      0
5      0
6      0
7      3
8      3
9      3
10     3
11     3
12     3
13     3
14     1
15     2
16     3
17     2
18     1
19     3
20    -1
21     2
22     2
23     0
24     1
25     1
26     1
27     3
28     3
29     3
      ..
81     3
82     0
83     3
84     2
85     0
86     2
87    -1
88     2
89     3
90     3
91     2
92     2
93     3
94     1
95     1
96     2
97     2
98     2
99     2
100    2
101    0
102    3
103    3
104    2
105    3
106    3
107    3
108    2
109    3
110    3
Name: truth_int, Length: 111, dtype: int64
0       20
1       29
2       63
3       23
4       64
5      143
6       47
7       52
8       13
9       69
10      54
11     104
12      52
13      24
14      28
15     122
16      50
17      65
18      90
19      65
20      45
21      38
22     111
23      17
24      57
25     116
26     113
27      68
28     156
29      71
      ...
81      67
82     242
83      31
84      60
85      59
86      51
87      74
88      51
89     103
90      11
91     150
92      93
93      23
94      92
95      64
96      28
97      25
98      66
99     126
100     74
101     34
102     60
103    103
104     85
105     48
106    187
107    119
108     37
109     50
110     68
Name: duration, Length: 111, dtype: int64
3:  3065 2:  1608 1:  933 0:  946 -1:  559
total_duration =  7111
max Id:  3
HiddenFigures_ice1.csv
HiddenFigures_ice1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7111
Name: duration, dtype: int64
3:  7111 2:  0 1:  0 0:  0 -1:  0
total_duration =  7111
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  9   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  10   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  11   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  12   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  13   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  14   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  15   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  16   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  17   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  18   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  19   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  20   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  21   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  22   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  23   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  24   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  25   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1

data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7111
Name: duration, dtype: int64
3:  7111 2:  0 1:  0 0:  0 -1:  0
total_duration =  7111
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7111
Name: duration, dtype: int64
3:  7111 2:  0 1:  0 0:  0 -1:  0
total_duration =  7111
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7111
Name: duration, dtype: int64
3:  7111 2:  0 1:  0 0:  0 -1:  0
total_duration =  7111
max Id:  3
HiddenFigures_ice2.csv
HiddenFigures_ice2
failed for  HiddenFigures_ice2
HiddenFigures_ice4.csv
HiddenFigures_ice4
failed for  HiddenFigures_ice4
HiddenFigures_ice8.csv
HiddenFigures_ice8
failed for  HiddenFigures_ice8
Lion.csv
Lion
data len =  170
block_len 7
start =  0   end =  7
0    3.0
1    2.0
2    3.0
3    1.0
4    1.0
5    2.0
6    0.0
Name: truth_int, dtype: float64
0    109
1     22
2     11
3     27
4     34
5     50
6     22
Name: duration, dtype: int64
3:  120 2:  72 1:  61 0:  22 -1:  0
total_duration =  275
max Id:  3
start =  7   end =  14
7     1.0
8     1.0
9     3.0
10    3.0
11    1.0
12    0.0
13    3.0
Name: truth_int, dtype: float64
7     31
8     39
9     15
10    31
11    11
12    35
13    15
Name: duration, dtype: int64
3:  61 2:  0 1:  81 0:  35 -1:  0
total_duration =  177
max Id:  1
start =  14   end =  21
14    3.0
15    2.0
16    3.0
17    3.0
18    3.0
19    3.0
20    2.0
Name: truth_int, dtype: float64
14     3
15    13
16    20
17    41
18    37
19    71
20    24
Name: duration, dtype: int64
3:  172 2:  37 1:  0 0:  0 -1:  0
total_duration =  209
max Id:  3
start =  21   end =  28
21    3.0
22    3.0
23    2.0
24    1.0
25    2.0
26    3.0
27    2.0
Name: truth_int, dtype: float64
21    67
22    38
23    14
24    47
25    27
26    41
27    83
Name: duration, dtype: int64
3:  146 2:  124 1:  47 0:  0 -1:  0
total_duration =  317
max Id:  3
start =  28   end =  35
28    0.0
29    2.0
30    0.0
31    3.0
32    2.0
33    1.0
34    2.0
Name: truth_int, dtype: float64
28    50
29    42
30    64
31    15
32    33
33    22
34    11
Name: duration, dtype: int64
3:  15 2:  86 1:  22 0:  114 -1:  0
total_duration =  237
max Id:  0
start =  35   end =  42
35    2.0
36    2.0
37    2.0
38    3.0
39    0.0
40    3.0
41    2.0
Name: truth_int, dtype: float64
35    53
36    37
37    23
38    28
39    10
40    34
41    49
Name: duration, dtype: int64
3:  62 2:  162 1:  0 0:  10 -1:  0
total_duration =  234
max Id:  2
start =  42   end =  49
42    1.0
43    1.0
44    0.0
45    NaN
46    2.0
47    3.0
48    1.0
Name: truth_int, dtype: float64
42     21
43     35
44     44
45     15
46     43
47    109
48     19
Name: duration, dtype: int64
3:  109 2:  43 1:  75 0:  44 -1:  0
total_duration =  286
failed for  Lion
Lion_ice1.csv
Lion_ice1
failed for  Lion_ice1
Lion_ice2.csv
Lion_ice2
failed for  Lion_ice2
Lion_ice4.csv
Lion_ice4
failed for  Lion_ice4
Lion_ice8.csv
Lion_ice8
failed for  Lion_ice8
Philomena.csv
Philomena
data len =  107
block_len 4
start =  0   end =  4
0   -1.0
1    3.0
2   -1.0
3    3.0
Name: truth_int, dtype: float64
0    54
1    33
2    26
3     4
Name: duration, dtype: int64
3:  37 2:  0 1:  0 0:  0 -1:  80
total_duration =  117
max Id:  -1
start =  4   end =  8
4   -1.0
5   -1.0
6    3.0
7    3.0
Name: truth_int, dtype: float64
4    21
5    32
6    26
7    43
Name: duration, dtype: int64
3:  69 2:  0 1:  0 0:  0 -1:  53
total_duration =  122
max Id:  3
start =  8   end =  12
8    -1.0
9     3.0
10    3.0
11    3.0
Name: truth_int, dtype: float64
8     26
9     34
10    44
11    36
Name: duration, dtype: int64
3:  114 2:  0 1:  0 0:  0 -1:  26
total_duration =  140
max Id:  3
start =  12   end =  16
12    2.0
13    NaN
14    3.0
15    2.0
Name: truth_int, dtype: float64
12    52
13    29
14    82
15    73
Name: duration, dtype: int64
3:  82 2:  125 1:  0 0:  0 -1:  0
total_duration =  236
failed for  Philomena
Philomena_ice1.csv
Philomena_ice1
failed for  Philomena_ice1
Philomena_ice2.csv
Philomena_ice2
failed for  Philomena_ice2
Philomena_ice4.csv
Philomena_ice4
failed for  Philomena_ice4
Philomena_ice8.csv
Philomena_ice8
failed for  Philomena_ice8
Rush.csv
Rush
data len =  107
block_len 4
start =  0   end =  4
0    3
1    2
2    3
3    3
Name: truth_int, dtype: int64
0    115
1     75
2     51
3     59
Name: duration, dtype: int64
3:  225 2:  75 1:  0 0:  0 -1:  0
total_duration =  300
max Id:  3
start =  4   end =  8
4    3
5    0
6    0
7    0
Name: truth_int, dtype: int64
4     22
5     78
6    119
7     67
Name: duration, dtype: int64
3:  22 2:  0 1:  0 0:  264 -1:  0
total_duration =  286
max Id:  0
start =  8   end =  12
8     3
9     3
10    3
11    1
Name: truth_int, dtype: int64
8     63
9     12
10    42
11    77
Name: duration, dtype: int64
3:  117 2:  0 1:  77 0:  0 -1:  0
total_duration =  194
max Id:  3
start =  12   end =  16
12    3
13    3
14    3
15    3
Name: truth_int, dtype: int64
12    41
13    34
14    32
15    42
Name: duration, dtype: int64
3:  149 2:  0 1:  0 0:  0 -1:  0
total_duration =  149
max Id:  3
start =  16   end =  20
16    3
17    1
18    3
19    0
Name: truth_int, dtype: int64
16    43
17    82
18    63
19    83
Name: duration, dtype: int64
3:  106 2:  0 1:  82 0:  83 -1:  0
total_duration =  271
max Id:  3
start =  20   end =  24
20    3
21    3
22    2
23    1
Name: truth_int, dtype: int64
20    84
21    63
22    31
23    38
Name: duration, dtype: int64
3:  147 2:  31 1:  38 0:  0 -1:  0
total_duration =  216
max Id:  3
start =  24   end =  28
24   -1
25    2
26    3
27    3
Name: truth_int, dtype: int64
24     22
25    140
26     31
27     29
Name: duration, dtype: int64
3:  60 2:  140 1:  0 0:  0 -1:  22
total_duration =  222
max Id:  2
start =  28   end =  32
28    3
29    3
30    3
31    2
Name: truth_int, dtype: int64
28    32
29    12
30    69
31    74
Name: duration, dtype: int64
3:  113 2:  74 1:  0 0:  0 -1:  0
total_duration =  187
max Id:  3
start =  32   end =  36
32    0
33    0
34    0
35    0
Name: truth_int, dtype: int64
32     68
33    109
34     72
35     30
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  279 -1:  0
total_duration =  279
max Id:  0
start =  36   end =  40
36    3
37    2
38    3
39    3
Name: truth_int, dtype: int64
36    121
37    144
38     30
39     80
Name: duration, dtype: int64
3:  231 2:  144 1:  0 0:  0 -1:  0
total_duration =  375
max Id:  3
start =  40   end =  44
40    3
41    3
42    3
43    3
Name: truth_int, dtype: int64
40     37
41     27
42    102
43     37
Name: duration, dtype: int64
3:  203 2:  0 1:  0 0:  0 -1:  0
total_duration =  203
max Id:  3
start =  44   end =  48
44    3
45    3
46    3
47    3
Name: truth_int, dtype: int64
44    71
45    24
46    70
47    13
Name: duration, dtype: int64
3:  178 2:  0 1:  0 0:  0 -1:  0
total_duration =  178
max Id:  3

start =  48   end =  52
48    3
49    3
50    3
51    3
Name: truth_int, dtype: int64
48    22
49    93
50    31
51    61
Name: duration, dtype: int64
3:  207 2:  0 1:  0 0:  0 -1:  0
total_duration =  207
max Id:  3
start =  52   end =  56
52    3
53    3
54    3
55    3
Name: truth_int, dtype: int64
52    68
53    32
54    96
55    40
Name: duration, dtype: int64
3:  236 2:  0 1:  0 0:  0 -1:  0
total_duration =  236
max Id:  3
start =  56   end =  60
56    3
57    3
58    3
59    3
Name: truth_int, dtype: int64
56    57
57    43
58    49
59    22
Name: duration, dtype: int64
3:  171 2:  0 1:  0 0:  0 -1:  0
total_duration =  171
max Id:  3
start =  60   end =  64
60    2
61    3
62    1
63    3
Name: truth_int, dtype: int64
60    35
61    33
62    23
63    21
Name: duration, dtype: int64
3:  54 2:  35 1:  23 0:  0 -1:  0
total_duration =  112
max Id:  3
start =  64   end =  68
64    1
65    3
66   -1
67    3
Name: truth_int, dtype: int64
64    70
65    44
66    23
67    21
Name: duration, dtype: int64
3:  65 2:  0 1:  70 0:  0 -1:  23
total_duration =  158
max Id:  1
start =  68   end =  72
68    2
69    3
70    3
71    3
Name: truth_int, dtype: int64
68    162
69    106
70     71
71     82
Name: duration, dtype: int64
3:  259 2:  162 1:  0 0:  0 -1:  0
total_duration =  421
max Id:  3
start =  72   end =  76
72    3
73    3
74    3
75    3
Name: truth_int, dtype: int64
72    146
73     12
74     25
75     44
Name: duration, dtype: int64
3:  227 2:  0 1:  0 0:  0 -1:  0
total_duration =  227
max Id:  3
start =  76   end =  80
76    3
77    3
78    3
79    3
Name: truth_int, dtype: int64
76    24
77    36
78    50
79    95
Name: duration, dtype: int64
3:  205 2:  0 1:  0 0:  0 -1:  0
total_duration =  205
max Id:  3
start =  80   end =  84
80    2
81    3
82    0
83    0
Name: truth_int, dtype: int64
80    71
81    37
82    84
83    43
Name: duration, dtype: int64
3:  37 2:  71 1:  0 0:  127 -1:  0
total_duration =  235
max Id:  0
start =  84   end =  88
84    3
85    3
86    2
87    2
Name: truth_int, dtype: int64
84    115
85    150
86    131
87     66
Name: duration, dtype: int64
3:  265 2:  197 1:  0 0:  0 -1:  0
total_duration =  462
max Id:  3
start =  88   end =  92
88    3
89    3
90    3
91    3
Name: truth_int, dtype: int64
88    45
89    73
90    53
91    40
Name: duration, dtype: int64
3:  211 2:  0 1:  0 0:  0 -1:  0
total_duration =  211
max Id:  3
start =  92   end =  96
92    3
93    3
94    3
95    3
Name: truth_int, dtype: int64
92     70
93     41
94    190
95     34
Name: duration, dtype: int64
3:  335 2:  0 1:  0 0:  0 -1:  0
total_duration =  335
max Id:  3
start =  96   end =  100
96    3
97    3
98    1
99    3
Name: truth_int, dtype: int64
96     32
97     94
98     80
99    135
Name: duration, dtype: int64
3:  261 2:  0 1:  80 0:  0 -1:  0
total_duration =  341
max Id:  3
start =  100   end =  104
100    3
101    3
102    3
103    3
Name: truth_int, dtype: int64
100    36
101    56
102    53
103    58
Name: duration, dtype: int64
3:  203 2:  0 1:  0 0:  0 -1:  0
total_duration =  203
max Id:  3
start =  104   end =  107
104    1
105    1
106    3
Name: truth_int, dtype: int64
104     16
105    249
106     70
Name: duration, dtype: int64
3:  70 2:  0 1:  265 0:  0 -1:  0
total_duration =  335
max Id:  1
data len =  107
block_len 12
start =  0   end =  12
0     3
1     2
2     3
3     3
4     3
5     0
6     0
7     0
8     3
9     3
10    3
11    1
Name: truth_int, dtype: int64
0     115
1      75
2      51
3      59
4      22
5      78
6     119
7      67
8      63
9      12
10     42
11     77
Name: duration, dtype: int64
3:  364 2:  75 1:  77 0:  264 -1:  0
total_duration =  780
max Id:  3
start =  12   end =  24
12    3
13    3
14    3
15    3
16    3
17    1
18    3
19    0
20    3
21    3
22    2
23    1
Name: truth_int, dtype: int64
12    41
13    34
14    32
15    42
16    43
17    82
18    63
19    83
20    84
21    63
22    31
23    38
Name: duration, dtype: int64
3:  402 2:  31 1:  120 0:  83 -1:  0
total_duration =  636
max Id:  3
start =  24   end =  36
24   -1
25    2
26    3
27    3
28    3
29    3
30    3
31    2
32    0
33    0
34    0
35    0
Name: truth_int, dtype: int64
24     22
25    140
26     31
27     29
28     32
29     12
30     69
31     74
32     68
33    109
34     72
35     30
Name: duration, dtype: int64
3:  173 2:  214 1:  0 0:  279 -1:  22
total_duration =  688
max Id:  0
start =  36   end =  48
36    3
37    2
38    3
39    3
40    3
41    3
42    3
43    3
44    3
45    3
46    3
47    3
Name: truth_int, dtype: int64
36    121
37    144
38     30
39     80
40     37
41     27
42    102
43     37
44     71
45     24
46     70
47     13
Name: duration, dtype: int64
3:  612 2:  144 1:  0 0:  0 -1:  0
total_duration =  756
max Id:  3
start =  48   end =  60
48    3
49    3
50    3
51    3
52    3
53    3
54    3
55    3
56    3
57    3
58    3
59    3
Name: truth_int, dtype: int64
48    22
49    93
50    31
51    61
52    68
53    32
54    96
55    40
56    57
57    43
58    49
59    22
Name: duration, dtype: int64
3:  614 2:  0 1:  0 0:  0 -1:  0
total_duration =  614
max Id:  3
start =  60   end =  72
60    2
61    3
62    1
63    3
64    1
65    3
66   -1
67    3
68    2
69    3
70    3
71    3
Name: truth_int, dtype: int64
60     35
61     33
62     23
63     21
64     70
65     44
66     23
67     21
68    162
69    106
70     71
71     82
Name: duration, dtype: int64
3:  378 2:  197 1:  93 0:  0 -1:  23
total_duration =  691
max Id:  3
start =  72   end =  84
72    3
73    3
74    3
75    3
76    3
77    3
78    3
79    3
80    2
81    3
82    0
83    0
Name: truth_int, dtype: int64
72    146
73     12
74     25
75     44
76     24
77     36
78     50
79     95
80     71
81     37
82     84
83     43
Name: duration, dtype: int64
3:  469 2:  71 1:  0 0:  127 -1:  0
total_duration =  667
max Id:  3
start =  84   end =  96
84    3
85    3
86    2
87    2
88    3
89    3
90    3
91    3
92    3
93    3
94    3
95    3
Name: truth_int, dtype: int64
84    115
85    150
86    131
87     66
88     45
89     73
90     53
91     40
92     70
93     41
94    190
95     34
Name: duration, dtype: int64
3:  811 2:  197 1:  0 0:  0 -1:  0
total_duration =  1008
max Id:  3
start =  96   end =  107
96     3
97     3
98     1
99     3
100    3
101    3
102    3
103    3
104    1
105    1
106    3
Name: truth_int, dtype: int64
96      32
97      94
98      80
99     135
100     36
101     56
102     53
103     58
104     16
105    249
106     70
Name: duration, dtype: int64
3:  534 2:  0 1:  345 0:  0 -1:  0
total_duration =  879
max Id:  3
data len =  107
block_len 36
start =  0   end =  36
0     3
1     2
2     3
3     3
4     3
5     0
6     0
7     0
8     3
9     3
10    3
11    1
12    3
13    3
14    3
15    3
16    3
17    1
18    3
19    0
20    3
21    3
22    2
23    1
24   -1
25    2
26    3
27    3
28    3
29    3
30    3
31    2
32    0
33    0
34    0
35    0
Name: truth_int, dtype: int64
0     115
1      75
2      51
3      59
4      22
5      78
6     119
7      67
8      63
9      12
10     42
11     77
12     41
13     34
14     32
15     42
16     43
17     82
18     63
19     83
20     84
21     63
22     31
23     38
24     22
25    140
26     31
27     29
28     32
29     12
30     69
31     74
32     68
33    109
34     72
35     30
Name: duration, dtype: int64
3:  939 2:  320 1:  197 0:  626 -1:  22
total_duration =  2104
max Id:  3
start =  36   end =  72
36    3
37    2
38    3
39    3
40    3
41    3
42    3
43    3
44    3
45    3
46    3
47    3
48    3
49    3
50    3
51    3
52    3
53    3
54    3
55    3
56    3
57    3
58    3
59    3
60    2
61    3
62    1
63    3
64    1
65    3
66   -1
67    3
68    2
69    3
70    3
71    3
Name: truth_int, dtype: int64
36    121
37    144
38     30
39     80
40     37
41     27
42    102
43     37
44     71
45     24
46     70
47     13
48     22
49     93
50     31
51     61
52     68
53     32
54     96
55     40
56     57
57     43
58     49
59     22
60     35
61     33
62     23
63     21
64     70
65     44
66     23
67     21
68    162
69    106
70     71
71     82
Name: duration, dtype: int64
3:  1604 2:  341 1:  93 0:  0 -1:  23
total_duration =  2061
max Id:  3
start =  72   end =  107
72     3
73     3
74     3
75     3
76     3
77     3
78     3
79     3
80     2
81     3
82     0
83     0
84     3
85     3
86     2
87     2
88     3
89     3
90     3
91     3
92     3
93     3
94     3
95     3
96     3
97     3
98     1
99     3
100    3
101    3
102    3
103    3
104    1
105    1
106    3
Name: truth_int, dtype: int64
72     146
73      12
74      25
75      44
76      24
77      36
78      50
79      95
80      71
81      37
82      84
83      43
84     115
85     150
86     131
87      66
88      45
89      73
90      53
91      40
92      70
93      41
94     190
95      34
96      32
97      94
98      80
99     135
100     36
101     56
102     53
103     58
104     16
105    249
106     70
Name: duration, dtype: int64
3:  1814 2:  268 1:  345 0:  127 -1:  0
total_duration =  2554
max Id:  3
data len =  107
block_len 107
start =  0   end =  107
0      3
1      2
2      3
3      3
4      3
5      0
6      0
7      0
8      3
9      3
10     3
11     1
12     3
13     3
14     3
15     3
16     3
17     1
18     3
19     0
20     3
21     3
22     2
23     1
24    -1
25     2
26     3
27     3
28     3
29     3
      ..
77     3
78     3
79     3
80     2
81     3
82     0
83     0
84     3
85     3
86     2
87     2
88     3
89     3
90     3
91     3
92     3
93     3
94     3
95     3
96     3
97     3
98     1
99     3
100    3
101    3
102    3
103    3
104    1
105    1
106    3
Name: truth_int, Length: 107, dtype: int64
0      115
1       75
2       51
3       59
4       22
5       78
6      119
7       67
8       63
9       12
10      42
11      77
12      41
13      34
14      32
15      42
16      43
17      82
18      63
19      83
20      84
21      63
22      31
23      38
24      22
25     140
26      31
27      29
28      32
29      12
      ...
77      36
78      50
79      95
80      71
81      37
82      84
83      43
84     115
85     150
86     131
87      66
88      45
89      73
90      53
91      40
92      70
93      41
94     190
95      34
96      32
97      94
98      80
99     135
100     36
101     56
102     53
103     58
104     16
105    249
106     70
Name: duration, Length: 107, dtype: int64
3:  4357 2:  929 1:  635 0:  753 -1:  45
total_duration =  6719
max Id:  3
Rush_ice1.csv
Rush_ice1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    6719
Name: duration, dtype: int64
3:  6719 2:  0 1:  0 0:  0 -1:  0
total_duration =  6719
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  9   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  10   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  11   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  12   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)

3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  13   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  14   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  15   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  16   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  17   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  18   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  19   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  20   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  21   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  22   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  23   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  24   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  25   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    6719
Name: duration, dtype: int64
3:  6719 2:  0 1:  0 0:  0 -1:  0
total_duration =  6719
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    6719
Name: duration, dtype: int64
3:  6719 2:  0 1:  0 0:  0 -1:  0
total_duration =  6719
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    6719
Name: duration, dtype: int64
3:  6719 2:  0 1:  0 0:  0 -1:  0
total_duration =  6719
max Id:  3
Rush_ice2.csv
Rush_ice2
failed for  Rush_ice2
Rush_ice4.csv
Rush_ice4
failed for  Rush_ice4
Rush_ice8.csv
Rush_ice8
failed for  Rush_ice8
Selma.csv
Selma
data len =  76
block_len 3
start =  0   end =  3
0    3
1    3
2    3
Name: truth_int, dtype: int64
0    133
1     39
2    126
Name: duration, dtype: int64
3:  298 2:  0 1:  0 0:  0 -1:  0
total_duration =  298
max Id:  3
start =  3   end =  6
3    3
4    2
5    2
Name: truth_int, dtype: int64
3    180
4     28
5    242
Name: duration, dtype: int64
3:  180 2:  270 1:  0 0:  0 -1:  0
total_duration =  450
max Id:  2
start =  6   end =  9
6    3
7    3
8    3
Name: truth_int, dtype: int64
6    67
7    30
8    65
Name: duration, dtype: int64
3:  162 2:  0 1:  0 0:  0 -1:  0
total_duration =  162
max Id:  3
start =  9   end =  12
9     3
10    3
11    3
Name: truth_int, dtype: int64
9      86
10    163
11    129
Name: duration, dtype: int64
3:  378 2:  0 1:  0 0:  0 -1:  0
total_duration =  378
max Id:  3
start =  12   end =  15
12    3
13    3
14    3
Name: truth_int, dtype: int64
12    40
13    83
14    83
Name: duration, dtype: int64
3:  206 2:  0 1:  0 0:  0 -1:  0
total_duration =  206
max Id:  3
start =  15   end =  18
15    3
16   -1
17    3
Name: truth_int, dtype: int64
15    175
16     27
17    210
Name: duration, dtype: int64
3:  385 2:  0 1:  0 0:  0 -1:  27
total_duration =  412
max Id:  3
start =  18   end =  21
18    3
19    3
20    2
Name: truth_int, dtype: int64
18    95
19    49
20    74
Name: duration, dtype: int64
3:  144 2:  74 1:  0 0:  0 -1:  0
total_duration =  218
max Id:  3
start =  21   end =  24
21    3
22    3
23    2
Name: truth_int, dtype: int64
21     14
22     41
23    199
Name: duration, dtype: int64
3:  55 2:  199 1:  0 0:  0 -1:  0
total_duration =  254
max Id:  2
start =  24   end =  27
24    3
25    3
26    3
Name: truth_int, dtype: int64
24    22
25    89
26    73
Name: duration, dtype: int64
3:  184 2:  0 1:  0 0:  0 -1:  0
total_duration =  184
max Id:  3
start =  27   end =  30
27    2
28    3
29    3
Name: truth_int, dtype: int64
27    114
28    105
29     61
Name: duration, dtype: int64
3:  166 2:  114 1:  0 0:  0 -1:  0
total_duration =  280
max Id:  3
start =  30   end =  33
30    2
31    3
32    3
Name: truth_int, dtype: int64
30    107
31    184
32    201
Name: duration, dtype: int64
3:  385 2:  107 1:  0 0:  0 -1:  0
total_duration =  492
max Id:  3
start =  33   end =  36
33    3
34    2
35   -1
Name: truth_int, dtype: int64
33    122
34     64
35     55
Name: duration, dtype: int64
3:  122 2:  64 1:  0 0:  0 -1:  55
total_duration =  241
max Id:  3
start =  36   end =  39
36    2
37    2
38    3
Name: truth_int, dtype: int64
36     15
37     17
38    285
Name: duration, dtype: int64
3:  285 2:  32 1:  0 0:  0 -1:  0
total_duration =  317
max Id:  3
start =  39   end =  42
39   -1
40    3
41    3
Name: truth_int, dtype: int64
39    126
40     51
41    114
Name: duration, dtype: int64
3:  165 2:  0 1:  0 0:  0 -1:  126
total_duration =  291
max Id:  3
start =  42   end =  45
42    3
43    3
44    2
Name: truth_int, dtype: int64
42    102
43     64
44     16
Name: duration, dtype: int64
3:  166 2:  16 1:  0 0:  0 -1:  0
total_duration =  182
max Id:  3
start =  45   end =  48
45    3
46    2
47    3
Name: truth_int, dtype: int64
45    89
46    14
47    10
Name: duration, dtype: int64
3:  99 2:  14 1:  0 0:  0 -1:  0
total_duration =  113
max Id:  3
start =  48   end =  51
48    3
49   -1
50    3
Name: truth_int, dtype: int64
48    101
49     38
50     43
Name: duration, dtype: int64
3:  144 2:  0 1:  0 0:  0 -1:  38
total_duration =  182
max Id:  3
start =  51   end =  54
51    2
52    3
53    3
Name: truth_int, dtype: int64
51    51
52    26
53    52
Name: duration, dtype: int64
3:  78 2:  51 1:  0 0:  0 -1:  0
total_duration =  129
max Id:  3
start =  54   end =  57
54    3
55    3
56   -1
Name: truth_int, dtype: int64
54    17
55    30
56    76
Name: duration, dtype: int64
3:  47 2:  0 1:  0 0:  0 -1:  76
total_duration =  123
max Id:  -1
start =  57   end =  60
57    3
58    3
59    3
Name: truth_int, dtype: int64
57    91
58    48
59    39
Name: duration, dtype: int64
3:  178 2:  0 1:  0 0:  0 -1:  0
total_duration =  178
max Id:  3
start =  60   end =  63
60    3
61    3
62    3
Name: truth_int, dtype: int64
60    186
61     58
62    104
Name: duration, dtype: int64
3:  348 2:  0 1:  0 0:  0 -1:  0
total_duration =  348
max Id:  3

start =  63   end =  66
63    3
64    2
65    3
Name: truth_int, dtype: int64
63    122
64    124
65    113
Name: duration, dtype: int64
3:  235 2:  124 1:  0 0:  0 -1:  0
total_duration =  359
max Id:  3
start =  66   end =  69
66   -1
67    3
68    3
Name: truth_int, dtype: int64
66    261
67     69
68    138
Name: duration, dtype: int64
3:  207 2:  0 1:  0 0:  0 -1:  261
total_duration =  468
max Id:  -1
start =  69   end =  72
69    3
70    3
71    3
Name: truth_int, dtype: int64
69     39
70     20
71    160
Name: duration, dtype: int64
3:  219 2:  0 1:  0 0:  0 -1:  0
total_duration =  219
max Id:  3
start =  72   end =  75
72    3
73    3
74    3
Name: truth_int, dtype: int64
72    131
73    147
74    149
Name: duration, dtype: int64
3:  427 2:  0 1:  0 0:  0 -1:  0
total_duration =  427
max Id:  3
start =  75   end =  76
75    3
Name: truth_int, dtype: int64
75    230
Name: duration, dtype: int64
3:  230 2:  0 1:  0 0:  0 -1:  0
total_duration =  230
max Id:  3
start =  78   end =  76
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  76
block_len 9
start =  0   end =  9
0    3
1    3
2    3
3    3
4    2
5    2
6    3
7    3
8    3
Name: truth_int, dtype: int64
0    133
1     39
2    126
3    180
4     28
5    242
6     67
7     30
8     65
Name: duration, dtype: int64
3:  640 2:  270 1:  0 0:  0 -1:  0
total_duration =  910
max Id:  3
start =  9   end =  18
9     3
10    3
11    3
12    3
13    3
14    3
15    3
16   -1
17    3
Name: truth_int, dtype: int64
9      86
10    163
11    129
12     40
13     83
14     83
15    175
16     27
17    210
Name: duration, dtype: int64
3:  969 2:  0 1:  0 0:  0 -1:  27
total_duration =  996
max Id:  3
start =  18   end =  27
18    3
19    3
20    2
21    3
22    3
23    2
24    3
25    3
26    3
Name: truth_int, dtype: int64
18     95
19     49
20     74
21     14
22     41
23    199
24     22
25     89
26     73
Name: duration, dtype: int64
3:  383 2:  273 1:  0 0:  0 -1:  0
total_duration =  656
max Id:  3
start =  27   end =  36
27    2
28    3
29    3
30    2
31    3
32    3
33    3
34    2
35   -1
Name: truth_int, dtype: int64
27    114
28    105
29     61
30    107
31    184
32    201
33    122
34     64
35     55
Name: duration, dtype: int64
3:  673 2:  285 1:  0 0:  0 -1:  55
total_duration =  1013
max Id:  3
start =  36   end =  45
36    2
37    2
38    3
39   -1
40    3
41    3
42    3
43    3
44    2
Name: truth_int, dtype: int64
36     15
37     17
38    285
39    126
40     51
41    114
42    102
43     64
44     16
Name: duration, dtype: int64
3:  616 2:  48 1:  0 0:  0 -1:  126
total_duration =  790
max Id:  3
start =  45   end =  54
45    3
46    2
47    3
48    3
49   -1
50    3
51    2
52    3
53    3
Name: truth_int, dtype: int64
45     89
46     14
47     10
48    101
49     38
50     43
51     51
52     26
53     52
Name: duration, dtype: int64
3:  321 2:  65 1:  0 0:  0 -1:  38
total_duration =  424
max Id:  3
start =  54   end =  63
54    3
55    3
56   -1
57    3
58    3
59    3
60    3
61    3
62    3
Name: truth_int, dtype: int64
54     17
55     30
56     76
57     91
58     48
59     39
60    186
61     58
62    104
Name: duration, dtype: int64
3:  573 2:  0 1:  0 0:  0 -1:  76
total_duration =  649
max Id:  3
start =  63   end =  72
63    3
64    2
65    3
66   -1
67    3
68    3
69    3
70    3
71    3
Name: truth_int, dtype: int64
63    122
64    124
65    113
66    261
67     69
68    138
69     39
70     20
71    160
Name: duration, dtype: int64
3:  661 2:  124 1:  0 0:  0 -1:  261
total_duration =  1046
max Id:  3
start =  72   end =  76
72    3
73    3
74    3
75    3
Name: truth_int, dtype: int64
72    131
73    147
74    149
75    230
Name: duration, dtype: int64
3:  657 2:  0 1:  0 0:  0 -1:  0
total_duration =  657
max Id:  3
data len =  76
block_len 26
start =  0   end =  26
0     3
1     3
2     3
3     3
4     2
5     2
6     3
7     3
8     3
9     3
10    3
11    3
12    3
13    3
14    3
15    3
16   -1
17    3
18    3
19    3
20    2
21    3
22    3
23    2
24    3
25    3
Name: truth_int, dtype: int64
0     133
1      39
2     126
3     180
4      28
5     242
6      67
7      30
8      65
9      86
10    163
11    129
12     40
13     83
14     83
15    175
16     27
17    210
18     95
19     49
20     74
21     14
22     41
23    199
24     22
25     89
Name: duration, dtype: int64
3:  1919 2:  543 1:  0 0:  0 -1:  27
total_duration =  2489
max Id:  3
start =  26   end =  52
26    3
27    2
28    3
29    3
30    2
31    3
32    3
33    3
34    2
35   -1
36    2
37    2
38    3
39   -1
40    3
41    3
42    3
43    3
44    2
45    3
46    2
47    3
48    3
49   -1
50    3
51    2
Name: truth_int, dtype: int64
26     73
27    114
28    105
29     61
30    107
31    184
32    201
33    122
34     64
35     55
36     15
37     17
38    285
39    126
40     51
41    114
42    102
43     64
44     16
45     89
46     14
47     10
48    101
49     38
50     43
51     51
Name: duration, dtype: int64
3:  1605 2:  398 1:  0 0:  0 -1:  219
total_duration =  2222
max Id:  3
start =  52   end =  76
52    3
53    3
54    3
55    3
56   -1
57    3
58    3
59    3
60    3
61    3
62    3
63    3
64    2
65    3
66   -1
67    3
68    3
69    3
70    3
71    3
72    3
73    3
74    3
75    3
Name: truth_int, dtype: int64
52     26
53     52
54     17
55     30
56     76
57     91
58     48
59     39
60    186
61     58
62    104
63    122
64    124
65    113
66    261
67     69
68    138
69     39
70     20
71    160
72    131
73    147
74    149
75    230
Name: duration, dtype: int64
3:  1969 2:  124 1:  0 0:  0 -1:  337
total_duration =  2430
max Id:  3
data len =  76
block_len 76
start =  0   end =  76
0     3
1     3
2     3
3     3
4     2
5     2
6     3
7     3
8     3
9     3
10    3
11    3
12    3
13    3
14    3
15    3
16   -1
17    3
18    3
19    3
20    2
21    3
22    3
23    2
24    3
25    3
26    3
27    2
28    3
29    3
     ..
46    2
47    3
48    3
49   -1
50    3
51    2
52    3
53    3
54    3
55    3
56   -1
57    3
58    3
59    3
60    3
61    3
62    3
63    3
64    2
65    3
66   -1
67    3
68    3
69    3
70    3
71    3
72    3
73    3
74    3
75    3
Name: truth_int, Length: 76, dtype: int64
0     133
1      39
2     126
3     180
4      28
5     242
6      67
7      30
8      65
9      86
10    163
11    129
12     40
13     83
14     83
15    175
16     27
17    210
18     95
19     49
20     74
21     14
22     41
23    199
24     22
25     89
26     73
27    114
28    105
29     61
     ...
46     14
47     10
48    101
49     38
50     43
51     51
52     26
53     52
54     17
55     30
56     76
57     91
58     48
59     39
60    186
61     58
62    104
63    122
64    124
65    113
66    261
67     69
68    138
69     39
70     20
71    160
72    131
73    147
74    149
75    230
Name: duration, Length: 76, dtype: int64
3:  5493 2:  1065 1:  0 0:  0 -1:  583
total_duration =  7141
max Id:  3
Selma_ice1.csv
Selma_ice1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7141
Name: duration, dtype: int64
3:  7141 2:  0 1:  0 0:  0 -1:  0
total_duration =  7141
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  9   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  10   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  11   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  12   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  13   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  14   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  15   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  16   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  17   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  18   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  19   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  20   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  21   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  22   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  23   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  24   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  25   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1

data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7141
Name: duration, dtype: int64
3:  7141 2:  0 1:  0 0:  0 -1:  0
total_duration =  7141
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7141
Name: duration, dtype: int64
3:  7141 2:  0 1:  0 0:  0 -1:  0
total_duration =  7141
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7141
Name: duration, dtype: int64
3:  7141 2:  0 1:  0 0:  0 -1:  0
total_duration =  7141
max Id:  3
Selma_ice2.csv
Selma_ice2
failed for  Selma_ice2
Selma_ice4.csv
Selma_ice4
failed for  Selma_ice4
Selma_ice8.csv
Selma_ice8
failed for  Selma_ice8
Spotlight.csv
Spotlight
data len =  126
block_len 5
start =  0   end =  5
0    2
1    2
2    2
3    2
4    3
Name: truth_int, dtype: int64
0     62
1     23
2     30
3     79
4    104
Name: duration, dtype: int64
3:  104 2:  194 1:  0 0:  0 -1:  0
total_duration =  298
max Id:  2
start =  5   end =  10
5    0
6    3
7    1
8    3
9    3
Name: truth_int, dtype: int64
5    141
6     36
7     33
8     22
9     98
Name: duration, dtype: int64
3:  156 2:  0 1:  33 0:  141 -1:  0
total_duration =  330
max Id:  3
start =  10   end =  15
10    3
11    3
12    3
13    3
14    3
Name: truth_int, dtype: int64
10    45
11    75
12    61
13    34
14    26
Name: duration, dtype: int64
3:  241 2:  0 1:  0 0:  0 -1:  0
total_duration =  241
max Id:  3
start =  15   end =  20
15    1
16    3
17    3
18    3
19    3
Name: truth_int, dtype: int64
15      2
16     66
17     38
18    132
19    142
Name: duration, dtype: int64
3:  378 2:  0 1:  2 0:  0 -1:  0
total_duration =  380
max Id:  3
start =  20   end =  25
20    3
21    0
22    3
23    1
24    3
Name: truth_int, dtype: int64
20     57
21     72
22     89
23    100
24     36
Name: duration, dtype: int64
3:  182 2:  0 1:  100 0:  72 -1:  0
total_duration =  354
max Id:  3
start =  25   end =  30
25    3
26    1
27    2
28    3
29    3
Name: truth_int, dtype: int64
25     84
26    121
27     15
28      9
29    227
Name: duration, dtype: int64
3:  320 2:  15 1:  121 0:  0 -1:  0
total_duration =  456
max Id:  3
start =  30   end =  35
30    3
31    3
32    3
33    3
34    3
Name: truth_int, dtype: int64
30     28
31     64
32     45
33     83
34    118
Name: duration, dtype: int64
3:  338 2:  0 1:  0 0:  0 -1:  0
total_duration =  338
max Id:  3
start =  35   end =  40
35    3
36    3
37    3
38    3
39    3
Name: truth_int, dtype: int64
35    99
36    81
37    30
38    70
39    20
Name: duration, dtype: int64
3:  300 2:  0 1:  0 0:  0 -1:  0
total_duration =  300
max Id:  3
start =  40   end =  45
40    3
41    3
42    3
43    3
44    3
Name: truth_int, dtype: int64
40    25
41    57
42    68
43    28
44    15
Name: duration, dtype: int64
3:  193 2:  0 1:  0 0:  0 -1:  0
total_duration =  193
max Id:  3
start =  45   end =  50
45    3
46    3
47    3
48    3
49    3
Name: truth_int, dtype: int64
45     43
46     62
47     23
48    121
49     63
Name: duration, dtype: int64
3:  312 2:  0 1:  0 0:  0 -1:  0
total_duration =  312
max Id:  3
start =  50   end =  55
50    0
51    3
52    3
53    1
54    3
Name: truth_int, dtype: int64
50     37
51     70
52    110
53     95
54     28
Name: duration, dtype: int64
3:  208 2:  0 1:  95 0:  37 -1:  0
total_duration =  340
max Id:  3
start =  55   end =  60
55    3
56    3
57    3
58    3
59    1
Name: truth_int, dtype: int64
55    117
56     52
57     27
58     61
59     16
Name: duration, dtype: int64
3:  257 2:  0 1:  16 0:  0 -1:  0
total_duration =  273
max Id:  3
start =  60   end =  65
60    1
61    1
62    3
63    1
64    1
Name: truth_int, dtype: int64
60    44
61     8
62    28
63    41
64     9
Name: duration, dtype: int64
3:  28 2:  0 1:  102 0:  0 -1:  0
total_duration =  130
max Id:  1
start =  65   end =  70
65    1
66    3
67    3
68    2
69    3
Name: truth_int, dtype: int64
65     87
66     46
67     72
68     35
69    102
Name: duration, dtype: int64
3:  220 2:  35 1:  87 0:  0 -1:  0
total_duration =  342
max Id:  3
start =  70   end =  75
70    0
71    3
72    2
73    0
74    2
Name: truth_int, dtype: int64
70     42
71    107
72     71
73     35
74     48
Name: duration, dtype: int64
3:  107 2:  119 1:  0 0:  77 -1:  0
total_duration =  303
max Id:  2
start =  75   end =  80
75    3
76    3
77    3
78    3
79    3
Name: truth_int, dtype: int64
75     39
76     33
77    212
78     22
79     52
Name: duration, dtype: int64
3:  358 2:  0 1:  0 0:  0 -1:  0
total_duration =  358
max Id:  3
start =  80   end =  85
80    3
81    3
82    1
83    2
84    1
Name: truth_int, dtype: int64
80    90
81    17
82    36
83    69
84    34
Name: duration, dtype: int64
3:  107 2:  69 1:  70 0:  0 -1:  0
total_duration =  246
max Id:  3
start =  85   end =  90
85    1
86    1
87    3
88    0
89    0
Name: truth_int, dtype: int64
85    56
86    22
87    70
88    17
89     9
Name: duration, dtype: int64
3:  70 2:  0 1:  78 0:  26 -1:  0
total_duration =  174
max Id:  1
start =  90   end =  95
90    0
91    2
92    2
93    3
94    0
Name: truth_int, dtype: int64
90     34
91    136
92     24
93     44
94     27
Name: duration, dtype: int64
3:  44 2:  160 1:  0 0:  61 -1:  0
total_duration =  265
max Id:  2
start =  95   end =  100
95    3
96    3
97    2
98    3
99    3
Name: truth_int, dtype: int64
95     77
96     32
97     96
98     27
99    107
Name: duration, dtype: int64
3:  243 2:  96 1:  0 0:  0 -1:  0
total_duration =  339
max Id:  3
start =  100   end =  105
100    0
101    3
102    3
103    3
104    3
Name: truth_int, dtype: int64
100    138
101     35
102     64
103    101
104     78
Name: duration, dtype: int64
3:  278 2:  0 1:  0 0:  138 -1:  0
total_duration =  416
max Id:  3
start =  105   end =  110
105    3
106    1
107    1
108    3
109    3
Name: truth_int, dtype: int64
105     15
106    100
107     93
108     51
109     24
Name: duration, dtype: int64
3:  90 2:  0 1:  193 0:  0 -1:  0
total_duration =  283
max Id:  1
start =  110   end =  115
110    2
111    2
112    3
113    3
114    3
Name: truth_int, dtype: int64
110     49
111    130
112     38
113      8
114     22
Name: duration, dtype: int64
3:  68 2:  179 1:  0 0:  0 -1:  0
total_duration =  247
max Id:  2
start =  115   end =  120
115    3
116    0
117    1
118    1
119    3
Name: truth_int, dtype: int64
115    61
116    19
117    17
118    46
119    26
Name: duration, dtype: int64
3:  87 2:  0 1:  63 0:  19 -1:  0
total_duration =  169
max Id:  3
start =  120   end =  125
120    3
121    3
122    3
123    3
124    3
Name: truth_int, dtype: int64
120    40
121    47
122     9
123    10
124    10
Name: duration, dtype: int64
3:  116 2:  0 1:  0 0:  0 -1:  0
total_duration =  116
max Id:  3
start =  125   end =  126
125    3
Name: truth_int, dtype: int64
125    26
Name: duration, dtype: int64
3:  26 2:  0 1:  0 0:  0 -1:  0
total_duration =  26
max Id:  3
start =  130   end =  126
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  126
block_len 14
start =  0   end =  14
0     2
1     2
2     2
3     2
4     3
5     0
6     3
7     1
8     3
9     3
10    3
11    3
12    3
13    3
Name: truth_int, dtype: int64
0      62
1      23
2      30
3      79
4     104
5     141
6      36
7      33
8      22
9      98
10     45
11     75
12     61
13     34
Name: duration, dtype: int64
3:  475 2:  194 1:  33 0:  141 -1:  0
total_duration =  843
max Id:  3
start =  14   end =  28
14    3
15    1
16    3
17    3
18    3
19    3
20    3
21    0
22    3
23    1
24    3
25    3
26    1
27    2
Name: truth_int, dtype: int64
14     26
15      2
16     66
17     38
18    132
19    142
20     57
21     72
22     89
23    100
24     36
25     84
26    121
27     15
Name: duration, dtype: int64
3:  670 2:  15 1:  223 0:  72 -1:  0
total_duration =  980
max Id:  3
start =  28   end =  42
28    3
29    3
30    3
31    3
32    3
33    3
34    3
35    3
36    3
37    3
38    3
39    3
40    3
41    3
Name: truth_int, dtype: int64
28      9
29    227
30     28
31     64
32     45
33     83
34    118
35     99
36     81
37     30
38     70
39     20
40     25
41     57
Name: duration, dtype: int64
3:  956 2:  0 1:  0 0:  0 -1:  0
total_duration =  956
max Id:  3
start =  42   end =  56
42    3
43    3
44    3
45    3
46    3
47    3
48    3
49    3
50    0
51    3
52    3
53    1
54    3
55    3
Name: truth_int, dtype: int64
42     68
43     28
44     15
45     43
46     62
47     23
48    121
49     63
50     37
51     70
52    110
53     95
54     28
55    117
Name: duration, dtype: int64
3:  748 2:  0 1:  95 0:  37 -1:  0
total_duration =  880
max Id:  3
start =  56   end =  70
56    3
57    3
58    3
59    1
60    1
61    1
62    3
63    1
64    1
65    1
66    3
67    3
68    2
69    3
Name: truth_int, dtype: int64
56     52
57     27
58     61
59     16
60     44
61      8
62     28
63     41
64      9
65     87
66     46
67     72
68     35
69    102
Name: duration, dtype: int64
3:  388 2:  35 1:  205 0:  0 -1:  0
total_duration =  628
max Id:  3
start =  70   end =  84
70    0
71    3
72    2
73    0
74    2
75    3
76    3
77    3
78    3
79    3
80    3
81    3
82    1
83    2
Name: truth_int, dtype: int64
70     42
71    107
72     71
73     35
74     48
75     39
76     33
77    212
78     22
79     52
80     90
81     17
82     36
83     69
Name: duration, dtype: int64
3:  572 2:  188 1:  36 0:  77 -1:  0
total_duration =  873
max Id:  3
start =  84   end =  98
84    1
85    1
86    1
87    3
88    0
89    0
90    0
91    2
92    2
93    3
94    0
95    3
96    3
97    2
Name: truth_int, dtype: int64
84     34
85     56
86     22
87     70
88     17
89      9
90     34
91    136
92     24
93     44
94     27
95     77
96     32
97     96
Name: duration, dtype: int64
3:  223 2:  256 1:  112 0:  87 -1:  0
total_duration =  678
max Id:  2
start =  98   end =  112
98     3
99     3
100    0
101    3
102    3
103    3
104    3
105    3
106    1
107    1
108    3
109    3
110    2
111    2
Name: truth_int, dtype: int64
98      27
99     107
100    138
101     35
102     64
103    101
104     78
105     15
106    100
107     93
108     51
109     24
110     49
111    130
Name: duration, dtype: int64
3:  502 2:  179 1:  193 0:  138 -1:  0
total_duration =  1012
max Id:  3
start =  112   end =  126
112    3
113    3
114    3
115    3
116    0
117    1
118    1
119    3
120    3
121    3
122    3
123    3
124    3
125    3
Name: truth_int, dtype: int64
112    38
113     8
114    22
115    61
116    19
117    17
118    46
119    26
120    40
121    47
122     9
123    10
124    10
125    26
Name: duration, dtype: int64
3:  297 2:  0 1:  63 0:  19 -1:  0
total_duration =  379
max Id:  3

data len =  126
block_len 42
start =  0   end =  42
0     2
1     2
2     2
3     2
4     3
5     0
6     3
7     1
8     3
9     3
10    3
11    3
12    3
13    3
14    3
15    1
16    3
17    3
18    3
19    3
20    3
21    0
22    3
23    1
24    3
25    3
26    1
27    2
28    3
29    3
30    3
31    3
32    3
33    3
34    3
35    3
36    3
37    3
38    3
39    3
40    3
41    3
Name: truth_int, dtype: int64
0      62
1      23
2      30
3      79
4     104
5     141
6      36
7      33
8      22
9      98
10     45
11     75
12     61
13     34
14     26
15      2
16     66
17     38
18    132
19    142
20     57
21     72
22     89
23    100
24     36
25     84
26    121
27     15
28      9
29    227
30     28
31     64
32     45
33     83
34    118
35     99
36     81
37     30
38     70
39     20
40     25
41     57
Name: duration, dtype: int64
3:  2101 2:  209 1:  256 0:  213 -1:  0
total_duration =  2779
max Id:  3
start =  42   end =  84
42    3
43    3
44    3
45    3
46    3
47    3
48    3
49    3
50    0
51    3
52    3
53    1
54    3
55    3
56    3
57    3
58    3
59    1
60    1
61    1
62    3
63    1
64    1
65    1
66    3
67    3
68    2
69    3
70    0
71    3
72    2
73    0
74    2
75    3
76    3
77    3
78    3
79    3
80    3
81    3
82    1
83    2
Name: truth_int, dtype: int64
42     68
43     28
44     15
45     43
46     62
47     23
48    121
49     63
50     37
51     70
52    110
53     95
54     28
55    117
56     52
57     27
58     61
59     16
60     44
61      8
62     28
63     41
64      9
65     87
66     46
67     72
68     35
69    102
70     42
71    107
72     71
73     35
74     48
75     39
76     33
77    212
78     22
79     52
80     90
81     17
82     36
83     69
Name: duration, dtype: int64
3:  1708 2:  223 1:  336 0:  114 -1:  0
total_duration =  2381
max Id:  3
start =  84   end =  126
84     1
85     1
86     1
87     3
88     0
89     0
90     0
91     2
92     2
93     3
94     0
95     3
96     3
97     2
98     3
99     3
100    0
101    3
102    3
103    3
104    3
105    3
106    1
107    1
108    3
109    3
110    2
111    2
112    3
113    3
114    3
115    3
116    0
117    1
118    1
119    3
120    3
121    3
122    3
123    3
124    3
125    3
Name: truth_int, dtype: int64
84      34
85      56
86      22
87      70
88      17
89       9
90      34
91     136
92      24
93      44
94      27
95      77
96      32
97      96
98      27
99     107
100    138
101     35
102     64
103    101
104     78
105     15
106    100
107     93
108     51
109     24
110     49
111    130
112     38
113      8
114     22
115     61
116     19
117     17
118     46
119     26
120     40
121     47
122      9
123     10
124     10
125     26
Name: duration, dtype: int64
3:  1022 2:  435 1:  368 0:  244 -1:  0
total_duration =  2069
max Id:  3
data len =  126
block_len 126
start =  0   end =  126
0      2
1      2
2      2
3      2
4      3
5      0
6      3
7      1
8      3
9      3
10     3
11     3
12     3
13     3
14     3
15     1
16     3
17     3
18     3
19     3
20     3
21     0
22     3
23     1
24     3
25     3
26     1
27     2
28     3
29     3
      ..
96     3
97     2
98     3
99     3
100    0
101    3
102    3
103    3
104    3
105    3
106    1
107    1
108    3
109    3
110    2
111    2
112    3
113    3
114    3
115    3
116    0
117    1
118    1
119    3
120    3
121    3
122    3
123    3
124    3
125    3
Name: truth_int, Length: 126, dtype: int64
0       62
1       23
2       30
3       79
4      104
5      141
6       36
7       33
8       22
9       98
10      45
11      75
12      61
13      34
14      26
15       2
16      66
17      38
18     132
19     142
20      57
21      72
22      89
23     100
24      36
25      84
26     121
27      15
28       9
29     227
      ...
96      32
97      96
98      27
99     107
100    138
101     35
102     64
103    101
104     78
105     15
106    100
107     93
108     51
109     24
110     49
111    130
112     38
113      8
114     22
115     61
116     19
117     17
118     46
119     26
120     40
121     47
122      9
123     10
124     10
125     26
Name: duration, Length: 126, dtype: int64
3:  4831 2:  867 1:  960 0:  571 -1:  0
total_duration =  7229
max Id:  3
Spotlight_ice1.csv
Spotlight_ice1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7229
Name: duration, dtype: int64
3:  7229 2:  0 1:  0 0:  0 -1:  0
total_duration =  7229
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  9   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  10   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  11   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  12   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  13   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  14   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  15   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  16   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  17   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  18   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  19   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  20   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  21   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  22   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  23   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  24   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  25   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7229
Name: duration, dtype: int64
3:  7229 2:  0 1:  0 0:  0 -1:  0
total_duration =  7229
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7229
Name: duration, dtype: int64
3:  7229 2:  0 1:  0 0:  0 -1:  0
total_duration =  7229
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1

data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7229
Name: duration, dtype: int64
3:  7229 2:  0 1:  0 0:  0 -1:  0
total_duration =  7229
max Id:  3
Spotlight_ice2.csv
Spotlight_ice2
failed for  Spotlight_ice2
Spotlight_ice4.csv
Spotlight_ice4
failed for  Spotlight_ice4
Spotlight_ice8.csv
Spotlight_ice8
failed for  Spotlight_ice8
TheBigShort.csv
TheBigShort
data len =  93
block_len 4
start =  0   end =  4
0    3
1    3
2    3
3    3
Name: truth_int, dtype: int64
0    27
1    65
2    43
3    14
Name: duration, dtype: int64
3:  149 2:  0 1:  0 0:  0 -1:  0
total_duration =  149
max Id:  3
start =  4   end =  8
4    3
5    3
6    3
7    2
Name: truth_int, dtype: int64
4     28
5     60
6     52
7    130
Name: duration, dtype: int64
3:  140 2:  130 1:  0 0:  0 -1:  0
total_duration =  270
max Id:  3
start =  8   end =  12
8     2
9     3
10    3
11    3
Name: truth_int, dtype: int64
8      97
9     110
10     55
11     97
Name: duration, dtype: int64
3:  262 2:  97 1:  0 0:  0 -1:  0
total_duration =  359
max Id:  3
start =  12   end =  16
12    3
13    3
14    3
15    1
Name: truth_int, dtype: int64
12     67
13     54
14     69
15    122
Name: duration, dtype: int64
3:  190 2:  0 1:  122 0:  0 -1:  0
total_duration =  312
max Id:  3
start =  16   end =  20
16    3
17    3
18    3
19    3
Name: truth_int, dtype: int64
16    203
17     16
18     50
19     58
Name: duration, dtype: int64
3:  327 2:  0 1:  0 0:  0 -1:  0
total_duration =  327
max Id:  3
start =  20   end =  24
20    3
21    0
22    2
23    3
Name: truth_int, dtype: int64
20     88
21     22
22    149
23    319
Name: duration, dtype: int64
3:  407 2:  149 1:  0 0:  22 -1:  0
total_duration =  578
max Id:  3
start =  24   end =  28
24    3
25    3
26    3
27    3
Name: truth_int, dtype: int64
24     45
25     67
26     84
27    133
Name: duration, dtype: int64
3:  329 2:  0 1:  0 0:  0 -1:  0
total_duration =  329
max Id:  3
start =  28   end =  32
28    3
29    3
30    3
31    2
Name: truth_int, dtype: int64
28     71
29     50
30     69
31    179
Name: duration, dtype: int64
3:  190 2:  179 1:  0 0:  0 -1:  0
total_duration =  369
max Id:  3
start =  32   end =  36
32    3
33    1
34    1
35    0
Name: truth_int, dtype: int64
32    230
33     62
34    166
35     80
Name: duration, dtype: int64
3:  230 2:  0 1:  228 0:  80 -1:  0
total_duration =  538
max Id:  3
start =  36   end =  40
36    3
37    3
38    3
39    2
Name: truth_int, dtype: int64
36     32
37    104
38    214
39     26
Name: duration, dtype: int64
3:  350 2:  26 1:  0 0:  0 -1:  0
total_duration =  376
max Id:  3
start =  40   end =  44
40    3
41    3
42    3
43    3
Name: truth_int, dtype: int64
40    170
41     20
42    164
43     40
Name: duration, dtype: int64
3:  394 2:  0 1:  0 0:  0 -1:  0
total_duration =  394
max Id:  3
start =  44   end =  48
44    3
45    3
46    3
47    3
Name: truth_int, dtype: int64
44     49
45    148
46    135
47     95
Name: duration, dtype: int64
3:  427 2:  0 1:  0 0:  0 -1:  0
total_duration =  427
max Id:  3
start =  48   end =  52
48    2
49    2
50    3
51    2
Name: truth_int, dtype: int64
48     70
49     58
50     15
51    138
Name: duration, dtype: int64
3:  15 2:  266 1:  0 0:  0 -1:  0
total_duration =  281
max Id:  2
start =  52   end =  56
52    3
53    3
54    2
55    3
Name: truth_int, dtype: int64
52     94
53     44
54     57
55    107
Name: duration, dtype: int64
3:  245 2:  57 1:  0 0:  0 -1:  0
total_duration =  302
max Id:  3
start =  56   end =  60
56    3
57    3
58    3
59    1
Name: truth_int, dtype: int64
56    211
57     59
58     48
59    117
Name: duration, dtype: int64
3:  318 2:  0 1:  117 0:  0 -1:  0
total_duration =  435
max Id:  3
start =  60   end =  64
60    3
61    3
62    3
63    3
Name: truth_int, dtype: int64
60    76
61    75
62    28
63    44
Name: duration, dtype: int64
3:  223 2:  0 1:  0 0:  0 -1:  0
total_duration =  223
max Id:  3
start =  64   end =  68
64    3
65    3
66    2
67    3
Name: truth_int, dtype: int64
64    46
65    59
66    17
67    38
Name: duration, dtype: int64
3:  143 2:  17 1:  0 0:  0 -1:  0
total_duration =  160
max Id:  3
start =  68   end =  72
68    0
69    3
70    3
71    3
Name: truth_int, dtype: int64
68     72
69     88
70     32
71    150
Name: duration, dtype: int64
3:  270 2:  0 1:  0 0:  72 -1:  0
total_duration =  342
max Id:  3
start =  72   end =  76
72    3
73    3
74    3
75    2
Name: truth_int, dtype: int64
72    101
73     39
74     91
75     29
Name: duration, dtype: int64
3:  231 2:  29 1:  0 0:  0 -1:  0
total_duration =  260
max Id:  3
start =  76   end =  80
76    3
77    3
78    3
79    3
Name: truth_int, dtype: int64
76     34
77     54
78     44
79    181
Name: duration, dtype: int64
3:  313 2:  0 1:  0 0:  0 -1:  0
total_duration =  313
max Id:  3
start =  80   end =  84
80    3
81    2
82    3
83    3
Name: truth_int, dtype: int64
80     57
81     61
82     38
83    138
Name: duration, dtype: int64
3:  233 2:  61 1:  0 0:  0 -1:  0
total_duration =  294
max Id:  3
start =  84   end =  88
84    0
85    3
86    3
87    3
Name: truth_int, dtype: int64
84    43
85    63
86    49
87    59
Name: duration, dtype: int64
3:  171 2:  0 1:  0 0:  43 -1:  0
total_duration =  214
max Id:  3
start =  88   end =  92
88    3
89    3
90    3
91    3
Name: truth_int, dtype: int64
88    27
89    22
90    23
91    27
Name: duration, dtype: int64
3:  99 2:  0 1:  0 0:  0 -1:  0
total_duration =  99
max Id:  3
start =  92   end =  93
92    3
Name: truth_int, dtype: int64
92    20
Name: duration, dtype: int64
3:  20 2:  0 1:  0 0:  0 -1:  0
total_duration =  20
max Id:  3
start =  96   end =  93
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  100   end =  93
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  104   end =  93
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  93
block_len 11
start =  0   end =  11
0     3
1     3
2     3
3     3
4     3
5     3
6     3
7     2
8     2
9     3
10    3
Name: truth_int, dtype: int64
0      27
1      65
2      43
3      14
4      28
5      60
6      52
7     130
8      97
9     110
10     55
Name: duration, dtype: int64
3:  454 2:  227 1:  0 0:  0 -1:  0
total_duration =  681
max Id:  3
start =  11   end =  22
11    3
12    3
13    3
14    3
15    1
16    3
17    3
18    3
19    3
20    3
21    0
Name: truth_int, dtype: int64
11     97
12     67
13     54
14     69
15    122
16    203
17     16
18     50
19     58
20     88
21     22
Name: duration, dtype: int64
3:  702 2:  0 1:  122 0:  22 -1:  0
total_duration =  846
max Id:  3
start =  22   end =  33
22    2
23    3
24    3
25    3
26    3
27    3
28    3
29    3
30    3
31    2
32    3
Name: truth_int, dtype: int64
22    149
23    319
24     45
25     67
26     84
27    133
28     71
29     50
30     69
31    179
32    230
Name: duration, dtype: int64
3:  1068 2:  328 1:  0 0:  0 -1:  0
total_duration =  1396
max Id:  3
start =  33   end =  44
33    1
34    1
35    0
36    3
37    3
38    3
39    2
40    3
41    3
42    3
43    3
Name: truth_int, dtype: int64
33     62
34    166
35     80
36     32
37    104
38    214
39     26
40    170
41     20
42    164
43     40
Name: duration, dtype: int64
3:  744 2:  26 1:  228 0:  80 -1:  0
total_duration =  1078
max Id:  3
start =  44   end =  55
44    3
45    3
46    3
47    3
48    2
49    2
50    3
51    2
52    3
53    3
54    2
Name: truth_int, dtype: int64
44     49
45    148
46    135
47     95
48     70
49     58
50     15
51    138
52     94
53     44
54     57
Name: duration, dtype: int64
3:  580 2:  323 1:  0 0:  0 -1:  0
total_duration =  903
max Id:  3
start =  55   end =  66
55    3
56    3
57    3
58    3
59    1
60    3
61    3
62    3
63    3
64    3
65    3
Name: truth_int, dtype: int64
55    107
56    211
57     59
58     48
59    117
60     76
61     75
62     28
63     44
64     46
65     59
Name: duration, dtype: int64
3:  753 2:  0 1:  117 0:  0 -1:  0
total_duration =  870
max Id:  3
start =  66   end =  77
66    2
67    3
68    0
69    3
70    3
71    3
72    3
73    3
74    3
75    2
76    3
Name: truth_int, dtype: int64
66     17
67     38
68     72
69     88
70     32
71    150
72    101
73     39
74     91
75     29
76     34
Name: duration, dtype: int64
3:  573 2:  46 1:  0 0:  72 -1:  0
total_duration =  691
max Id:  3
start =  77   end =  88
77    3
78    3
79    3
80    3
81    2
82    3
83    3
84    0
85    3
86    3
87    3
Name: truth_int, dtype: int64
77     54
78     44
79    181
80     57
81     61
82     38
83    138
84     43
85     63
86     49
87     59
Name: duration, dtype: int64
3:  683 2:  61 1:  0 0:  43 -1:  0
total_duration =  787
max Id:  3
start =  88   end =  93
88    3
89    3
90    3
91    3
92    3
Name: truth_int, dtype: int64
88    27
89    22
90    23
91    27
92    20
Name: duration, dtype: int64
3:  119 2:  0 1:  0 0:  0 -1:  0
total_duration =  119
max Id:  3

data len =  93
block_len 31
start =  0   end =  31
0     3
1     3
2     3
3     3
4     3
5     3
6     3
7     2
8     2
9     3
10    3
11    3
12    3
13    3
14    3
15    1
16    3
17    3
18    3
19    3
20    3
21    0
22    2
23    3
24    3
25    3
26    3
27    3
28    3
29    3
30    3
Name: truth_int, dtype: int64
0      27
1      65
2      43
3      14
4      28
5      60
6      52
7     130
8      97
9     110
10     55
11     97
12     67
13     54
14     69
15    122
16    203
17     16
18     50
19     58
20     88
21     22
22    149
23    319
24     45
25     67
26     84
27    133
28     71
29     50
30     69
Name: duration, dtype: int64
3:  1994 2:  376 1:  122 0:  22 -1:  0
total_duration =  2514
max Id:  3
start =  31   end =  62
31    2
32    3
33    1
34    1
35    0
36    3
37    3
38    3
39    2
40    3
41    3
42    3
43    3
44    3
45    3
46    3
47    3
48    2
49    2
50    3
51    2
52    3
53    3
54    2
55    3
56    3
57    3
58    3
59    1
60    3
61    3
Name: truth_int, dtype: int64
31    179
32    230
33     62
34    166
35     80
36     32
37    104
38    214
39     26
40    170
41     20
42    164
43     40
44     49
45    148
46    135
47     95
48     70
49     58
50     15
51    138
52     94
53     44
54     57
55    107
56    211
57     59
58     48
59    117
60     76
61     75
Name: duration, dtype: int64
3:  2130 2:  528 1:  345 0:  80 -1:  0
total_duration =  3083
max Id:  3
start =  62   end =  93
62    3
63    3
64    3
65    3
66    2
67    3
68    0
69    3
70    3
71    3
72    3
73    3
74    3
75    2
76    3
77    3
78    3
79    3
80    3
81    2
82    3
83    3
84    0
85    3
86    3
87    3
88    3
89    3
90    3
91    3
92    3
Name: truth_int, dtype: int64
62     28
63     44
64     46
65     59
66     17
67     38
68     72
69     88
70     32
71    150
72    101
73     39
74     91
75     29
76     34
77     54
78     44
79    181
80     57
81     61
82     38
83    138
84     43
85     63
86     49
87     59
88     27
89     22
90     23
91     27
92     20
Name: duration, dtype: int64
3:  1552 2:  107 1:  0 0:  115 -1:  0
total_duration =  1774
max Id:  3
data len =  93
block_len 93
start =  0   end =  93
0     3
1     3
2     3
3     3
4     3
5     3
6     3
7     2
8     2
9     3
10    3
11    3
12    3
13    3
14    3
15    1
16    3
17    3
18    3
19    3
20    3
21    0
22    2
23    3
24    3
25    3
26    3
27    3
28    3
29    3
     ..
63    3
64    3
65    3
66    2
67    3
68    0
69    3
70    3
71    3
72    3
73    3
74    3
75    2
76    3
77    3
78    3
79    3
80    3
81    2
82    3
83    3
84    0
85    3
86    3
87    3
88    3
89    3
90    3
91    3
92    3
Name: truth_int, Length: 93, dtype: int64
0      27
1      65
2      43
3      14
4      28
5      60
6      52
7     130
8      97
9     110
10     55
11     97
12     67
13     54
14     69
15    122
16    203
17     16
18     50
19     58
20     88
21     22
22    149
23    319
24     45
25     67
26     84
27    133
28     71
29     50
     ...
63     44
64     46
65     59
66     17
67     38
68     72
69     88
70     32
71    150
72    101
73     39
74     91
75     29
76     34
77     54
78     44
79    181
80     57
81     61
82     38
83    138
84     43
85     63
86     49
87     59
88     27
89     22
90     23
91     27
92     20
Name: duration, Length: 93, dtype: int64
3:  5676 2:  1011 1:  467 0:  217 -1:  0
total_duration =  7371
max Id:  3
TheBigShort_ice1.csv
TheBigShort_ice1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7371
Name: duration, dtype: int64
3:  7371 2:  0 1:  0 0:  0 -1:  0
total_duration =  7371
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  9   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  10   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  11   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  12   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  13   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  14   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  15   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  16   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  17   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  18   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  19   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  20   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  21   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  22   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  23   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  24   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  25   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7371
Name: duration, dtype: int64
3:  7371 2:  0 1:  0 0:  0 -1:  0
total_duration =  7371
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1

data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7371
Name: duration, dtype: int64
3:  7371 2:  0 1:  0 0:  0 -1:  0
total_duration =  7371
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    7371
Name: duration, dtype: int64
3:  7371 2:  0 1:  0 0:  0 -1:  0
total_duration =  7371
max Id:  3
TheBigShort_ice2.csv
TheBigShort_ice2
failed for  TheBigShort_ice2
TheBigShort_ice4.csv
TheBigShort_ice4
failed for  TheBigShort_ice4
TheBigShort_ice8.csv
TheBigShort_ice8
failed for  TheBigShort_ice8
TheImitationGame.csv
TheImitationGame
data len =  155
block_len 6
start =  0   end =  6
0    3
1    3
2   -1
3    2
4    1
5    2
Name: truth_int, dtype: int64
0    33
1    39
2    42
3    46
4    77
5    26
Name: duration, dtype: int64
3:  72 2:  72 1:  77 0:  0 -1:  42
total_duration =  263
max Id:  1
start =  6   end =  12
6     3
7     0
8     0
9     0
10    3
11    1
Name: truth_int, dtype: int64
6     148
7      14
8      12
9      23
10     26
11     36
Name: duration, dtype: int64
3:  174 2:  0 1:  36 0:  49 -1:  0
total_duration =  259
max Id:  3
start =  12   end =  18
12    0
13    1
14    1
15    1
16    2
17    0
Name: truth_int, dtype: int64
12    61
13     1
14    52
15    16
16     5
17     2
Name: duration, dtype: int64
3:  0 2:  5 1:  69 0:  63 -1:  0
total_duration =  137
max Id:  1
start =  18   end =  24
18    3
19    1
20   -1
21    2
22    2
23    0
Name: truth_int, dtype: int64
18    31
19    16
20    24
21    35
22    15
23    56
Name: duration, dtype: int64
3:  31 2:  50 1:  16 0:  56 -1:  24
total_duration =  177
max Id:  0
start =  24   end =  30
24    2
25    1
26    0
27    2
28    3
29    3
Name: truth_int, dtype: int64
24    127
25     64
26     21
27     53
28     22
29     50
Name: duration, dtype: int64
3:  72 2:  180 1:  64 0:  21 -1:  0
total_duration =  337
max Id:  2
start =  30   end =  36
30    0
31    0
32    0
33    2
34    1
35    2
Name: truth_int, dtype: int64
30    36
31    15
32    42
33    45
34    30
35    14
Name: duration, dtype: int64
3:  0 2:  59 1:  30 0:  93 -1:  0
total_duration =  182
max Id:  0
start =  36   end =  42
36    1
37    2
38    3
39    0
40    2
41    3
Name: truth_int, dtype: int64
36    50
37     6
38     7
39    14
40    10
41    60
Name: duration, dtype: int64
3:  67 2:  16 1:  50 0:  14 -1:  0
total_duration =  147
max Id:  3
start =  42   end =  48
42    1
43    2
44   -1
45    3
46    3
47   -1
Name: truth_int, dtype: int64
42    36
43    28
44    27
45    60
46    40
47    33
Name: duration, dtype: int64
3:  100 2:  28 1:  36 0:  0 -1:  60
total_duration =  224
max Id:  3
start =  48   end =  54
48    0
49    2
50   -1
51    0
52    2
53    1
Name: truth_int, dtype: int64
48     7
49    62
50    53
51    27
52    25
53    77
Name: duration, dtype: int64
3:  0 2:  87 1:  77 0:  34 -1:  53
total_duration =  251
max Id:  2
start =  54   end =  60
54    3
55    0
56    0
57    0
58    1
59    0
Name: truth_int, dtype: int64
54    16
55    39
56    13
57    57
58    31
59    39
Name: duration, dtype: int64
3:  16 2:  0 1:  31 0:  148 -1:  0
total_duration =  195
max Id:  0
start =  60   end =  66
60    0
61    2
62    0
63   -1
64    2
65    0
Name: truth_int, dtype: int64
60    73
61    36
62     6
63    27
64    24
65    55
Name: duration, dtype: int64
3:  0 2:  60 1:  0 0:  134 -1:  27
total_duration =  221
max Id:  0
start =  66   end =  72
66    0
67    0
68    0
69   -1
70    0
71    2
Name: truth_int, dtype: int64
66     38
67    142
68     10
69     57
70     63
71     11
Name: duration, dtype: int64
3:  0 2:  11 1:  0 0:  253 -1:  57
total_duration =  321
max Id:  0
start =  72   end =  78
72    0
73    1
74    1
75    2
76    0
77    0
Name: truth_int, dtype: int64
72    36
73    26
74    14
75    63
76    62
77    71
Name: duration, dtype: int64
3:  0 2:  63 1:  40 0:  169 -1:  0
total_duration =  272
max Id:  0
start =  78   end =  84
78    2
79    1
80    3
81    3
82    0
83    0
Name: truth_int, dtype: int64
78     53
79     68
80     32
81     30
82    141
83     45
Name: duration, dtype: int64
3:  62 2:  53 1:  68 0:  186 -1:  0
total_duration =  369
max Id:  0
start =  84   end =  90
84    0
85    0
86    2
87    0
88    2
89    0
Name: truth_int, dtype: int64
84    45
85    42
86    59
87    15
88    27
89    19
Name: duration, dtype: int64
3:  0 2:  86 1:  0 0:  121 -1:  0
total_duration =  207
max Id:  0
start =  90   end =  96
90    0
91    0
92    2
93    0
94    0
95    2
Name: truth_int, dtype: int64
90      7
91     47
92     70
93     73
94    100
95     53
Name: duration, dtype: int64
3:  0 2:  123 1:  0 0:  227 -1:  0
total_duration =  350
max Id:  0
start =  96   end =  102
96     0
97     3
98     1
99     0
100    1
101    1
Name: truth_int, dtype: int64
96     217
97      60
98     159
99      68
100     56
101    205
Name: duration, dtype: int64
3:  60 2:  0 1:  420 0:  285 -1:  0
total_duration =  765
max Id:  1
start =  102   end =  108
102    2
103    0
104    1
105    2
106    0
107   -1
Name: truth_int, dtype: int64
102     40
103    149
104    101
105     13
106     52
107     27
Name: duration, dtype: int64
3:  0 2:  53 1:  101 0:  201 -1:  27
total_duration =  382
max Id:  0
start =  108   end =  114
108    2
109    0
110   -1
111    0
112    0
113   -1
Name: truth_int, dtype: int64
108    38
109    26
110    11
111    14
112     4
113    22
Name: duration, dtype: int64
3:  0 2:  38 1:  0 0:  44 -1:  33
total_duration =  115
max Id:  0
start =  114   end =  120
114    0
115    0
116    0
117    0
118    0
119    2
Name: truth_int, dtype: int64
114    62
115    46
116    43
117    42
118    35
119    13
Name: duration, dtype: int64
3:  0 2:  13 1:  0 0:  228 -1:  0
total_duration =  241
max Id:  0
start =  120   end =  126
120    0
121    0
122    0
123    0
124    2
125    3
Name: truth_int, dtype: int64
120    35
121     7
122    36
123    28
124    25
125     5
Name: duration, dtype: int64
3:  5 2:  25 1:  0 0:  106 -1:  0
total_duration =  136
max Id:  0
start =  126   end =  132
126    3
127    0
128    0
129    0
130    2
131    3
Name: truth_int, dtype: int64
126    46
127    28
128    38
129    34
130    55
131    62
Name: duration, dtype: int64
3:  108 2:  55 1:  0 0:  100 -1:  0
total_duration =  263
max Id:  3
start =  132   end =  138
132    1
133   -1
134    1
135    3
136    2
137   -1
Name: truth_int, dtype: int64
132     54
133     54
134    140
135     21
136     29
137     22
Name: duration, dtype: int64
3:  21 2:  29 1:  194 0:  0 -1:  76
total_duration =  320
max Id:  1
start =  138   end =  144
138    3
139    0
140    0
141    2
142    1
143    2
Name: truth_int, dtype: int64
138    32
139    10
140    20
141    11
142    50
143    25
Name: duration, dtype: int64
3:  32 2:  36 1:  50 0:  30 -1:  0
total_duration =  148
max Id:  1
start =  144   end =  150
144   -1
145    2
146    3
147    0
148    2
149    1
Name: truth_int, dtype: int64
144    35
145    48
146    37
147    43
148    30
149    16
Name: duration, dtype: int64
3:  37 2:  78 1:  16 0:  43 -1:  35
total_duration =  209
max Id:  2
start =  150   end =  155
150    3
151    3
152    3
153    2
154    3
Name: truth_int, dtype: int64
150    10
151    14
152    11
153    12
154    23
Name: duration, dtype: int64
3:  58 2:  12 1:  0 0:  0 -1:  0
total_duration =  70
max Id:  3
start =  156   end =  155
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  155
block_len 18
start =  0   end =  18
0     3
1     3
2    -1
3     2
4     1
5     2
6     3
7     0
8     0
9     0
10    3
11    1
12    0
13    1
14    1
15    1
16    2
17    0
Name: truth_int, dtype: int64
0      33
1      39
2      42
3      46
4      77
5      26
6     148
7      14
8      12
9      23
10     26
11     36
12     61
13      1
14     52
15     16
16      5
17      2
Name: duration, dtype: int64
3:  246 2:  77 1:  182 0:  112 -1:  42
total_duration =  659
max Id:  3
start =  18   end =  36
18    3
19    1
20   -1
21    2
22    2
23    0
24    2
25    1
26    0
27    2
28    3
29    3
30    0
31    0
32    0
33    2
34    1
35    2
Name: truth_int, dtype: int64
18     31
19     16
20     24
21     35
22     15
23     56
24    127
25     64
26     21
27     53
28     22
29     50
30     36
31     15
32     42
33     45
34     30
35     14
Name: duration, dtype: int64
3:  103 2:  289 1:  110 0:  170 -1:  24
total_duration =  696
max Id:  2
start =  36   end =  54
36    1
37    2
38    3
39    0
40    2
41    3
42    1
43    2
44   -1
45    3
46    3
47   -1
48    0
49    2
50   -1
51    0
52    2
53    1
Name: truth_int, dtype: int64
36    50
37     6
38     7
39    14
40    10
41    60
42    36
43    28
44    27
45    60
46    40
47    33
48     7
49    62
50    53
51    27
52    25
53    77
Name: duration, dtype: int64
3:  167 2:  131 1:  163 0:  48 -1:  113
total_duration =  622
max Id:  3
start =  54   end =  72
54    3
55    0
56    0
57    0
58    1
59    0
60    0
61    2
62    0
63   -1
64    2
65    0
66    0
67    0
68    0
69   -1
70    0
71    2
Name: truth_int, dtype: int64
54     16
55     39
56     13
57     57
58     31
59     39
60     73
61     36
62      6
63     27
64     24
65     55
66     38
67    142
68     10
69     57
70     63
71     11
Name: duration, dtype: int64
3:  16 2:  71 1:  31 0:  535 -1:  84
total_duration =  737
max Id:  0
start =  72   end =  90
72    0
73    1
74    1
75    2
76    0
77    0
78    2
79    1
80    3
81    3
82    0
83    0
84    0
85    0
86    2
87    0
88    2
89    0
Name: truth_int, dtype: int64
72     36
73     26
74     14
75     63
76     62
77     71
78     53
79     68
80     32
81     30
82    141
83     45
84     45
85     42
86     59
87     15
88     27
89     19
Name: duration, dtype: int64
3:  62 2:  202 1:  108 0:  476 -1:  0
total_duration =  848
max Id:  0
start =  90   end =  108
90     0
91     0
92     2
93     0
94     0
95     2
96     0
97     3
98     1
99     0
100    1
101    1
102    2
103    0
104    1
105    2
106    0
107   -1
Name: truth_int, dtype: int64
90       7
91      47
92      70
93      73
94     100
95      53
96     217
97      60
98     159
99      68
100     56
101    205
102     40
103    149
104    101
105     13
106     52
107     27
Name: duration, dtype: int64
3:  60 2:  176 1:  521 0:  713 -1:  27
total_duration =  1497
max Id:  0
start =  108   end =  126
108    2
109    0
110   -1
111    0
112    0
113   -1
114    0
115    0
116    0
117    0
118    0
119    2
120    0
121    0
122    0
123    0
124    2
125    3
Name: truth_int, dtype: int64
108    38
109    26
110    11
111    14
112     4
113    22
114    62
115    46
116    43
117    42
118    35
119    13
120    35
121     7
122    36
123    28
124    25
125     5
Name: duration, dtype: int64
3:  5 2:  76 1:  0 0:  378 -1:  33
total_duration =  492
max Id:  0
start =  126   end =  144
126    3
127    0
128    0
129    0
130    2
131    3
132    1
133   -1
134    1
135    3
136    2
137   -1
138    3
139    0
140    0
141    2
142    1
143    2
Name: truth_int, dtype: int64
126     46
127     28
128     38
129     34
130     55
131     62
132     54
133     54
134    140
135     21
136     29
137     22
138     32
139     10
140     20
141     11
142     50
143     25
Name: duration, dtype: int64
3:  161 2:  120 1:  244 0:  130 -1:  76
total_duration =  731
max Id:  1
start =  144   end =  155
144   -1
145    2
146    3
147    0
148    2
149    1
150    3
151    3
152    3
153    2
154    3
Name: truth_int, dtype: int64
144    35
145    48
146    37
147    43
148    30
149    16
150    10
151    14
152    11
153    12
154    23
Name: duration, dtype: int64
3:  95 2:  90 1:  16 0:  43 -1:  35
total_duration =  279
max Id:  3

data len =  155
block_len 52
start =  0   end =  52
0     3
1     3
2    -1
3     2
4     1
5     2
6     3
7     0
8     0
9     0
10    3
11    1
12    0
13    1
14    1
15    1
16    2
17    0
18    3
19    1
20   -1
21    2
22    2
23    0
24    2
25    1
26    0
27    2
28    3
29    3
30    0
31    0
32    0
33    2
34    1
35    2
36    1
37    2
38    3
39    0
40    2
41    3
42    1
43    2
44   -1
45    3
46    3
47   -1
48    0
49    2
50   -1
51    0
Name: truth_int, dtype: int64
0      33
1      39
2      42
3      46
4      77
5      26
6     148
7      14
8      12
9      23
10     26
11     36
12     61
13      1
14     52
15     16
16      5
17      2
18     31
19     16
20     24
21     35
22     15
23     56
24    127
25     64
26     21
27     53
28     22
29     50
30     36
31     15
32     42
33     45
34     30
35     14
36     50
37      6
38      7
39     14
40     10
41     60
42     36
43     28
44     27
45     60
46     40
47     33
48      7
49     62
50     53
51     27
Name: duration, dtype: int64
3:  516 2:  472 1:  378 0:  330 -1:  179
total_duration =  1875
max Id:  3
start =  52   end =  104
52     2
53     1
54     3
55     0
56     0
57     0
58     1
59     0
60     0
61     2
62     0
63    -1
64     2
65     0
66     0
67     0
68     0
69    -1
70     0
71     2
72     0
73     1
74     1
75     2
76     0
77     0
78     2
79     1
80     3
81     3
82     0
83     0
84     0
85     0
86     2
87     0
88     2
89     0
90     0
91     0
92     2
93     0
94     0
95     2
96     0
97     3
98     1
99     0
100    1
101    1
102    2
103    0
Name: truth_int, dtype: int64
52      25
53      77
54      16
55      39
56      13
57      57
58      31
59      39
60      73
61      36
62       6
63      27
64      24
65      55
66      38
67     142
68      10
69      57
70      63
71      11
72      36
73      26
74      14
75      63
76      62
77      71
78      53
79      68
80      32
81      30
82     141
83      45
84      45
85      42
86      59
87      15
88      27
89      19
90       7
91      47
92      70
93      73
94     100
95      53
96     217
97      60
98     159
99      68
100     56
101    205
102     40
103    149
Name: duration, dtype: int64
3:  138 2:  461 1:  636 0:  1672 -1:  84
total_duration =  2991
max Id:  0
start =  104   end =  155
104    1
105    2
106    0
107   -1
108    2
109    0
110   -1
111    0
112    0
113   -1
114    0
115    0
116    0
117    0
118    0
119    2
120    0
121    0
122    0
123    0
124    2
125    3
126    3
127    0
128    0
129    0
130    2
131    3
132    1
133   -1
134    1
135    3
136    2
137   -1
138    3
139    0
140    0
141    2
142    1
143    2
144   -1
145    2
146    3
147    0
148    2
149    1
150    3
151    3
152    3
153    2
154    3
Name: truth_int, dtype: int64
104    101
105     13
106     52
107     27
108     38
109     26
110     11
111     14
112      4
113     22
114     62
115     46
116     43
117     42
118     35
119     13
120     35
121      7
122     36
123     28
124     25
125      5
126     46
127     28
128     38
129     34
130     55
131     62
132     54
133     54
134    140
135     21
136     29
137     22
138     32
139     10
140     20
141     11
142     50
143     25
144     35
145     48
146     37
147     43
148     30
149     16
150     10
151     14
152     11
153     12
154     23
Name: duration, dtype: int64
3:  261 2:  299 1:  361 0:  603 -1:  171
total_duration =  1695
max Id:  0
data len =  155
block_len 155
start =  0   end =  155
0      3
1      3
2     -1
3      2
4      1
5      2
6      3
7      0
8      0
9      0
10     3
11     1
12     0
13     1
14     1
15     1
16     2
17     0
18     3
19     1
20    -1
21     2
22     2
23     0
24     2
25     1
26     0
27     2
28     3
29     3
      ..
125    3
126    3
127    0
128    0
129    0
130    2
131    3
132    1
133   -1
134    1
135    3
136    2
137   -1
138    3
139    0
140    0
141    2
142    1
143    2
144   -1
145    2
146    3
147    0
148    2
149    1
150    3
151    3
152    3
153    2
154    3
Name: truth_int, Length: 155, dtype: int64
0       33
1       39
2       42
3       46
4       77
5       26
6      148
7       14
8       12
9       23
10      26
11      36
12      61
13       1
14      52
15      16
16       5
17       2
18      31
19      16
20      24
21      35
22      15
23      56
24     127
25      64
26      21
27      53
28      22
29      50
      ...
125      5
126     46
127     28
128     38
129     34
130     55
131     62
132     54
133     54
134    140
135     21
136     29
137     22
138     32
139     10
140     20
141     11
142     50
143     25
144     35
145     48
146     37
147     43
148     30
149     16
150     10
151     14
152     11
153     12
154     23
Name: duration, Length: 155, dtype: int64
3:  915 2:  1232 1:  1375 0:  2605 -1:  434
total_duration =  6561
max Id:  0
TheImitationGame_ice1.csv
TheImitationGame_ice1
data len =  1
block_len 1
start =  0   end =  1
0    0
Name: truth_int, dtype: int64
0    6561
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  6561 -1:  0
total_duration =  6561
max Id:  0
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  9   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  10   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  11   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  12   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  13   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  14   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  15   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  16   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  17   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  18   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  19   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  20   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  21   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  22   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  23   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  24   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  25   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    0
Name: truth_int, dtype: int64
0    6561
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  6561 -1:  0
total_duration =  6561
max Id:  0
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)

3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    0
Name: truth_int, dtype: int64
0    6561
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  6561 -1:  0
total_duration =  6561
max Id:  0
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    0
Name: truth_int, dtype: int64
0    6561
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  6561 -1:  0
total_duration =  6561
max Id:  0
TheImitationGame_ice2.csv
TheImitationGame_ice2
failed for  TheImitationGame_ice2
TheImitationGame_ice4.csv
TheImitationGame_ice4
failed for  TheImitationGame_ice4
TheImitationGame_ice8.csv
TheImitationGame_ice8
failed for  TheImitationGame_ice8
TheKingsSpeech.csv
TheKingsSpeech
data len =  90
block_len 4
start =  0   end =  4
0    3
1    -
2    3
3    3
Name: truth_int, dtype: object
0    12
1    30
2    16
3    32
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  90
failed for  TheKingsSpeech
TheSocialNetwork.csv
TheSocialNetwork
data len =  171
block_len 7
start =  0   end =  7
0    0
1    3
2    0
3    2
4    0
5    2
6    3
Name: truth_int, dtype: int64
0    105
1     29
2     46
3     19
4    104
5    147
6     49
Name: duration, dtype: int64
3:  78 2:  166 1:  0 0:  255 -1:  0
total_duration =  499
max Id:  0
start =  7   end =  14
7     3
8     3
9     3
10    3
11    3
12    2
13    3
Name: truth_int, dtype: int64
7     10
8     23
9     31
10    16
11     0
12    27
13    13
Name: duration, dtype: int64
3:  93 2:  27 1:  0 0:  0 -1:  0
total_duration =  120
max Id:  3
start =  14   end =  21
14    3
15    3
16    0
17    0
18   -1
19    0
20    3
Name: truth_int, dtype: int64
14    20
15    54
16    53
17    15
18     4
19    10
20    44
Name: duration, dtype: int64
3:  118 2:  0 1:  0 0:  78 -1:  4
total_duration =  200
max Id:  3
start =  21   end =  28
21    3
22    0
23    3
24    0
25    0
26    0
27    3
Name: truth_int, dtype: int64
21    27
22    22
23    21
24    35
25    33
26    42
27    15
Name: duration, dtype: int64
3:  63 2:  0 1:  0 0:  132 -1:  0
total_duration =  195
max Id:  0
start =  28   end =  35
28    3
29    3
30    3
31    3
32    3
33    1
34    0
Name: truth_int, dtype: int64
28    43
29    47
30    12
31    23
32    33
33    23
34    28
Name: duration, dtype: int64
3:  158 2:  0 1:  23 0:  28 -1:  0
total_duration =  209
max Id:  3
start =  35   end =  42
35    0
36    2
37    2
38    3
39    3
40    3
41    2
Name: truth_int, dtype: int64
35    46
36    42
37     9
38    46
39    73
40    47
41    92
Name: duration, dtype: int64
3:  166 2:  143 1:  0 0:  46 -1:  0
total_duration =  355
max Id:  3
start =  42   end =  49
42    3
43   -1
44    0
45    3
46    3
47    3
48    3
Name: truth_int, dtype: int64
42    51
43    25
44     6
45     5
46     3
47     7
48     6
Name: duration, dtype: int64
3:  72 2:  0 1:  0 0:  6 -1:  25
total_duration =  103
max Id:  3
start =  49   end =  56
49    0
50    0
51   -1
52   -1
53    3
54    3
55    3
Name: truth_int, dtype: int64
49     9
50    25
51    13
52    57
53    11
54    48
55    31
Name: duration, dtype: int64
3:  90 2:  0 1:  0 0:  34 -1:  70
total_duration =  194
max Id:  3
start =  56   end =  63
56    2
57    3
58    3
59    3
60    2
61    3
62    0
Name: truth_int, dtype: int64
56    40
57    27
58    41
59    20
60     8
61    18
62    41
Name: duration, dtype: int64
3:  106 2:  48 1:  0 0:  41 -1:  0
total_duration =  195
max Id:  3
start =  63   end =  70
63    2
64    3
65    3
66    0
67    2
68    0
69    3
Name: truth_int, dtype: int64
63    51
64    15
65    48
66    14
67    69
68    62
69    36
Name: duration, dtype: int64
3:  99 2:  120 1:  0 0:  76 -1:  0
total_duration =  295
max Id:  2
start =  70   end =  77
70    3
71    0
72    3
73    3
74    2
75    3
76    3
Name: truth_int, dtype: int64
70    175
71     71
72     12
73     23
74     75
75     53
76     55
Name: duration, dtype: int64
3:  318 2:  75 1:  0 0:  71 -1:  0
total_duration =  464
max Id:  3
start =  77   end =  84
77    3
78    1
79    3
80    3
81    1
82    0
83    3
Name: truth_int, dtype: int64
77     85
78    107
79     14
80     44
81     27
82     99
83     46
Name: duration, dtype: int64
3:  189 2:  0 1:  134 0:  99 -1:  0
total_duration =  422
max Id:  3
start =  84   end =  91
84   -1
85    3
86    2
87    3
88    3
89    3
90    1
Name: truth_int, dtype: int64
84     68
85     77
86    131
87     68
88     23
89    205
90     11
Name: duration, dtype: int64
3:  373 2:  131 1:  11 0:  0 -1:  68
total_duration =  583
max Id:  3
start =  91   end =  98
91    3
92    3
93    3
94    2
95    3
96    3
97    3
Name: truth_int, dtype: int64
91    32
92    32
93    11
94    30
95    15
96    45
97     2
Name: duration, dtype: int64
3:  137 2:  30 1:  0 0:  0 -1:  0
total_duration =  167
max Id:  3
start =  98   end =  105
98     3
99     3
100    3
101    3
102    3
103    3
104    3
Name: truth_int, dtype: int64
98      8
99      7
100     9
101     2
102    21
103     8
104     8
Name: duration, dtype: int64
3:  63 2:  0 1:  0 0:  0 -1:  0
total_duration =  63
max Id:  3
start =  105   end =  112
105    0
106    3
107    0
108    2
109    3
110    3
111    2
Name: truth_int, dtype: int64
105     8
106    26
107     1
108    20
109    14
110    54
111    10
Name: duration, dtype: int64
3:  94 2:  30 1:  0 0:  9 -1:  0
total_duration =  133
max Id:  3
start =  112   end =  119
112    2
113    3
114    2
115    2
116   -1
117    0
118    3
Name: truth_int, dtype: int64
112    32
113    10
114    18
115    23
116    57
117     5
118    10
Name: duration, dtype: int64
3:  20 2:  73 1:  0 0:  5 -1:  57
total_duration =  155
max Id:  2
start =  119   end =  126
119    0
120    3
121    0
122   -1
123    0
124    3
125    2
Name: truth_int, dtype: int64
119     7
120     9
121     4
122     7
123     2
124    22
125    31
Name: duration, dtype: int64
3:  31 2:  31 1:  0 0:  13 -1:  7
total_duration =  82
max Id:  2
start =  126   end =  133
126   -1
127    3
128    3
129    3
130    3
131    2
132    3
Name: truth_int, dtype: int64
126     28
127     85
128    102
129     39
130     47
131     28
132     43
Name: duration, dtype: int64
3:  316 2:  28 1:  0 0:  0 -1:  28
total_duration =  372
max Id:  3
start =  133   end =  140
133    3
134    3
135    3
136    2
137    3
138    0
139    3
Name: truth_int, dtype: int64
133    235
134    102
135    119
136     56
137     39
138     62
139     70
Name: duration, dtype: int64
3:  565 2:  56 1:  0 0:  62 -1:  0
total_duration =  683
max Id:  3
start =  140   end =  147
140    3
141    3
142    3
143    3
144    1
145    3
146    3
Name: truth_int, dtype: int64
140    87
141    19
142    13
143    38
144    97
145    45
146    59
Name: duration, dtype: int64
3:  261 2:  0 1:  97 0:  0 -1:  0
total_duration =  358
max Id:  3
start =  147   end =  154
147    2
148    2
149    3
150    3
151    3
152    3
153    3
Name: truth_int, dtype: int64
147     9
148     7
149    66
150    62
151    22
152    54
153    47
Name: duration, dtype: int64
3:  251 2:  16 1:  0 0:  0 -1:  0
total_duration =  267
max Id:  3
start =  154   end =  161
154    3
155    1
156    0
157    0
158    0
159    0
160    3
Name: truth_int, dtype: int64
154    52
155     2
156    99
157    30
158    42
159    40
160    30
Name: duration, dtype: int64
3:  82 2:  0 1:  2 0:  211 -1:  0
total_duration =  295
max Id:  0
start =  161   end =  168
161    3
162    3
163    3
164    3
165    0
166    2
167    3
Name: truth_int, dtype: int64
161    40
162    14
163    35
164    64
165     6
166    72
167    16
Name: duration, dtype: int64
3:  169 2:  72 1:  0 0:  6 -1:  0
total_duration =  247
max Id:  3
start =  168   end =  171
168    3
169    1
170    3
Name: truth_int, dtype: int64
168    147
169     52
170    119
Name: duration, dtype: int64
3:  266 2:  0 1:  52 0:  0 -1:  0
total_duration =  318
max Id:  3
start =  175   end =  171
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  182   end =  171
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  171
block_len 19
start =  0   end =  19
0     0
1     3
2     0
3     2
4     0
5     2
6     3
7     3
8     3
9     3
10    3
11    3
12    2
13    3
14    3
15    3
16    0
17    0
18   -1
Name: truth_int, dtype: int64
0     105
1      29
2      46
3      19
4     104
5     147
6      49
7      10
8      23
9      31
10     16
11      0
12     27
13     13
14     20
15     54
16     53
17     15
18      4
Name: duration, dtype: int64
3:  245 2:  193 1:  0 0:  323 -1:  4
total_duration =  765
max Id:  0
start =  19   end =  38
19    0
20    3
21    3
22    0
23    3
24    0
25    0
26    0
27    3
28    3
29    3
30    3
31    3
32    3
33    1
34    0
35    0
36    2
37    2
Name: truth_int, dtype: int64
19    10
20    44
21    27
22    22
23    21
24    35
25    33
26    42
27    15
28    43
29    47
30    12
31    23
32    33
33    23
34    28
35    46
36    42
37     9
Name: duration, dtype: int64
3:  265 2:  51 1:  23 0:  216 -1:  0
total_duration =  555
max Id:  3
start =  38   end =  57
38    3
39    3
40    3
41    2
42    3
43   -1
44    0
45    3
46    3
47    3
48    3
49    0
50    0
51   -1
52   -1
53    3
54    3
55    3
56    2
Name: truth_int, dtype: int64
38    46
39    73
40    47
41    92
42    51
43    25
44     6
45     5
46     3
47     7
48     6
49     9
50    25
51    13
52    57
53    11
54    48
55    31
56    40
Name: duration, dtype: int64
3:  328 2:  132 1:  0 0:  40 -1:  95
total_duration =  595
max Id:  3
start =  57   end =  76
57    3
58    3
59    3
60    2
61    3
62    0
63    2
64    3
65    3
66    0
67    2
68    0
69    3
70    3
71    0
72    3
73    3
74    2
75    3
Name: truth_int, dtype: int64
57     27
58     41
59     20
60      8
61     18
62     41
63     51
64     15
65     48
66     14
67     69
68     62
69     36
70    175
71     71
72     12
73     23
74     75
75     53
Name: duration, dtype: int64
3:  468 2:  203 1:  0 0:  188 -1:  0
total_duration =  859
max Id:  3
start =  76   end =  95
76    3
77    3
78    1
79    3
80    3
81    1
82    0
83    3
84   -1
85    3
86    2
87    3
88    3
89    3
90    1
91    3
92    3
93    3
94    2
Name: truth_int, dtype: int64
76     55
77     85
78    107
79     14
80     44
81     27
82     99
83     46
84     68
85     77
86    131
87     68
88     23
89    205
90     11
91     32
92     32
93     11
94     30
Name: duration, dtype: int64
3:  692 2:  161 1:  145 0:  99 -1:  68
total_duration =  1165
max Id:  3
start =  95   end =  114
95     3
96     3
97     3
98     3
99     3
100    3
101    3
102    3
103    3
104    3
105    0
106    3
107    0
108    2
109    3
110    3
111    2
112    2
113    3
Name: truth_int, dtype: int64
95     15
96     45
97      2
98      8
99      7
100     9
101     2
102    21
103     8
104     8
105     8
106    26
107     1
108    20
109    14
110    54
111    10
112    32
113    10
Name: duration, dtype: int64
3:  229 2:  62 1:  0 0:  9 -1:  0
total_duration =  300
max Id:  3
start =  114   end =  133
114    2
115    2
116   -1
117    0
118    3
119    0
120    3
121    0
122   -1
123    0
124    3
125    2
126   -1
127    3
128    3
129    3
130    3
131    2
132    3
Name: truth_int, dtype: int64
114     18
115     23
116     57
117      5
118     10
119      7
120      9
121      4
122      7
123      2
124     22
125     31
126     28
127     85
128    102
129     39
130     47
131     28
132     43
Name: duration, dtype: int64
3:  357 2:  100 1:  0 0:  18 -1:  92
total_duration =  567
max Id:  3
start =  133   end =  152
133    3
134    3
135    3
136    2
137    3
138    0
139    3
140    3
141    3
142    3
143    3
144    1
145    3
146    3
147    2
148    2
149    3
150    3
151    3
Name: truth_int, dtype: int64
133    235
134    102
135    119
136     56
137     39
138     62
139     70
140     87
141     19
142     13
143     38
144     97
145     45
146     59
147      9
148      7
149     66
150     62
151     22
Name: duration, dtype: int64
3:  976 2:  72 1:  97 0:  62 -1:  0
total_duration =  1207
max Id:  3
start =  152   end =  171
152    3
153    3
154    3
155    1
156    0
157    0
158    0
159    0
160    3
161    3
162    3
163    3
164    3
165    0
166    2
167    3
168    3
169    1
170    3
Name: truth_int, dtype: int64
152     54
153     47
154     52
155      2
156     99
157     30
158     42
159     40
160     30
161     40
162     14
163     35
164     64
165      6
166     72
167     16
168    147
169     52
170    119
Name: duration, dtype: int64
3:  618 2:  72 1:  54 0:  217 -1:  0
total_duration =  961
max Id:  3

data len =  171
block_len 57
start =  0   end =  57
0     0
1     3
2     0
3     2
4     0
5     2
6     3
7     3
8     3
9     3
10    3
11    3
12    2
13    3
14    3
15    3
16    0
17    0
18   -1
19    0
20    3
21    3
22    0
23    3
24    0
25    0
26    0
27    3
28    3
29    3
30    3
31    3
32    3
33    1
34    0
35    0
36    2
37    2
38    3
39    3
40    3
41    2
42    3
43   -1
44    0
45    3
46    3
47    3
48    3
49    0
50    0
51   -1
52   -1
53    3
54    3
55    3
56    2
Name: truth_int, dtype: int64
0     105
1      29
2      46
3      19
4     104
5     147
6      49
7      10
8      23
9      31
10     16
11      0
12     27
13     13
14     20
15     54
16     53
17     15
18      4
19     10
20     44
21     27
22     22
23     21
24     35
25     33
26     42
27     15
28     43
29     47
30     12
31     23
32     33
33     23
34     28
35     46
36     42
37      9
38     46
39     73
40     47
41     92
42     51
43     25
44      6
45      5
46      3
47      7
48      6
49      9
50     25
51     13
52     57
53     11
54     48
55     31
56     40
Name: duration, dtype: int64
3:  838 2:  376 1:  23 0:  579 -1:  99
total_duration =  1915
max Id:  3
start =  57   end =  114
57     3
58     3
59     3
60     2
61     3
62     0
63     2
64     3
65     3
66     0
67     2
68     0
69     3
70     3
71     0
72     3
73     3
74     2
75     3
76     3
77     3
78     1
79     3
80     3
81     1
82     0
83     3
84    -1
85     3
86     2
87     3
88     3
89     3
90     1
91     3
92     3
93     3
94     2
95     3
96     3
97     3
98     3
99     3
100    3
101    3
102    3
103    3
104    3
105    0
106    3
107    0
108    2
109    3
110    3
111    2
112    2
113    3
Name: truth_int, dtype: int64
57      27
58      41
59      20
60       8
61      18
62      41
63      51
64      15
65      48
66      14
67      69
68      62
69      36
70     175
71      71
72      12
73      23
74      75
75      53
76      55
77      85
78     107
79      14
80      44
81      27
82      99
83      46
84      68
85      77
86     131
87      68
88      23
89     205
90      11
91      32
92      32
93      11
94      30
95      15
96      45
97       2
98       8
99       7
100      9
101      2
102     21
103      8
104      8
105      8
106     26
107      1
108     20
109     14
110     54
111     10
112     32
113     10
Name: duration, dtype: int64
3:  1389 2:  426 1:  145 0:  296 -1:  68
total_duration =  2324
max Id:  3
start =  114   end =  171
114    2
115    2
116   -1
117    0
118    3
119    0
120    3
121    0
122   -1
123    0
124    3
125    2
126   -1
127    3
128    3
129    3
130    3
131    2
132    3
133    3
134    3
135    3
136    2
137    3
138    0
139    3
140    3
141    3
142    3
143    3
144    1
145    3
146    3
147    2
148    2
149    3
150    3
151    3
152    3
153    3
154    3
155    1
156    0
157    0
158    0
159    0
160    3
161    3
162    3
163    3
164    3
165    0
166    2
167    3
168    3
169    1
170    3
Name: truth_int, dtype: int64
114     18
115     23
116     57
117      5
118     10
119      7
120      9
121      4
122      7
123      2
124     22
125     31
126     28
127     85
128    102
129     39
130     47
131     28
132     43
133    235
134    102
135    119
136     56
137     39
138     62
139     70
140     87
141     19
142     13
143     38
144     97
145     45
146     59
147      9
148      7
149     66
150     62
151     22
152     54
153     47
154     52
155      2
156     99
157     30
158     42
159     40
160     30
161     40
162     14
163     35
164     64
165      6
166     72
167     16
168    147
169     52
170    119
Name: duration, dtype: int64
3:  1951 2:  244 1:  151 0:  297 -1:  92
total_duration =  2735
max Id:  3
data len =  171
block_len 171
start =  0   end =  171
0      0
1      3
2      0
3      2
4      0
5      2
6      3
7      3
8      3
9      3
10     3
11     3
12     2
13     3
14     3
15     3
16     0
17     0
18    -1
19     0
20     3
21     3
22     0
23     3
24     0
25     0
26     0
27     3
28     3
29     3
      ..
141    3
142    3
143    3
144    1
145    3
146    3
147    2
148    2
149    3
150    3
151    3
152    3
153    3
154    3
155    1
156    0
157    0
158    0
159    0
160    3
161    3
162    3
163    3
164    3
165    0
166    2
167    3
168    3
169    1
170    3
Name: truth_int, Length: 171, dtype: int64
0      105
1       29
2       46
3       19
4      104
5      147
6       49
7       10
8       23
9       31
10      16
11       0
12      27
13      13
14      20
15      54
16      53
17      15
18       4
19      10
20      44
21      27
22      22
23      21
24      35
25      33
26      42
27      15
28      43
29      47
      ...
141     19
142     13
143     38
144     97
145     45
146     59
147      9
148      7
149     66
150     62
151     22
152     54
153     47
154     52
155      2
156     99
157     30
158     42
159     40
160     30
161     40
162     14
163     35
164     64
165      6
166     72
167     16
168    147
169     52
170    119
Name: duration, Length: 171, dtype: int64
3:  4178 2:  1046 1:  319 0:  1172 -1:  259
total_duration =  6974
max Id:  3
TheSocialNetwork_ice1.csv
TheSocialNetwork_ice1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    6974
Name: duration, dtype: int64
3:  6974 2:  0 1:  0 0:  0 -1:  0
total_duration =  6974
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  9   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  10   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  11   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  12   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  13   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  14   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  15   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  16   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  17   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  18   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  19   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  20   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  21   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  22   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  23   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0

max Id:  -1
start =  24   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  25   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    6974
Name: duration, dtype: int64
3:  6974 2:  0 1:  0 0:  0 -1:  0
total_duration =  6974
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  3   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    6974
Name: duration, dtype: int64
3:  6974 2:  0 1:  0 0:  0 -1:  0
total_duration =  6974
max Id:  3
start =  1   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  2   end =  1
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  1
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    6974
Name: duration, dtype: int64
3:  6974 2:  0 1:  0 0:  0 -1:  0
total_duration =  6974
max Id:  3
TheSocialNetwork_ice2.csv
TheSocialNetwork_ice2
failed for  TheSocialNetwork_ice2
TheSocialNetwork_ice27.csv
TheSocialNetwork_ice27
data len =  27
block_len 1
start =  0   end =  1
0    0
Name: truth_int, dtype: int64
0    499
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  499 -1:  0
total_duration =  499
max Id:  0
start =  1   end =  2
1    3
Name: truth_int, dtype: int64
1    120
Name: duration, dtype: int64
3:  120 2:  0 1:  0 0:  0 -1:  0
total_duration =  120
max Id:  3
start =  2   end =  3
2    3
Name: truth_int, dtype: int64
2    200
Name: duration, dtype: int64
3:  200 2:  0 1:  0 0:  0 -1:  0
total_duration =  200
max Id:  3
start =  3   end =  4
3    0
Name: truth_int, dtype: int64
3    195
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  195 -1:  0
total_duration =  195
max Id:  0
start =  4   end =  5
4    3
Name: truth_int, dtype: int64
4    209
Name: duration, dtype: int64
3:  209 2:  0 1:  0 0:  0 -1:  0
total_duration =  209
max Id:  3
start =  5   end =  6
5    3
Name: truth_int, dtype: int64
5    355
Name: duration, dtype: int64
3:  355 2:  0 1:  0 0:  0 -1:  0
total_duration =  355
max Id:  3
start =  6   end =  7
6    3
Name: truth_int, dtype: int64
6    103
Name: duration, dtype: int64
3:  103 2:  0 1:  0 0:  0 -1:  0
total_duration =  103
max Id:  3
start =  7   end =  8
7    3
Name: truth_int, dtype: int64
7    194
Name: duration, dtype: int64
3:  194 2:  0 1:  0 0:  0 -1:  0
total_duration =  194
max Id:  3
start =  8   end =  9
8    3
Name: truth_int, dtype: int64
8    195
Name: duration, dtype: int64
3:  195 2:  0 1:  0 0:  0 -1:  0
total_duration =  195
max Id:  3
start =  9   end =  10
9    2
Name: truth_int, dtype: int64
9    295
Name: duration, dtype: int64
3:  0 2:  295 1:  0 0:  0 -1:  0
total_duration =  295
max Id:  2
start =  10   end =  11
10    3
Name: truth_int, dtype: int64
10    464
Name: duration, dtype: int64
3:  464 2:  0 1:  0 0:  0 -1:  0
total_duration =  464
max Id:  3
start =  11   end =  12
11    3
Name: truth_int, dtype: int64
11    422
Name: duration, dtype: int64
3:  422 2:  0 1:  0 0:  0 -1:  0
total_duration =  422
max Id:  3
start =  12   end =  13
12    3
Name: truth_int, dtype: int64
12    583
Name: duration, dtype: int64
3:  583 2:  0 1:  0 0:  0 -1:  0
total_duration =  583
max Id:  3
start =  13   end =  14
13    3
Name: truth_int, dtype: int64
13    167
Name: duration, dtype: int64
3:  167 2:  0 1:  0 0:  0 -1:  0
total_duration =  167
max Id:  3
start =  14   end =  15
14    3
Name: truth_int, dtype: int64
14    63
Name: duration, dtype: int64
3:  63 2:  0 1:  0 0:  0 -1:  0
total_duration =  63
max Id:  3
start =  15   end =  16
15    3
Name: truth_int, dtype: int64
15    133
Name: duration, dtype: int64
3:  133 2:  0 1:  0 0:  0 -1:  0
total_duration =  133
max Id:  3
start =  16   end =  17
16    2
Name: truth_int, dtype: int64
16    155
Name: duration, dtype: int64
3:  0 2:  155 1:  0 0:  0 -1:  0
total_duration =  155
max Id:  2
start =  17   end =  18
17    2
Name: truth_int, dtype: int64
17    82
Name: duration, dtype: int64
3:  0 2:  82 1:  0 0:  0 -1:  0
total_duration =  82
max Id:  2
start =  18   end =  19
18    3
Name: truth_int, dtype: int64
18    372
Name: duration, dtype: int64
3:  372 2:  0 1:  0 0:  0 -1:  0
total_duration =  372
max Id:  3
start =  19   end =  20
19    3
Name: truth_int, dtype: int64
19    683
Name: duration, dtype: int64
3:  683 2:  0 1:  0 0:  0 -1:  0
total_duration =  683
max Id:  3
start =  20   end =  21
20    3
Name: truth_int, dtype: int64
20    358
Name: duration, dtype: int64
3:  358 2:  0 1:  0 0:  0 -1:  0
total_duration =  358
max Id:  3
start =  21   end =  22
21    3
Name: truth_int, dtype: int64
21    267
Name: duration, dtype: int64
3:  267 2:  0 1:  0 0:  0 -1:  0
total_duration =  267
max Id:  3
start =  22   end =  23
22    0
Name: truth_int, dtype: int64
22    295
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  295 -1:  0
total_duration =  295
max Id:  0
start =  23   end =  24
23    3
Name: truth_int, dtype: int64
23    247
Name: duration, dtype: int64
3:  247 2:  0 1:  0 0:  0 -1:  0
total_duration =  247
max Id:  3
start =  24   end =  25
24    3
Name: truth_int, dtype: int64
24    318
Name: duration, dtype: int64
3:  318 2:  0 1:  0 0:  0 -1:  0
total_duration =  318
max Id:  3
start =  25   end =  26
25   -1
Name: truth_int, dtype: int64
25    0
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  27
26   -1
Name: truth_int, dtype: int64
26    0
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  27
block_len 3
start =  0   end =  3
0    0
1    3
2    3
Name: truth_int, dtype: int64
0    499
1    120
2    200
Name: duration, dtype: int64
3:  320 2:  0 1:  0 0:  499 -1:  0
total_duration =  819
max Id:  0
start =  3   end =  6
3    0
4    3
5    3
Name: truth_int, dtype: int64
3    195
4    209
5    355
Name: duration, dtype: int64
3:  564 2:  0 1:  0 0:  195 -1:  0
total_duration =  759
max Id:  3
start =  6   end =  9
6    3
7    3
8    3
Name: truth_int, dtype: int64
6    103
7    194
8    195
Name: duration, dtype: int64
3:  492 2:  0 1:  0 0:  0 -1:  0
total_duration =  492
max Id:  3
start =  9   end =  12
9     2
10    3
11    3
Name: truth_int, dtype: int64
9     295
10    464
11    422
Name: duration, dtype: int64
3:  886 2:  295 1:  0 0:  0 -1:  0
total_duration =  1181
max Id:  3
start =  12   end =  15
12    3
13    3
14    3
Name: truth_int, dtype: int64
12    583
13    167
14     63
Name: duration, dtype: int64
3:  813 2:  0 1:  0 0:  0 -1:  0
total_duration =  813
max Id:  3
start =  15   end =  18
15    3
16    2
17    2
Name: truth_int, dtype: int64
15    133
16    155
17     82
Name: duration, dtype: int64

3:  133 2:  237 1:  0 0:  0 -1:  0
total_duration =  370
max Id:  2
start =  18   end =  21
18    3
19    3
20    3
Name: truth_int, dtype: int64
18    372
19    683
20    358
Name: duration, dtype: int64
3:  1413 2:  0 1:  0 0:  0 -1:  0
total_duration =  1413
max Id:  3
start =  21   end =  24
21    3
22    0
23    3
Name: truth_int, dtype: int64
21    267
22    295
23    247
Name: duration, dtype: int64
3:  514 2:  0 1:  0 0:  295 -1:  0
total_duration =  809
max Id:  3
start =  24   end =  27
24    3
25   -1
26   -1
Name: truth_int, dtype: int64
24    318
25      0
26      0
Name: duration, dtype: int64
3:  318 2:  0 1:  0 0:  0 -1:  0
total_duration =  318
max Id:  3
data len =  27
block_len 9
start =  0   end =  9
0    0
1    3
2    3
3    0
4    3
5    3
6    3
7    3
8    3
Name: truth_int, dtype: int64
0    499
1    120
2    200
3    195
4    209
5    355
6    103
7    194
8    195
Name: duration, dtype: int64
3:  1376 2:  0 1:  0 0:  694 -1:  0
total_duration =  2070
max Id:  3
start =  9   end =  18
9     2
10    3
11    3
12    3
13    3
14    3
15    3
16    2
17    2
Name: truth_int, dtype: int64
9     295
10    464
11    422
12    583
13    167
14     63
15    133
16    155
17     82
Name: duration, dtype: int64
3:  1832 2:  532 1:  0 0:  0 -1:  0
total_duration =  2364
max Id:  3
start =  18   end =  27
18    3
19    3
20    3
21    3
22    0
23    3
24    3
25   -1
26   -1
Name: truth_int, dtype: int64
18    372
19    683
20    358
21    267
22    295
23    247
24    318
25      0
26      0
Name: duration, dtype: int64
3:  2245 2:  0 1:  0 0:  295 -1:  0
total_duration =  2540
max Id:  3
data len =  27
block_len 27
start =  0   end =  27
0     0
1     3
2     3
3     0
4     3
5     3
6     3
7     3
8     3
9     2
10    3
11    3
12    3
13    3
14    3
15    3
16    2
17    2
18    3
19    3
20    3
21    3
22    0
23    3
24    3
25   -1
26   -1
Name: truth_int, dtype: int64
0     499
1     120
2     200
3     195
4     209
5     355
6     103
7     194
8     195
9     295
10    464
11    422
12    583
13    167
14     63
15    133
16    155
17     82
18    372
19    683
20    358
21    267
22    295
23    247
24    318
25      0
26      0
Name: duration, dtype: int64
3:  5453 2:  532 1:  0 0:  989 -1:  0
total_duration =  6974
max Id:  3
TheSocialNetwork_ice3.csv
TheSocialNetwork_ice3
data len =  3
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    1915
Name: duration, dtype: int64
3:  1915 2:  0 1:  0 0:  0 -1:  0
total_duration =  1915
max Id:  3
start =  1   end =  2
1    3
Name: truth_int, dtype: int64
1    2324
Name: duration, dtype: int64
3:  2324 2:  0 1:  0 0:  0 -1:  0
total_duration =  2324
max Id:  3
start =  2   end =  3
2    3
Name: truth_int, dtype: int64
2    2735
Name: duration, dtype: int64
3:  2735 2:  0 1:  0 0:  0 -1:  0
total_duration =  2735
max Id:  3
start =  3   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  9   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  10   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  11   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  12   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  13   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  14   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  15   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  16   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  17   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  18   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  19   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  20   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  21   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  22   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  23   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  24   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  25   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  3
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    1915
Name: duration, dtype: int64
3:  1915 2:  0 1:  0 0:  0 -1:  0
total_duration =  1915
max Id:  3
start =  1   end =  2
1    3
Name: truth_int, dtype: int64
1    2324
Name: duration, dtype: int64
3:  2324 2:  0 1:  0 0:  0 -1:  0
total_duration =  2324
max Id:  3
start =  2   end =  3
2    3
Name: truth_int, dtype: int64
2    2735
Name: duration, dtype: int64
3:  2735 2:  0 1:  0 0:  0 -1:  0
total_duration =  2735
max Id:  3
start =  3   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  4   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  5   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  6   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  7   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  8   end =  3
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  3
block_len 1
start =  0   end =  1
0    3
Name: truth_int, dtype: int64
0    1915
Name: duration, dtype: int64
3:  1915 2:  0 1:  0 0:  0 -1:  0
total_duration =  1915
max Id:  3
start =  1   end =  2
1    3
Name: truth_int, dtype: int64
1    2324
Name: duration, dtype: int64
3:  2324 2:  0 1:  0 0:  0 -1:  0
total_duration =  2324
max Id:  3
start =  2   end =  3
2    3
Name: truth_int, dtype: int64
2    2735
Name: duration, dtype: int64
3:  2735 2:  0 1:  0 0:  0 -1:  0
total_duration =  2735
max Id:  3

data len =  3
block_len 3
start =  0   end =  3
0    3
1    3
2    3
Name: truth_int, dtype: int64
0    1915
1    2324
2    2735
Name: duration, dtype: int64
3:  6974 2:  0 1:  0 0:  0 -1:  0
total_duration =  6974
max Id:  3
TheSocialNetwork_ice4.csv
TheSocialNetwork_ice4
failed for  TheSocialNetwork_ice4
TheSocialNetwork_ice8.csv
TheSocialNetwork_ice8
failed for  TheSocialNetwork_ice8
TheSocialNetwork_ice9.csv
TheSocialNetwork_ice9
data len =  9
block_len 1
start =  0   end =  1
0    0
Name: truth_int, dtype: int64
0    765
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  765 -1:  0
total_duration =  765
max Id:  0
start =  1   end =  2
1    3
Name: truth_int, dtype: int64
1    555
Name: duration, dtype: int64
3:  555 2:  0 1:  0 0:  0 -1:  0
total_duration =  555
max Id:  3
start =  2   end =  3
2    3
Name: truth_int, dtype: int64
2    595
Name: duration, dtype: int64
3:  595 2:  0 1:  0 0:  0 -1:  0
total_duration =  595
max Id:  3
start =  3   end =  4
3    3
Name: truth_int, dtype: int64
3    859
Name: duration, dtype: int64
3:  859 2:  0 1:  0 0:  0 -1:  0
total_duration =  859
max Id:  3
start =  4   end =  5
4    3
Name: truth_int, dtype: int64
4    1165
Name: duration, dtype: int64
3:  1165 2:  0 1:  0 0:  0 -1:  0
total_duration =  1165
max Id:  3
start =  5   end =  6
5    3
Name: truth_int, dtype: int64
5    300
Name: duration, dtype: int64
3:  300 2:  0 1:  0 0:  0 -1:  0
total_duration =  300
max Id:  3
start =  6   end =  7
6    3
Name: truth_int, dtype: int64
6    567
Name: duration, dtype: int64
3:  567 2:  0 1:  0 0:  0 -1:  0
total_duration =  567
max Id:  3
start =  7   end =  8
7    3
Name: truth_int, dtype: int64
7    1207
Name: duration, dtype: int64
3:  1207 2:  0 1:  0 0:  0 -1:  0
total_duration =  1207
max Id:  3
start =  8   end =  9
8    3
Name: truth_int, dtype: int64
8    961
Name: duration, dtype: int64
3:  961 2:  0 1:  0 0:  0 -1:  0
total_duration =  961
max Id:  3
start =  9   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  10   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  11   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  12   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  13   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  14   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  15   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  16   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  17   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  18   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  19   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  20   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  21   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  22   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  23   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  24   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  25   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
start =  26   end =  9
Series([], Name: truth_int, dtype: int64)
Series([], Name: duration, dtype: int64)
3:  0 2:  0 1:  0 0:  0 -1:  0
total_duration =  0
max Id:  -1
data len =  9
block_len 1
start =  0   end =  1
0    0
Name: truth_int, dtype: int64
0    765
Name: duration, dtype: int64
3:  0 2:  0 1:  0 0:  765 -1:  0
total_duration =  765
max Id:  0
start =  1   end =  2
1    3
Name: truth_int, dtype: int64
1    555
Name: duration, dtype: int64
3:  555 2:  0 1:  0 0:  0 -1:  0
total_duration =  555
max Id:  3
start =  2   end =  3
2    3
Name: truth_int, dtype: int64
2    595
Name: duration, dtype: int64
3:  595 2:  0 1:  0 0:  0 -1:  0
total_duration =  595
max Id:  3
start =  3   end =  4
3    3
Name: truth_int, dtype: int64
3    859
Name: duration, dtype: int64
3:  859 2:  0 1:  0 0:  0 -1:  0
total_duration =  859
max Id:  3
start =  4   end =  5
4    3
Name: truth_int, dtype: int64
4    1165
Name: duration, dtype: int64
3:  1165 2:  0 1:  0 0:  0 -1:  0
total_duration =  1165
max Id:  3
start =  5   end =  6
5    3
Name: truth_int, dtype: int64
5    300
Name: duration, dtype: int64
3:  300 2:  0 1:  0 0:  0 -1:  0
total_duration =  300
max Id:  3
start =  6   end =  7
6    3
Name: truth_int, dtype: int64
6    567
Name: duration, dtype: int64
3:  567 2:  0 1:  0 0:  0 -1:  0
total_duration =  567
max Id:  3
start =  7   end =  8
7    3
Name: truth_int, dtype: int64
7    1207
Name: duration, dtype: int64
3:  1207 2:  0 1:  0 0:  0 -1:  0
total_duration =  1207
max Id:  3
start =  8   end =  9
8    3
Name: truth_int, dtype: int64
8    961
Name: duration, dtype: int64
3:  961 2:  0 1:  0 0:  0 -1:  0
total_duration =  961
max Id:  3
data len =  9
block_len 3
start =  0   end =  3
0    0
1    3
2    3
Name: truth_int, dtype: int64
0    765
1    555
2    595
Name: duration, dtype: int64
3:  1150 2:  0 1:  0 0:  765 -1:  0
total_duration =  1915
max Id:  3
start =  3   end =  6
3    3
4    3
5    3
Name: truth_int, dtype: int64
3     859
4    1165
5     300
Name: duration, dtype: int64
3:  2324 2:  0 1:  0 0:  0 -1:  0
total_duration =  2324
max Id:  3
start =  6   end =  9
6    3
7    3
8    3
Name: truth_int, dtype: int64
6     567
7    1207
8     961
Name: duration, dtype: int64
3:  2735 2:  0 1:  0 0:  0 -1:  0
total_duration =  2735
max Id:  3
data len =  9
block_len 9
start =  0   end =  9
0    0
1    3
2    3
3    3
4    3
5    3
6    3
7    3
8    3
Name: truth_int, dtype: int64
0     765
1     555
2     595
3     859
4    1165
5     300
6     567
7    1207
8     961
Name: duration, dtype: int64
3:  6209 2:  0 1:  0 0:  765 -1:  0
total_duration =  6974
max Id:  3
WolfofWallStreet.csv
WolfofWallStreet
data len =  139
block_len 6
start =  0   end =  6
0    1.0
1    0.0
2    3.0
3    3.0
4    3.0
5    3.0
Name: truth_int, dtype: float64
0    34
1    23
2    93
3    40
4    83
5    29
Name: duration, dtype: int64
3:  245 2:  0 1:  34 0:  23 -1:  0
total_duration =  302
max Id:  3
start =  6   end =  12
6     3.0
7     3.0
8     3.0
9     3.0
10    3.0
11    0.0
Name: truth_int, dtype: float64
6      36
7      38
8      59
9     194
10    125
11     40
Name: duration, dtype: int64
3:  452 2:  0 1:  0 0:  40 -1:  0
total_duration =  492
max Id:  3
start =  12   end =  18
12    2.0
13    NaN
14    NaN
15    2.0
16    NaN
17    2.0
Name: truth_int, dtype: float64
12     22
13     20
14     71
15     69
16    173
17    123
Name: duration, dtype: int64
3:  0 2:  214 1:  0 0:  0 -1:  0
total_duration =  478
failed for  WolfofWallStreet
WolfofWallStreet_ice1.csv
WolfofWallStreet_ice1
failed for  WolfofWallStreet_ice1
WolfofWallStreet_ice2.csv
WolfofWallStreet_ice2
failed for  WolfofWallStreet_ice2
WolfofWallStreet_ice4.csv
WolfofWallStreet_ice4
failed for  WolfofWallStreet_ice4
WolfofWallStreet_ice8.csv
WolfofWallStreet_ice8
failed for  WolfofWallStreet_ice8

In [27]:
score = pd.read_csv("selma_ice8.csv")

In [28]:
score.head()

   Unnamed: 0    0
0           0  3.0
1           1  3.0
2           2  3.0
3           3  3.0
4           4  2.0